### ISSUE TITLE
mysql cookbook not adding grant 'root'@'ip address'

### ISSUE THREAD

**Issue by doublerr** [rcbops/chef-cookbooks#166]
The recipes for keystone,etc are tying to connect to mysql as 'root'@'10.0.2.15' (for example) however there is no grant for root @ ipaddress; there is only root @ localhost and 127.0.0.1.

Set allow_remote_root = true in mysql attribute to fix this.

I'll be adding a Pull request for this issue.

**Comment by doublerr** [comment]
https://github.com/rcbops/mysql/pull/1

**Comment by breu** [comment]
addressed in https://github.com/rcbops-cookbooks/mysql/pull/1
