### ISSUE TITLE
Mysql passwords fail to be set correctly

### ISSUE THREAD

**Issue by hurrycane** [rcbops/chef-cookbooks#18]
Hello,

I'm using the cookbooks from the main branch. After adding the single-controller role to the run list of a freshly created ec2 instance running Ubuntu 11.10 - the chef-client there fails saying that keystone-manage could not connect to the database.
I've checked manually the passwords for all the [nova,keystone,glance,dash] users and none of them have the required passwords.

I've found that disabling the condition not_if in the keystone recipe fixes this problem.

Thanks!
Bogdan

PS: Also could you please provide some docs for exactly how to use the recipes? I'm understand the big picture of how chef runs but i'm sure that the jsons in the examples folders need to be used somehow. Thanks!

**Comment by galstrom21** [comment]
Bogdan, just saw this.. i have a fix that i am testing.. will merge once i verify that it works

**Comment by galstrom21** [comment]
Latest patch set should resolve this issue

**Comment by hurrycane** [comment]
Thanks!
