### ISSUE TITLE
MySQL cookbook should disable "log-queries-not-using-indexes"

### ISSUE THREAD

**Issue by doublerr** [rcbops/chef-cookbooks#196]
OpenStack queries don't use indexes very well and enabling this option causes a very large slow query log file.

We saw a 45GB in 2 days without much load on the environment.

We should disable this variable or allow it to be enabled/disabled via an override.

Ryan

**Comment by breu** [comment]
Patch submitted in https://github.com/rcbops-cookbooks/mysql/pull/9

**Comment by breu** [comment]
This has been resolved in the latest sprint cookbooks
