### ISSUE TITLE
Allow overcommit overrides in nova.conf

### ISSUE THREAD

**Issue by doublerr** [rcbops/chef-cookbooks#198]
Request has been made to allow overcommit cpu/ram. 

I believe the flags are --max_cores and --max_gigabytes which i believe should be configurable at the node level.

**Comment by galstrom21** [comment]
The memory overcommit is here (i think):
https://github.com/openstack/nova/blob/stable/essex/nova/scheduler/filters/ram_filter.py#L24-26

The cpu overcommit is here (i think):
https://github.com/openstack/nova/blob/stable/essex/nova/scheduler/filters/core_filter.py#L26-28

**Comment by doublerr** [comment]
We need the ability to set these attributes as overrides.

Also is this the correct repo or should we be using https://github.com/rcbops-cookbooks

**Comment by galstrom21** [comment]
I would prefer you open issues in the repo for the item.. for this one it would be nova.. that way we can reference the issue in the commit messages and have them tied together.

**Comment by doublerr** [comment]
closing and will open issue in rcbops-cookbooks/nova
