### ISSUE TITLE
collectd issue in latest sprint branch

### ISSUE THREAD

**Issue by doublerr** [rcbops/chef-cookbooks#202]
With the latest sprint branch, chef bombs on the follow error:

[Tue, 24 Jul 2012 00:47:14 +0000] INFO: template[/etc/collectd/plugins/mysql.conf] sending restart action to service[collectd](delayed)
[Tue, 24 Jul 2012 00:47:14 +0000] INFO: Processing service[collectd] action restart (collectd::default line 98)
[Tue, 24 Jul 2012 00:48:15 +0000] ERROR: service[collectd](collectd::default line 98) has had an error
[Tue, 24 Jul 2012 00:48:15 +0000] ERROR: Running exception handlers
[Tue, 24 Jul 2012 00:48:31 +0000] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
[Tue, 24 Jul 2012 00:48:31 +0000] ERROR: Exception handlers complete
[Tue, 24 Jul 2012 00:48:31 +0000] ERROR: Mixlib::ShellOut::ShellCommandFailed: service[collectd](collectd::default line 98) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /etc/init.d/collectd restart ----
STDOUT: Restarting statistics collection and monitoring daemon: collectd . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
STDERR: configfile: stat (/etc/collectd/thresholds/*.conf) failed: No such file or directory

WARNING: collectd might still be running.
In large setups it might take some time to write all pending data to
the disk. You can adjust the waiting time in /etc/default/collect.
---- End output of /etc/init.d/collectd restart ----

I was able to get around this by testing with a dummy conf file but it still did not restart appropriately or in the way chef is expecting.

**Comment by breu** [comment]
Hi Ryan,

Can you provide the run_list for the node that saw this error?

knife node show <fqdn>

-breu

**Comment by doublerr** [comment]
"run_list": [
    "recipe[<specific network manager for customer>]",
    "role[single-controller]",
    "role[collectd-server]",
    "role[collectd-client]",
    "role[graphite]",
    "recipe[graphite::statsd]"

**Comment by JCallicoat** [comment]
This isn't chef specific, btw. Calling `service collectd restart` often leaves collectd still running after timing out waiting to stop it (at least, in our environments). You can HUP the collectd process (not collectdmon), but I think that risks losing uncommitted data.
