### ISSUE TITLE
can't add role[single-controller] without '

### ISSUE THREAD

**Issue by williamherry** [rcbops/chef-cookbooks#222]
Hi, I am try to use this cookbooks to install openstack on centos 6.2, at the beggining I meet this odd problem

```
knife node run list add all.chef.com role[single-controller]
# returns
run_list:  recipe[roles]
```

`role[allinone]` can be added correctly, also, add `role[single-controller]` to `'` works fine, it not `chef-cookbooks` 's problem, but I just want to know that if some thing I don't know yet about chef

BTW, I try to test this cookbook on centos6.2, any question will report here, if you don't mind

**Comment by breu** [comment]
Hello,

I verified what you reported is indeed occurring

knife node run_list add ubuntu role[nova-scheduler]
run_list: 
    role[single-controller]
    role[single-compute]
    recipe[roles]

knife node run_list add ubuntu 'role[nova-scheduler]'
run_list: 
    role[single-controller]
    role[single-compute]
    recipe[roles]
    role[nova-scheduler]

Are you using OpsCode hosted chef or your own Open Source chef server?

**Comment by williamherry** [comment]
no, I use my own chef server, is it a bug of chef or should we just use `'`?

**Comment by breu** [comment]
This is bash shell expansing biting you.  Quote with ' and you'll be fine.
