### ISSUE TITLE
Missing gem 'right_aws' and 'mysql'

### ISSUE THREAD

**Issue by williamherry** [rcbops/chef-cookbooks#223]
this message in log

```
WARN: Missing gem 'right_aws'
INFO: Missing gem 'mysql'
```

which cookbook should I report to?

**Comment by breu** [comment]
These notices are normal and will not cause any issues with chef.  The MySQL cookbook will install these as part of its normal run if needed.

If you need to install these before the first run you can do so with

/opt/chef/embedded/bin/gem install mysql

You will need to have installed the mysqlclient libraries and most likely gcc.
