### ISSUE TITLE
Can't find network nova

### ISSUE THREAD

**Issue by johnbarney** [rcbops/chef-cookbooks#237]
fresh install of chef and OS

Recipe Compile Error in /var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb
## RuntimeError

Can't find network nova
## Cookbook Trace:

  /var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:289:in `get_ip_for_net'
  /var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:147:in`get_bind_endpoint'
  /var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:24:in `from_file'

  "run_list": [
    "role[single-controller]"
  ]

**Comment by mancdaz** [comment]
Hi @johnb0011,

Did you define the networks in your chef environment?  Take a look at the example environment here:

https://github.com/rcbops/chef-cookbooks/blob/master/environments/example.json#L50

Darren

**Comment by johnbarney** [comment]
My nodes were still set to _default. This solved my problem. Thank you.
