### ISSUE TITLE
RHEL 6.2 qpid conflicts with rabbitmq port

### ISSUE THREAD

**Issue by budjb** [rcbops/chef-cookbooks#242]
Using the "Basic Server" installation type in RHEL 6.2, qpid is installed and run on the same port rabbitmq is configured to run on.  Because of this, the chef installation fails when trying to start rabbitmq.

To move past this step, I did the following:
yum remove -y qpid-*

This removed the following packages:
qpid-cpp-client
qpid-cpp-client-ssl
qpid-cpp-server
qpid-cpp-server-ssl
qpid-qmf

Plus the following for dependencies:
matahari
matahari-agent-lib
matahari-broker
matahari-host
matahari-network
matahari-service
matahari-sysconfig

Once these packages are removed rabbitmq starts.

**Comment by galstrom21** [comment]
Closing this as it is 6 months old and I believe it has been resolved.. please reopen if this issue is still active on the current version.
