### ISSUE TITLE
Auto-assignment of floating IPs is not supported

### ISSUE THREAD

**Issue by budjb** [rcbops/chef-cookbooks#245]
I have been working with Rightscale and their integration with Alamo installs, and they require public IP addresses on their instances they create.  Openstack supports auto-assignment of IP addresses, but this does not work on Alamo since the nova.conf gets regenerated on every chef-client run.  We need a configuration option to persist this specific config option.

**Comment by galstrom21** [comment]
auto_assign_floating_ip (Default: False) - 135:network/manager.py

**Comment by galstrom21** [comment]
Moving to https://github.com/rcbops-cookbooks/nova/issues/184
