### ISSUE TITLE
Provide support for volumes

### ISSUE THREAD

**Issue by sacharya** [rcbops/chef-cookbooks#246]
I didn't see an issue already created for volumes.

**Comment by mancdaz** [comment]
Hi @sacharya, there is already support for nova volumes - simply add this role to the relevant node:

https://github.com/rcbops/chef-cookbooks/blob/master/roles/nova-volume.rb

Obviously you need to create your own volume group (nova-volumes), but otherwise everything is there.

**Comment by breu** [comment]
It looks like there may need to be a cookbook change to get this to work on both ubuntu and rhel.

We need to
- template out iscsi_helper
  - ubuntu = /usr/sbin/ietadm
  - rhel based = /usr/sbin/tgtadm
  - package dependencies are taken care of already
- set the nova-volumes service to start on boot.
- figure out how dash works with a nova-volumes service running but with no vg created

**Comment by rpedde** [comment]
Recent Ubuntu are tgt also

**Comment by breu** [comment]
Working on this in https://github.com/rcbops-cookbooks/nova/pull/178

**Comment by breu** [comment]
This is available now per https://github.com/rcbops-cookbooks/nova/pull/178
