### ISSUE TITLE
RHEL: SNATing not working for instances; instances can not reach the web

### ISSUE THREAD

**Issue by budjb** [rcbops/chef-cookbooks#247]
There is a problem where the nova.conf has the wrong values for public_interface and fixed_range that causes instances to be able to do any outbound traffic.  The values get set to the defaults of eth0 and 192.168.100.0/24, respectively.  Once I plug the correct values for the machine's configuration, outbound traffic starts working.

**Comment by galstrom21** [comment]
moving to rcbops-cookbooks/nova/issues/187
