### ISSUE TITLE
apache2 commit a9325a3180eea20cf2a9148cab84e3e9c5fcb540 breaks alamo-installer

### ISSUE THREAD

**Issue by breu** [rcbops/chef-cookbooks#248]
introduction of minitests has a broken symlink and causes the cookbook upload to fail on the iso

**Comment by breu** [comment]
we need to revert to 7784e31fd547465573a141e1f6a19a98f774f8e4

**Comment by mancdaz** [comment]
@rackerjoe can we close this?

**Comment by galstrom21** [comment]
closing as this issue is over 2 months old
