### ISSUE TITLE
[Severity 1] chef could not find recipe -volume for cookbook nova

### ISSUE THREAD

**Issue by panpengjun** [rcbops/chef-cookbooks#254]
When enabling swift storage in image service by executing 

knife exec -E '@e=Chef::Environment.load("rpcs"); a=@e.
override_attributes; \
a["glance"].merge!({"api" => {"default_store" => "swift"}}); \
@e.override_attributes(a); @e.save'

chef returns an error saying "Could not find recipe -volume for cookbook nova". Sprint branch is used.

**Comment by galstrom21** [comment]
@panpengjun: can you post your chef-environment

looks like you are missing the package_component key

**Comment by panpengjun** [comment]
Please take a look at this. https://gist.github.com/3981165

**Comment by breu** [comment]
@panpengjun also need the output from 'knife node show' on the node that is failing.  I'll bet you have a recipe in the runlist named just -volume which is incorrect

**Comment by galstrom21** [comment]
@panpengjun: you are missing package_component in your environment..

Take a look at the example environment file: https://github.com/rcbops/chef-cookbooks/blob/sprint/environments/example.json#L58

**Comment by panpengjun** [comment]
Joe,

I've checked all nodes with their runlist and recipes. I don't have
anything named -volume.

PJ

**Comment by panpengjun** [comment]
Hey Justin,

Your fix does work.

But curiously, when v2 is released, do I need to add this line manually or the new environment will include it?

PJ

**Comment by galstrom21** [comment]
@panpengjun: the v2 iso will have this set in the environment set automatically..

**Comment by panpengjun** [comment]
So the reason I missed this line is because v1 does not set it. Am I
correct?

PJ

**Comment by klevenstein** [comment]
Would it be fair to say that when upgrading from an existing v1 installation, the user should set package_component to "essex-final" or "folsom" depending on what the user needs for their cluster?
