### ISSUE TITLE
[Severity 1] Block Migration Fails Silently

### ISSUE THREAD

**Issue by panpengjun** [rcbops/chef-cookbooks#258]
I found a bug in the block migration test. The detail info is given as following.
1. 364025-aio: AIO installation of Alamo v2 generated using alamo builder built by Jacob.
2. 364026-compute: Compute node installation of Alamo v2 generated using alamo builder built by Jacob.
3. Create an 512 MB cirros instance on 364025-aio.
4. nova live-migration --block_migrate <instance ID> 364026-compute
5. System does not return an error. nova boot shows it is in migrating.
6. When the status turns to ACTIVE, nova show <instance ID>. It is still in 364025-aio.
7. Check the actual instance file. They are in 364025-aio instead of 364026-compute.
8. Check /var/log/nova/nova-scheduler.log, nova-network.log, nova-compute.log, no error message.
9. Create another vm and migrate, works.

I have sent to you the sosreport before and after the failure.

**Comment by breu** [comment]
Hi Pengjun,

Can you send us the sosreport for 364026-compute as it sits right now?

**Comment by breu** [comment]
for my notes:

relevant line from the source node

2012-10-31 18:12:19 ERROR nova.virt.libvirt.driver [-] [instance: fa46a443-9b13-4b81-a2f2-f6ef7cb1e51d] Live Migration failure: operation failed: Failed to connect to remote libvirt URI qemu+tcp://364026-compute/system

libvirt log
2012-10-31 22:19:10.580+0000: 24927: error : virNetSocketNewConnectTCP:411 : Unable to resolve address '364026-compute' service '16509': Name or service not known
2012-10-31 22:19:11.379+0000: 24927: error : doPeer2PeerMigrate:2233 : operation failed: Failed to connect to remote libvirt URI qemu+tcp://364026-compute/system

**Comment by panpengjun** [comment]
Since I have tried a couple of times, this may related to an earlier
migration error. I've replied through rackspace mail already.

PJ

**Comment by breu** [comment]
Hi Pengjun,

I was able to duplicate this with an all-in-one and a single compute node.  The problem is that /etc/hosts does not get updated on the controller node to reflect the IP address and name mappings for the compute node and this is required for live migration.

To resolve the issue re-run chef-client on the controller node.

After this is done /etc/hosts is updated and migration works correctly.

**Comment by panpengjun** [comment]
Hi Joe,

Do you mean that the end users have to re-run chef-client manually to make
it work? Or do you think there will be a fix in the iso or your chef
cookbook?

PJ

**Comment by breu** [comment]
for the purpose of this cookbook, yes.  I have created a separate issue for the alamo issue here https://github.com/rcbops/alamo-builder/issues/28.  I will leave this issue closed.

**Comment by panpengjun** [comment]
Please let me know when this is fixed. We will recreate a minimal CD for
testing. For now, I will just use your instructions. Thanks a lot.

PJ
