### ISSUE TITLE
Block Migration Status Not Updated

### ISSUE THREAD

**Issue by panpengjun** [rcbops/chef-cookbooks#260]
1. Migrate a vm from aio to compute node.
2. Nova list shows MIGRATING status.
3. Instance directory has actually been moved to the compute node. Can ping and ssh to the vm.

Could not reproduce.

**Comment by mancdaz** [comment]
@panpengjun - I'm a little confused - what could you not reproduce? Did the block migration work ok this time?

Are you saying that the migration worked but the status did not change properly?  if so, this is a bug in OpenStack rather than with the chef cookbooks.

**Comment by panpengjun** [comment]
I was not able to produce this issue. May be caused by an openstack issue. I am about to close it.
