### ISSUE TITLE
[Severity 1] collectd breaks in MySQL Replication

### ISSUE THREAD

**Issue by panpengjun** [rcbops/chef-cookbooks#271]
collectd breaks when replacing the active node by the standby node. Failed when running chef-client.

**Comment by mancdaz** [comment]
@panpengjun could you please give a little more detail on exactly what you did, what the error output was from chef etc?  You can paste the output of your chef run, and any relevant log files, on http://paste.openstack.org/

**Comment by panpengjun** [comment]
I will do it either tonight or tomorrow morning. I am out currently and do
not have my RSA token.

PJ

**Comment by breu** [comment]
abandoned.  closing.
