### ISSUE TITLE
Issue with dsh_group[nova], nova::nova-common

### ISSUE THREAD

**Issue by xin-e-liu** [rcbops/chef-cookbooks#298]
Hi guys, 

I got the following error when working with Ruby 1.9.3, gems 1.8 and chef client 10.18.2. It seems to be an issue that has been resolved, but somehow reappear: https://github.com/rcbops-cookbooks/nova/issues/149

Thanks,
Xin

Generated at Fri Jan 25 09:32:55 -0800 2013
TypeError: dsh_group[nova](nova::nova-common line 89) had an error: TypeError: can't convert Hash into String
/var/chef/cache/cookbooks/dsh/providers/group.rb:148:in `system'
/var/chef/cache/cookbooks/dsh/providers/group.rb:148:in`get_pubkey'
/var/chef/cache/cookbooks/dsh/providers/group.rb:85:in `class_from_file'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/provider.rb:203:in`instance_eval'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/provider.rb:203:in `action_join'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/provider.rb:119:in`send'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/provider.rb:119:in `run_action'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/resource.rb:597:in`run_action'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/runner.rb:49:in `run_action'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/runner.rb:81:in`converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/runner.rb:81:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/runner.rb:81:in`converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in`call'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in`step'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in`each_with_index'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/runner.rb:80:in`converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/client.rb:378:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/client.rb:420:in`do_run'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/client.rb:176:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/application.rb:140:in`run_chef_client'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/application/client.rb:274:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/application/client.rb:267:in`loop'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/application/client.rb:267:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/../lib/chef/application.rb:72:in`run'
/usr/lib/ruby/gems/1.8/gems/chef-10.18.2/bin/chef-client:26
/usr/bin/chef-client:23:in `load'
/usr/bin/chef-client:23

root@os-server1:/usr/lib/ruby# ruby -v
ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux]

**Comment by breu** [comment]
How did you install the chef client?  We have seen issues like this when you are using the system packages for chef and ruby.  We recommend installing chef with the opscode installer that includes ruby and gem binaries that work with the specific version of chef-client and can be installed alongside the system binaries without interfering.

You can install this client with
curl -skS http://www.opscode.com/chef/install.sh | /bin/bash

NOTE: you should delete chef-client that you installed through the system repositories.

Please install the chef-client with the opscode installer.  This should resolve your issues.

**Comment by xin-e-liu** [comment]
Thanks Joe. I actually installed through gem. I'll try installation from source. 

Xin

**Comment by breu** [comment]
It is not a source install but a packaged binary installation with ruby, gem, and chef-client of known working combinations.

**Comment by xin-e-liu** [comment]
Yeah, I have tried installation from ubuntu repository and gem... Haven't tried source. Will do that.

Xin

**Comment by xin-e-liu** [comment]
I have tried to use chef from source, things are working. Sweet!

**Comment by galstrom21** [comment]
@codeoedoc: closing this issue as it is now working for you
