### ISSUE TITLE
role[allinone] does not include nova-api

### ISSUE THREAD

**Issue by xin-e-liu** [rcbops/chef-cookbooks#300]
Hi guys, 

I think role[allinone] is missing the nova-api role, which is needed for retrieving metadata. I have included this additional role, and it seems the VM is able to download metadata. 

Thanks,
Xin

**Comment by mancdaz** [comment]
@codeoedoc,

The allinone role includes the single-compute role, which itself includes the two role nova-api-os-compute and nova-api-ec2.  If you look at the nova-api role, it simply includes just nova-api-os-compute and nova-api-ec2.  Hence the allinone role does include the necessary api roles.

@mancdaz

**Comment by xin-e-liu** [comment]
Hi Darren, 

With the allinone role, the installation is missing the nova-api-metadata process. I added both the nova:api-metadata recipt and nova-api role. As you pointed out that nova-api is already there, then probably we are missing the nova:api-metadata recipt in the allineone role?

Thanks,
Xin

**Comment by breu** [comment]
Xin,

allinone breaks out into single-controller and single-compute.  single-compute calls the nova::compute recipe that includes nova::api-metadata as the second line of the recipe.  

What version of the nova cookbook are you utilizing?  Either a SHA or the version number located in metadata.rb will suffice.

**Comment by xin-e-liu** [comment]
Hi Darren, 

I'm using the latest 1.0.17. Seems the nova::compute recipe is not including nova::api-metadata?... I must be missing something... 
https://github.com/rcbops-cookbooks/nova/blob/master/recipes/compute.rb

Thanks,
Xin

**Comment by mancdaz** [comment]
@codeoedoc @rackerjoe 

I suspect this commit is the cause:

https://github.com/rcbops-cookbooks/nova/commit/bbb386fddf328696e90bcf1da09fe0f4c0f9698a

**Comment by galstrom21** [comment]
nova::api-metadata has been moved over.. and is now sourced by nova-network::nova-compute

https://github.com/rcbops-cookbooks/nova-network/blob/master/recipes/nova-compute.rb#L17-L20
