### ISSUE TITLE
librarian-chef instead of submodules?

### ISSUE THREAD

**Issue by ziadsawalha** [rcbops/chef-cookbooks#306]
Have you considered using [librarian-chef](https://github.com/applicationsonline/librarian/blob/master/README.md#the-cheffile) instead of git submodules?

**Comment by willkelly** [comment]
Hello ziad!  We actually spoke about using librarian with opscode, but it unfortunately did not fit all of our needs.  It can certainly be used in conjunction with our repo from people who care to use it, but we're sticking with submodules for the time being.

**Comment by ziadsawalha** [comment]
Thanks, @willkelly.
