### ISSUE TITLE
autoetchosts overriding IPs with floating IPs

### ISSUE THREAD

**Issue by doublerr** [rcbops/chef-cookbooks#315]
Multiple users (https://privatecloudforums.rackspace.com/viewtopic.php?f=4&t=301) are reporting that the autoetchosts recipe will overwrite /etc/hosts entries for compute nodes if a floating IP is assigned to an instance.

The exact situation is when the floating IP range is from the same network range as the host (management) network. This means on the public_interface, there will be two IP addresses from the same range if a floating IP is assigned. Chef will then update the /etc/hosts file with  the floating IP as opposed to the IP originally assigned. This then impacts openstack functions when trying to communicate with other hosts (migration, etc).

The answer may simply be "don't use floating IPs from the same range as your physical hosts" but I wanted to open this issue to see if the recipe can be modified to help prevent this issue.

Steps to reproduce: 
1. Create floating IPs from the same range as the management network
2. Assign floating IPs to instances
3. re-run chef-client on the compute nodes
4. check /etc/hosts to see if the entries have been modified

**Comment by breu** [comment]
@doublerr This should be resolved in https://github.com/rcbops-cookbooks/osops-utils/blob/master/libraries/ip_location.rb#L353 which has been in since c491bbda05c4123c043c3f2202285d2abb63f509.  Can you verify that you have at least version 1.0.10 of the osops-utils cookbook?

**Comment by breu** [comment]
I am going to mark this as not-a-bug for now...  Let me know if this is still affecting you.

**Comment by breu** [comment]
@doublerr have you had a chance to try the fix noted above?

**Comment by doublerr** [comment]
I just tried a later set of the cookbooks. Looks to have been fixed.
