### ISSUE TITLE
[Folsom] Floating IPs do not move after resize

### ISSUE THREAD

**Issue by DavidWittman** [rcbops/chef-cookbooks#316]
#### :rotating_light: Spoiler Alert :rotating_light:

This is a bug in Nova, not the Chef cookbooks.
### Issue

The bridge and NAT configurations for floating IP addresses are not migrated to the destination host after a confirmed resize.
### Steps to reproduce
1. Build an instance
2. Assign a floating IP address to that instance
3. Resize the instance and confirm the resize
4. Try to access instance via floating IP, and/or check bridge/NAT rules on the source host.
### Workaround
1. Disassociate the floating IP. `nova remove-floating-ip <instance-uuid> <floating-ip>`
2. Reassociate the floating IP on the new host. `nova add-floating-ip <instance-uuid> <floating-ip>`
3. Restart nova-network on the source host to remove the old bridge config and NAT rules. `service nova-network restart`
### Affects

Folsom
### Launchpad Bug

https://bugs.launchpad.net/nova/+bug/1053344

**Comment by mancdaz** [comment]
@DavidWittman 

Thanks for the detail.  I'm going to close this issue as it's not something that is targeted against our cookbooks (ie we can't fix it here).
