### ISSUE TITLE
[DE88] OpenCenter issue on CentOS 6.3 - mysql cookbook

### ISSUE THREAD

**Issue by doublerr** [rcbops/chef-cookbooks#317]
Forum Post: https://privatecloudforums.rackspace.com/viewtopic.php?f=4&t=351

Mysql is not starting due to the following error: InnoDB: Error: ib_logfiles are too small for innodb_thread_concurrency 64.

Fix is to lower the concurrency to a lower value.

**Comment by breu** [comment]
This is a problem in the upstream of the mysql cookbook from opscode.  Currently it is set to:

 # of cpus \* 2

So it would appear that the candidate server is either running 32 cores or at least 16 cores with hyperthreading enabled.

What is the maximum size of innodb_thread_concurrency based on the size of the ib_logfiles?

**Comment by DavidWittman** [comment]
> InnoDB: Error: ib_logfiles are too small for innodb_thread_concurrency 8.
> InnoDB: The combined size of ib_logfiles should be bigger than
> InnoDB: 200 kB \* innodb_thread_concurrency.
> InnoDB: To get mysqld to start up, set innodb_thread_concurrency in my.cnf
> InnoDB: to a lower value, for example, to 8. After an ERROR-FREE shutdown
> InnoDB: of mysqld you can adjust the size of ib_logfiles, as explained in
> InnoDB: http://dev.mysql.com/doc/refman/5.0/en/adding-and-removing.html
> InnoDB: Cannot continue operation. Calling exit(1).

By that math, it looks the maximum innodb_thread_concurrency is 25 based on a [default innodb_log_file_size of 5M](https://github.com/opscode-cookbooks/mysql/blob/master/attributes/server.rb#L188).

However, rather than capping the thread concurrency, it's probably a better idea from a performance perspective to jack up the innodb_log_file_size considerably (64M+) and disable thread concurrency checks by setting innodb_thread_concurrency to 0. This is the default in MySQL 5.5 and is [recommended by the savants at Percona](http://dba.stackexchange.com/questions/5666/possible-to-make-mysql-use-more-then-one-core/5670#5670).

**Comment by breu** [comment]
Changing the value of innodb_log_file_size on an already installed system will break MySQL so your recommendation will only work on new installs.  Changing the default attribute will propagate the attribute value to nodes that do not have an override in place.  

We will move forward with capping thread concurrency and fix it in the MySQL-openstack cookbook but this bug needs to be reported upstream to opscode.

**Comment by DavidWittman** [comment]
Why not set thread concurrency to 0 instead? It's the recommended setting
and should address this issue without breaking existing environments.
On Mar 8, 2013 5:47 PM, "Joe Breu" notifications@github.com wrote:

Changing the value of innodb_log_file_size on an already installed system
will break MySQL so your recommendation will only work on new installs.
Changing the default attribute will propagate the attribute value to nodes
that do not have an override in place.

We will move forward with capping thread concurrency and fix it in the
MySQL-openstack cookbook but this bug needs to be reported upstream to
opscode.

—
Reply to this email directly or view it on
GitHubhttps://github.com/rcbops/chef-cookbooks/issues/317#issuecomment-14652838
.

**Comment by mancdaz** [comment]
FYI:

http://tickets.opscode.com/browse/COOK-2102 was already raised, so I attached a fix there.

https://github.com/opscode-cookbooks/mysql/pull/82
