### ISSUE TITLE
FATAL: RuntimeError: Can't find network management

### ISSUE THREAD

**Issue by amaltson** [rcbops/chef-cookbooks#320]
I have a fresh Ubuntu 12.04.2 LTS install that I'm trying to setup OpenStack on. I'm using Chef and have assigned this particular node `role[single-controller]` and `role[single-compute]`. When I run chef-client, I'm getting:

```
[2013-03-12T19:47:10-04:00] ERROR: Can't find network management

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb
================================================================================

RuntimeError
------------
Can't find network management

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:346:in `get_ip_for_net'
  /var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:151:in `get_bind_endpoint'
  /var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:29:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:

339:          node["osops_networks"]["mapping"].has_key?(network)
340:        network = node["osops_networks"]["mapping"][network]
341:      end
342:
343:      if not (node.has_key?("osops_networks") and node["osops_networks"].has_key?(network)) then
344:        error = "Can't find network #{network}"
345:        Chef::Log.error(error)
346>>       raise error
347:      end
348:
349:      net = IPAddr.new(node["osops_networks"][network])
350:      node["network"]["interfaces"].each do |interface|
351:        if interface[1].has_key?("addresses") then
352:          interface[1]["addresses"].each do |k,v|
353:            if v["family"] == "inet6" or (v["family"] == "inet" and v["prefixlen"] != "32") then
354:              addr=IPAddr.new(k)
355:              if net.include?(addr) then

[2013-03-12T19:47:10-04:00] ERROR: Running exception handlers
[2013-03-12T19:47:10-04:00] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
[2013-03-12T19:47:10-04:00] ERROR: Exception handlers complete
[2013-03-12T19:47:10-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2013-03-12T19:47:10-04:00] FATAL: RuntimeError: Can't find network management
```

I also have the [full chef-client run](https://gist.github.com/amaltson/5148213).

I should mention that I'm not using this chef-cookbooks repo directly. I've installed all the opscode cookbooks (except RabbitMQ, using the one on GitHub because openstack needs a newer version) using `knife cookbook site install` and `cp`ed over the OpenStack cookbooks. I uploaded everything to the Chef server.

Thank you in advance.

**Comment by mancdaz** [comment]
Hi @amaltson 

This collection of cookbooks is fairly tightly intertwined, and as such is only designed to run when the cookbooks used are those that the submodules point directly at.  

That said, it looks like the issue you are having is that you have not defined any osops-networks in your environment.  See example here: https://github.com/rcbops/chef-cookbooks/blob/master/environments/example.json#L53-L56

These networks should exist, and the node in question should have an IP address on the relevant network that the cookbook is using.

Hope that helps.  If you have any further issues, please clone the entire parent repo, and do a full submodule init/update, and then upload the cookbooks in the cookbooks subdirectory to your chef server (probably best to purge all similarly named cookbooks from your chef server first to prevent version conflicts).

Thanks
@mancdaz

**Comment by amaltson** [comment]
Thanks @mancdaz, I'm starting to get further now. I put in the entire example json (slightly modified for our setup). I'm not getting stuck on:

```
[2013-03-13T11:06:24-04:00] FATAL: You can only have one node with the glance-setup role

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/glance/recipes/setup.rb
================================================================================

SystemExit
----------
exit

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/glance/recipes/setup.rb:36:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/glance/recipes/setup.rb:

 29:    release = "folsom"
 30:  end
 31:
 32:  platform_options = node["glance"]["platform"][release]
 33:
 34:  # make sure we die if there are multiple glance-setups
 35:  if other_setup = get_settings_by_role("glance-setup", "glance", false)
 36>>   Chef::Application.fatal! "You can only have one node with the glance-setup role"
 37:  end
 38:
 39:  unless node["glance"]["db"]["password"]
 40:    Chef::Log.info("Running glance setup - setting glance passwords")
 41:  end
 42:
 43:  if node["developer_mode"]
 44:    node.set_unless["glance"]["db"]["password"] = "glance"
 45:  else

[2013-03-13T11:06:24-04:00] ERROR: Running exception handlers
[2013-03-13T11:06:24-04:00] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
[2013-03-13T11:06:24-04:00] ERROR: Exception handlers complete
```

I do want to have just one node (for now), is that not allowed? As mentioned above, this node has the roles `role[single-controller]` and `role[single-compute]`, which, if I understood it correctly, is the same as `role[allinone]`. I use those roles directly because I want to add more compute nodes in the future.

**Comment by mancdaz** [comment]
@amaltson 

Are there definitely no other nodes in this chef_environment that may also have the glance-setup role (either directly, or because they also have the single-controller role).  The error you are seeing is because the search in the recipe has found another node that has this role assigned, which is not allowed since this role is where passwords are set etc.

**Comment by amaltson** [comment]
@mancdaz 

Just checked the runlist of all my nodes and definitely only one node (the openstack node) has the `glance-setup` recipe. It doesn't have it as a role though. The FQDN for the node isn't valid.. could that be it? Here's the node's info, not sure if it helps:

```
knife node show openstack1
Node Name:   openstack1
Environment: openstack
FQDN:        ubuntu-openstack.<internal.network>
IP:          some.ip.address
Run List:    role[single-controller], role[single-compute]
Roles:       single-controller, base, mysql-master, rabbitmq-server, keystone, keystone-api, glance-setup, glance-registry, glance-api, nova-setup, nova-network-controller, nova-scheduler, nova-api-ec2, nova-api-os-compute, nova-volume, nova-cert, nova-vncproxy, horizon-server, single-compute, nova-network-compute
Recipes:     osops-utils::packages, openssh, ntp, sosreport, rsyslog::default, hardware, osops-utils::default, mysql-openstack::server, erlang::default, rabbitmq-openstack::server, keystone::server, keystone::keystone-api, glance::setup, glance::registry, glance::api, nova::nova-setup, nova-network::nova-controller, nova::scheduler, nova::api-ec2, nova::api-os-compute, nova::volume, nova::nova-cert, nova::vncproxy, mysql::client, mysql::ruby, horizon::server, nova-network::nova-compute, nova::compute
Platform:    ubuntu 12.04
Tags:
```

**Comment by mancdaz** [comment]
@amaltson 

What does:

knife search node 'roles:glance-setup'

show you?  Either there are multiple servers with that role, or the other thing may be that you are using an older version of one of the other cookbooks (osops-utils).  The 'get_settings_by_role' function was updated to allow exclusion of 'myself' in a search for role holders.

**Comment by amaltson** [comment]
@mancdaz I was literally typing out what the search result is before you asked for it lol:

```
$ knife search node "role:glance-setup"
0 items found
```

I'm using version 1.0.14 of osops-utils. That seems to be the latest this repo submodules to.

I've tried pulling in 1.0.15 from GitHub, still fails at the same place. Looking through the code I'm surprised it's failing because

```
if other_setup = get_settings_by_role("glance-setup", "glance", false)
  Chef::Application.fatal! "You can only have one node with the glance-setup role"
end
```

Should be fails because `get_settings_by_role("glance-setup", "glance", false)` would return false looking through the code and the query it does. `knife search node "role:glance-setup AND chef_environment:openstack"` also returns zero results.

**Comment by mancdaz** [comment]
Try the knife search with roles rather than role. That searches the expanded run list.

**Comment by amaltson** [comment]
Ahh, OK. Now I'm getting a result:

```
$ knife search node "roles:glance-setup"
1 items found

Node Name:   openstack1
Environment: openstack
... <same as above for node details>
```

**Comment by mancdaz** [comment]
@amaltson looks like this could be the way the get_settings_by_role function is detecting the node.  It assumes fqdn and Node name are the same, which in your case they are not.  I need to fix up that function, or change how we detect multiple glance-setup roles (or both), but in the meantime if you make your fqdn and nodenames be the same, it should get past this bit.

**Comment by mancdaz** [comment]
@amaltson once this https://github.com/rcbops-cookbooks/glance/pull/111 merges, your issue should be fixed.

**Comment by amaltson** [comment]
Thanks @mancdaz. I tried changing the node name and it got further. Running into an issue with the MySQL password, but I'll trying blowing away the MySQL db and having it reinstalled.

**Comment by mancdaz** [comment]
@amaltson I'm going to close this issue as the original issue is resolved.  Please open another if you need any more assistance, so that specific issues can be tracked in their own issue thread (just makes it easier for others to find if they have the same problem)

Cheers
@mancdaz

**Comment by amaltson** [comment]
Thanks for your help!
