### ISSUE TITLE
Allow Cinder to use different interface for iSCSI traffic

### ISSUE THREAD

**Issue by doublerr** [rcbops/chef-cookbooks#323]
This is a feature request for the concept used in https://github.com/rcbops-cookbooks/cinder/pull/12

We need the ability to send iSCSI traffic between cinder volume nodes to nova compute nodes over a dedicated interface. This interface may be different than the interface used for management purposes.

example
eth0 (all) - management & service/message queue communication
eth1 (compute nodes) - interface for fixed network (instance <-> communication)
eth2  (compute/cinder volume nodes) - 10G -  dedicated block storage interface

**Comment by mancdaz** [comment]
fixed in https://github.com/rcbops-cookbooks/cinder/pull/27
