### ISSUE TITLE
[DE36] HA Glance Replication not working

### ISSUE THREAD

**Issue by jcannava** [rcbops/chef-cookbooks#328]
The replicator scripts are running but failing to do anything resulting in only one server having the images.

**Comment by mattt416** [comment]
Hi Jason,

I just built two instances running ha-controller1 and ha-controller2 and was able to get the glance-replicator to work, however it did seem to take a few chef-client runs to get everything into a working state.  I'll need to dig into this further to see why that was necessary.

-Matt

**Comment by mattt416** [comment]
Hello Jason,

The following PR has been merged and helps to reduce the # of chef-client runs required on a new ha-controller1/ha-controller2 role setup for the glance replication / image sync stuff to work:

https://github.com/rcbops-cookbooks/osops-utils/pull/78

Thanks,
Matt
