### ISSUE TITLE
[DE43]: FixedIPQuotas default is set too low

### ISSUE THREAD

**Issue by breu** [rcbops/chef-cookbooks#332]
A new quota was implemented to resolve https://bugs.launchpad.net/bugs/1125468 on Fixed  IPs.  At current it is set to 10.

We need to set this to a reasonable value.  nova.conf value is

quota_fixed_ips

**Comment by retreved** [comment]
We have deployments that are being impacted by this bug.  Full details are on launchpad: 
https://bugs.launchpad.net/nova/+bug/1161190

We manually inserted a floating_ips value of 100 into the quotas table and restarted all openstack services but the API is still limiting to 10 fixed_ips.  
Internal ticket 130403-09904

Support needs a fix for this issue within our kick.

**Comment by galstrom21** [comment]
@reteved: manually setting the value to '-1' does not work?

**Comment by galstrom21** [comment]
@retreved: can you confirm this is against the floating_ip or fixed_ip quota.. you mentioned both in your previous update.

**Comment by galstrom21** [comment]
reference: nova.conf key is 'quota_fixed_ips'

**Comment by retreved** [comment]
Value -1 does not work when setting fixed_ips in quotas.  
This is against fixed_ips, not floating.  Sorry for the confusion

**Comment by galstrom21** [comment]
@reteved: can you paste the quotas table

**Comment by retreved** [comment]
mysql> select \* from quotas;
+----+---------------------+---------------------+------------+---------+----------------------------------+-----------------------------+------------+
| id | created_at          | updated_at          | deleted_at | deleted | project_id                       | resource                    | hard_limit |
+----+---------------------+---------------------+------------+---------+----------------------------------+-----------------------------+------------+
|  1 | 2013-04-09 07:47:30 | NULL                | NULL       |       0 | 344d4852777a4d68a8882acf88517b86 | metadata_items              |        128 |
|  3 | 2013-04-09 07:47:30 | NULL                | NULL       |       0 | 344d4852777a4d68a8882acf88517b86 | injected_file_content_bytes |      10240 |
|  5 | 2013-04-09 07:47:30 | NULL                | NULL       |       0 | 344d4852777a4d68a8882acf88517b86 | injected_files              |          5 |
|  7 | 2013-04-09 07:47:30 | NULL                | NULL       |       0 | 344d4852777a4d68a8882acf88517b86 | gigabytes                   |       1000 |
|  9 | 2013-04-09 07:47:30 | 2013-04-09 07:48:32 | NULL       |       0 | 344d4852777a4d68a8882acf88517b86 | ram                         |     102400 |
| 11 | 2013-04-09 07:47:30 | 2013-04-09 08:55:01 | NULL       |       0 | 344d4852777a4d68a8882acf88517b86 | floating_ips                |       1000 |
| 13 | 2013-04-09 07:47:30 | 2013-04-09 08:54:37 | NULL       |       0 | 344d4852777a4d68a8882acf88517b86 | instances                   |       1000 |
| 15 | 2013-04-09 07:47:30 | 2013-04-09 08:54:46 | NULL       |       0 | 344d4852777a4d68a8882acf88517b86 | volumes                     |       1000 |
| 17 | 2013-04-09 07:47:30 | 2013-04-09 08:54:52 | NULL       |       0 | 344d4852777a4d68a8882acf88517b86 | cores                       |       1000 |
| 19 | 2013-04-09 08:44:14 | NULL                | NULL       |       0 | 44d4852777a4d68a8882acf88517b86  | instances                   |       1000 |
| 21 | 2013-04-09 08:44:27 | NULL                | NULL       |       0 | 44d4852777a4d68a8882acf88517b86  | volumes                     |       1000 |
| 23 | 2013-04-09 08:44:38 | NULL                | NULL       |       0 | 44d4852777a4d68a8882acf88517b86  | floating_ips                |       1000 |
| 25 | 2013-04-09 08:44:45 | NULL                | NULL       |       0 | 44d4852777a4d68a8882acf88517b86  | cores                       |       1000 |
| 27 | 2013-04-09 08:44:45 | NULL                | NULL       |       0 | 344d4852777a4d68a8882acf88517b86 | fixed_ips                   |         -1 |
+----+---------------------+---------------------+------------+---------+----------------------------------+-----------------------------+------------+
14 rows in set (0.00 sec)

**Comment by galstrom21** [comment]
On a test environment:

```
# curl http://127.0.0.1:8774//v2/569ffdb56c544467858645ee1d246f1c/os-quota-sets/924b2f250dfc4702b447fb222967c79a -H 'x-auth-token: 01852c4acfd54e73a8ccd186b8d40d09' | python -m json.tool
{
    "quota_set": {
        "cores": 20,
        "fixed_ips": 10,
        "floating_ips": 10,
        "gigabytes": 1000,
        "id": "924b2f250dfc4702b447fb222967c79a",
        "injected_file_content_bytes": 10240,
        "injected_file_path_bytes": 255,
        "injected_files": 5,
        "instances": 25,
        "key_pairs": 100,
        "metadata_items": 128,
        "ram": 51200,
        "security_group_rules": 20,
        "security_groups": 50,
        "volumes": 10
    }
}
```

I inserted a fixed_ips line into quotas:

```
mysql> select * from quotas;
+----+---------------------+------------+------------+---------+----------------------------------+-----------+------------+
| id | created_at          | updated_at | deleted_at | deleted | project_id                       | resource  | hard_limit |
+----+---------------------+------------+------------+---------+----------------------------------+-----------+------------+
|  1 | 2013-04-09 19:32:53 | NULL       | NULL       |       0 | 924b2f250dfc4702b447fb222967c79a | instances |         25 |
|  5 | 2013-04-09 19:36:45 | NULL       | NULL       |       0 | 924b2f250dfc4702b447fb222967c79a | fixed_ips |        200 |
+----+---------------------+------------+------------+---------+----------------------------------+-----------+------------+
2 rows in set (0.00 sec)
```

It is now showing the new value:

```
# curl http://127.0.0.1:8774//v2/569ffdb56c544467858645ee1d246f1c/os-quota-sets/924b2f250dfc4702b447fb222967c79a -H 'x-auth-token: 01852c4acfd54e73a8ccd186b8d40d09' | python -m json.tool
{
    "quota_set": {
        "cores": 20,
        "fixed_ips": 200,
        "floating_ips": 10,
        "gigabytes": 1000,
        "id": "924b2f250dfc4702b447fb222967c79a",
        "injected_file_content_bytes": 10240,
        "injected_file_path_bytes": 255,
        "injected_files": 5,
        "instances": 25,
        "key_pairs": 100,
        "metadata_items": 128,
        "ram": 51200,
        "security_group_rules": 20,
        "security_groups": 50,
        "volumes": 10
    }
}
```

**Comment by galstrom21** [comment]
Is the new quota value showing up on your env? or is it still showing as 10?

**Comment by galstrom21** [comment]
```
# dpkg -l | grep nova
ii  nova-api-ec2                     2012.2.1+stable-20121212-a99a802e-0ubuntu1.4~cloud0 OpenStack Compute - EC2 API frontend
ii  nova-api-metadata                2012.2.1+stable-20121212-a99a802e-0ubuntu1.4~cloud0 OpenStack Compute - metadata API frontend
ii  nova-api-os-compute              2012.2.1+stable-20121212-a99a802e-0ubuntu1.4~cloud0 OpenStack Compute - OpenStack Compute API frontend
ii  nova-cert                        2012.2.1+stable-20121212-a99a802e-0ubuntu1.4~cloud0 OpenStack Compute - certificate management
ii  nova-common                      2012.2.1+stable-20121212-a99a802e-0ubuntu1.4~cloud0 OpenStack Compute - common files
ii  nova-compute                     2012.2.1+stable-20121212-a99a802e-0ubuntu1.4~cloud0 OpenStack Compute - compute node
rc  nova-compute-kvm                 2012.2.1+stable-20121212-a99a802e-0ubuntu1.4~cloud0 OpenStack Compute - compute node (KVM)
ii  nova-compute-qemu                2012.2.1+stable-20121212-a99a802e-0ubuntu1.4~cloud0 OpenStack Compute - compute node (QEmu)
ii  nova-consoleauth                 2012.2.1+stable-20121212-a99a802e-0ubuntu1.4~cloud0 OpenStack Compute - Console Authenticator
ii  nova-network                     2012.2.1+stable-20121212-a99a802e-0ubuntu1.4~cloud0 OpenStack Compute - Network manager
ii  nova-novncproxy                  2012.2.1+stable-20121212-a99a802e-0ubuntu1.4~cloud0 OpenStack Compute - NoVNC proxy
ii  nova-scheduler                   2012.2.1+stable-20121212-a99a802e-0ubuntu1.4~cloud0 OpenStack Compute - virtual machine scheduler
ii  python-nova                      2012.2.1+stable-20121212-a99a802e-0ubuntu1.4~cloud0 OpenStack Compute Python libraries
ii  python-novaclient                1:2.9.0-0ubuntu1~cloud0                             client library for OpenStack Compute API
```

**Comment by galstrom21** [comment]
also tried '-1' and it is returning as '-1' in the os-quota-sets call

**Comment by galstrom21** [comment]
You could also try manually injecting via the API:

```
# curl http://127.0.0.1:8774/v2/569ffdb56c544467858645ee1d246f1c/os-quota-sets/924b2f250dfc4702b447fb222967c79a -X PUT -H "Content-Type: application/json" -H "X-Auth-Token: 123728a6660745068b03aaa8979d028b" -d '{"quota_set": {"fixed_ips": 25, "tenant_id": "924b2f250dfc4702b447fb222967c79a"}}'
```

where '924b2f250dfc4702b447fb222967c79a' is the tenant for the quota you are wanting to set.. and '569ffdb56c544467858645ee1d246f1c' is the admin tenant UUID.

**Comment by galstrom21** [comment]
closing this issue, as it has not been updated in over a month.
