### ISSUE TITLE
[DE46] CSS not working after swift install

### ISSUE THREAD

**Issue by ringohasadd** [rcbops/chef-cookbooks#334]
After installing Swift the dashboard css under the "containers" section is not displaying properly. 

Instance type "Ubuntu 12.04.1 Precise (cloudimg)"
Swift cookbook version: 1.0.12

**Comment by mattt416** [comment]
Hi @ringohasadd,

Thanks for creating an issue for this.  I was able to replicate what you are seeing when choosing the "Rackspace" horizon theme.

I'll go ahead and close off this issue once we have a fix rolled out.

Regards,
Matt

**Comment by galstrom21** [comment]
@mattt416: can we get any more information from when you replicated the issue? Is it throwing an error, or is it just bad css?

**Comment by pmesserli** [comment]
It looks like this might be a issue with the attribute for the themes in the horizon cookbooks.  We have been running into issues with the styling on the dashboard.  It looks like one of the links its trying to pull off cloud files is broken.

default["horizon"]["theme_image_base"] = "http://ef550cb0f0ed69a100c1-40806b80b9b0290f6d33c73b927ee053.r51.cf2.rackcdn.com"

This is no longer a valid link, it may be related to this issue.  Changing the theme from Rackspace to default resolves the issue in the environment file.

**Comment by zfeldstein** [comment]
Closing issue, please re-open if this is still a problem.
