### ISSUE TITLE
[DE66]: fresh chef-client run with only ha-controller1 role assigned to the first node in the environment fails with stacktrace

### ISSUE THREAD

**Issue by breu** [rcbops/chef-cookbooks#354]
Steps to reproduce:

Set environment variable
  override_attributes: vips: swift-proxy is defined
run chef

ERROR output:

[2013-04-01T16:33:52+00:00] INFO: Configuring virtual_server for swift-proxy
# 
# Recipe Compile Error in /var/chef/cache/cookbooks/openstack-ha/recipes/default.rb
## NoMethodError

undefined method `[]' for nil:NilClass
## Cookbook Trace:

  /var/chef/cache/cookbooks/openstack-ha/recipes/default.rb:77:in `block in from_file'
  /var/chef/cache/cookbooks/openstack-ha/recipes/default.rb:32:in`each'
  /var/chef/cache/cookbooks/openstack-ha/recipes/default.rb:32:in `from_file'
## Relevant File Content:

/var/chef/cache/cookbooks/openstack-ha/recipes/default.rb:

 70:        notify_fault "#{haproxy_platform_options["service_bin"]} haproxy stop ; #{haproxy_platform_options["service_bin"]} keystone restart"
 71:      end
 72:
 73:      # now configure the virtual server
 74:      Chef::Log.info("Configuring virtual_server for #{ns}-#{svc}")
 75:
 76:      # Lookup listen_port from the environment, or fall back to the first searched node running the role
 77>>     listen_port = rcb_safe_deref(node, "#{ns}.services.#{svc}.port") ? node[ns]["services"][svc]["port"] : get_realserver_endpoints(role, ns, svc)[0]["port"]
 78:
 79:      # Generate array of host:port real servers
 80:      rs_list = get_realserver_endpoints(role, ns, svc).each.inject([]) { |output,x| output << x["host"] + ":" + x["port"].to_s }
 81:      rs_list.sort!
 82:      Chef::Log.debug "realserver list is #{rs_list}"
 83:
 84:      haproxy_virtual_server "#{ns}-#{svc}" do
 85:        lb_algo lb_algo
 86:        mode lb_mode

This is the only node configured at the moment.

RESOLUTION:

Removing [override_attributes: vips: swift-proxy] from the environment resolves the stacktrace.

**Comment by mancdaz** [comment]
fixed in referenced PR
