### ISSUE TITLE
[DE69]: rabbitmq should use tcp_listen_options instead of gratuitous restarts to clear old connections

### ISSUE THREAD

**Issue by breu** [rcbops/chef-cookbooks#355]
need to add and push upstream to the rabbitmq cookbook a flag to enable tcp_listen_options in the rabbitmq.config file

{tcp_listen_options, [binary,
                     {packet, raw},
                     {reuseaddr, true},
                     {backlog, 128},
                     {nodelay, true},
                     {exit_on_close, false},
                     {keepalive, true}]}

**Comment by mancdaz** [comment]
pull request for upstream cookbook here:

https://github.com/opscode-cookbooks/rabbitmq/pull/44

**Comment by jcannava** [comment]
opscode-cookbooks/rabbitmq#44 has been merged to the upstream cookbook in commit https://github.com/opscode-cookbooks/rabbitmq/commit/c7f34ae46a2ceba17c67876adc62e7823a85c0ca. Since our submodule references a later commit I am marking this as closed. If it is still an issue please re-open.
