### ISSUE TITLE
[DE102]: apt pinning in rabbitmq-openstack cookbook causing issues

### ISSUE THREAD

**Issue by mattt416** [rcbops/chef-cookbooks#360]
The upstream rabbitmq cookbook now defaults rabbitmq-server to 3.0.4 from https://www.rabbitmq.com/releases/rabbitmq-server/, so the apt pinning configuration dropped in by this cookbook causes rabbitmq-server to be downgraded if an apt-get is manually run.

**Comment by breu** [comment]
@mattt416 setting rabbitmq:use_distro_version in rabbitmq-openstack and removing the pinning should resolve this.

**Comment by mattt416** [comment]
Initially created https://github.com/rcbops-cookbooks/rabbitmq-openstack/pull/25, but then sent https://github.com/rcbops-cookbooks/rabbitmq-openstack/pull/26 through.  We will continue to use distro-provided packages in folsom and look to using rabbitmq.com 3.x packages in grizzly.
