### ISSUE TITLE
[DE104]: ha-controller1 role restarts cinder-api on every run due to template mismatch in cinder-setup and cinder-api

### ISSUE THREAD

**Issue by breu** [rcbops/chef-cookbooks#365]
The iscsi IP address stored in /etc/cinder/cinder.conf gets changed on every chef run from empty string to a non-empty string which forces chef-client to restart.

Additionally the cinder cookbook has 4 template declarations for /etc/cinder/cinder.conf.  We should not be cloning resources in this way.

**Comment by breu** [comment]
The cinder.conf template resources are in these recipes:
cinder-api.rb
cinder-scheduler.rb
cinder-setup.rb
cinder-volume.rb

**Comment by mancdaz** [comment]
I think we can fix this by splitting the config out into a 'cinder-config' recipe, and then including it at the point in the current recipes where we are writing out the config.
