### ISSUE TITLE
[DE107]: NOVA-API and CINDER-API are trying to connect to KEYSTONE on an invalid IP causing a 401.

### ISSUE THREAD

**Issue by JakeWarner** [rcbops/chef-cookbooks#368]
I'm 90% sure this is a bug after days of testing and tweaking configurations.

Steps to replicate:
1) Setup NovaCluster using 3 IP different ranges as similar to below:
Nova Public Network: **PUBLICIP**/27
Nova Public Network Interface: eth0
Nova VM Bridge Interface: br100
Nova Management Network: 192.168.1.0/24
Nova Cluster Name: test
VM Network Interface: eth1
VM Network: 10.0.0.0/16
Nova Internal Network: 192.168.1.0/24

2) Drag Controller/Compute into their respective containers.

3) Check "knife environment show test" to verify:
  osops_networks:
    management: 192.168.1.0/24
    nova:       192.168.1.0/24
    public:     **PUBLICIP**/27

4) Try to access OpenStack dashboard -- it should have a 401 error.

5) On controller, run: "head -n 10 /etc/keystone/keystone.conf", verify that bind_host is using the management network.
  bind_host = 192.168.1.***

6) On controller, run "tail -n 10 /etc/nova/api-paste.ini" and notice that service_host, auth_host, and auth_uri are trying to use the **PUBLICIP** 

7) Run "curl -f 'http://**PUBLICIP**:8774/v2/' " and see that it's a "401 Unauthorized" -- doing a debug on this, you find out that it's returning a 401 because it can't connect to Keystone at http://**PUBLICIP**:5000/v2.

8) There are now two ways to solve this issue:
8.1)  Modify /etc/keystone/keystone.conf and set bind_host to be 0.0.0.0 so that it listens for everything (not ideal).
8.2) Modify /etc/nova/api-paste.ini to use the internal IP.

9) Once either of the two changes were made in 8, you should now be able to see the panel and access the API. I've tried to change these variables in the chef attributes (both environment and node view) but they're always being overwritten every time a "chef client" is run.

This bug refers to the post: 
https://privatecloudforums.rackspace.com/viewtopic.php?f=4&t=379

**Comment by mattt416** [comment]
Hi @JakeWarner,

I was able to replicate the issue outlined here.  We'll update this issue w/ more information as it becomes available.

Thanks!

-Matt

**Comment by Deemetrio** [comment]
Confirm this bug. I have system installed from scratch. This bug reproduced and solution in p.8 works

**Comment by andymcc** [comment]
This was changed by @matt416 in the following commit which has merged:
https://github.com/rcbops-cookbooks/keystone/commit/c16c8f0d4c8a07404938866e9954e4fd5297fae7

Keystone should now listen on all hosts unless its in HA mode - which should resolve this issue.
