### ISSUE TITLE
[DE108]: glance points keystone service_host at auth_host IP

### ISSUE THREAD

**Issue by mattt416** [rcbops/chef-cookbooks#369]
To reproduce, configure your cluster with different VIPs for keystone-service-api and keystone-admin-api.  At that point, you'll see glance is configured to point to keystone's service_host using the auth_host IP address, which in this case causes problems.

**Comment by andymcc** [comment]
@mattt416 fixed by your update to make keystone listen on all IPs until its in ha mode with a vip!
Since it'll now be listening on all ips it shouldn't matter.
