### ISSUE TITLE
[DE109]: [mysql-openstack]: vrrp_interface is hard set to public interface

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#370]
The vrrp_interface is hard set to the 'public' interface. Ideally this should be an attribute which can be overridden as required by the deployer.

Pull request to resolve: https://github.com/rcbops-cookbooks/mysql-openstack/pull/35

**Comment by andymcc** [comment]
https://github.com/rcbops-cookbooks/mysql-openstack/pull/37 Should be fixed!
