### ISSUE TITLE
[DE110]: [openstack-ha]: vrrp_interface is hard set to public interface

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#371]
The vrrp_interface is hard set to the 'public' interface. Ideally this should be an attribute which can be overridden as required by the deployer.

Pull request to resolve the issue: https://github.com/rcbops-cookbooks/openstack-ha/pull/37

**Comment by andymcc** [comment]
https://github.com/rcbops-cookbooks/openstack-ha/pull/39 Should be fixed!
