### ISSUE TITLE
[DE111]: [rabbitmq-openstack]: vrrp_interface is hard set to public interface

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#372]
The vrrp_interface is hard set to the 'public' interface. Ideally this should be an attribute which can be overridden as required by the deployer.

Pull request to resolve this: https://github.com/rcbops-cookbooks/rabbitmq-openstack/pull/33

**Comment by andymcc** [comment]
https://github.com/rcbops-cookbooks/rabbitmq-openstack/pull/35
