### ISSUE TITLE
[DE114]: [openstack-ha]: router_id can not be 0

### ISSUE THREAD

**Issue by breu** [rcbops/chef-cookbooks#374]
deploying HA services on a VIP that ends in 0 breaks keepalived

vrrp_instance VI_10_127_54_0 {
  interface eth0
  virtual_router_id 0
  state BACKUP
  priority 100
  virtual_ipaddress {
      10.127.54.0
  }
  track_script {
    rabbitmq
  }

  notify_master "/usr/sbin/service rabbitmq-server restart; /usr/sbin/service keystone restart"
  notify_backup "/usr/sbin/service rabbitmq-server restart; /usr/sbin/service keystone restart"
  notify_fault "/usr/sbin/service rabbitmq-server restart; /usr/sbin/service keystone restart"
}

Apr 23 19:46:33 matrix-all-1-539-api2 Keepalived_vrrp: Opening file '/etc/keepalived/conf.d/vrrp_VI_10_127_54_0.conf'.
Apr 23 19:46:33 matrix-all-1-539-api2 Keepalived_vrrp: VRRP Error : VRID not valid !
Apr 23 19:46:33 matrix-all-1-539-api2 Keepalived_vrrp:              must be between 1 & 255. reconfigure !
Apr 23 19:46:33 matrix-all-1-539-api2 Keepalived_vrrp: Opening file '/etc/keepalived/conf.d/vrrp_VI_10_127_54_31.conf'.
Apr 23 19:46:33 matrix-all-1-539-api2 Keepalived_vrrp: VRRP_Instance(VI_10_127_54_0) the virtual id must be set!

**Comment by breu** [comment]
despite what the man pages for keepalived say, http://www.ietf.org/rfc/rfc2338.txt says it best.

VRID Virtual Router Identifier.  Configured item in the range 1-255 (decimal).  There is no default.

**Comment by andymcc** [comment]
https://github.com/rcbops-cookbooks/openstack-ha/pull/38

Since there are 255 possible options for the VRID and 256 possible last octets (not to mention IPs with the same last octet) there isn't a way to use the last octet and still work reliably! As a way around this added in the ability to set the value.
