### ISSUE TITLE
[DE115]: mysql::server recipe does not run on subsequent chef-client runs after deploying a controller

### ISSUE THREAD

**Issue by vinsonr** [rcbops/chef-cookbooks#375]
mysql::server recipe does not run on subsequent chef-client runs after deploying a controller. This is because if a node has node["mysql"]["myid"] set then the block of code including mysql::server is not executed. This results in mysql tuning parameters set after deployment not being applied. It also results in a failure to manage the mysql packages and config files properly.

File: mysql-openstack/recipes/server.rb
Line: 62

**Comment by mancdaz** [comment]
Hi @vinsonr 

This has now been fixed in rcbops-cookbooks/mysql-openstack/pull/30
