### ISSUE TITLE
[DE119]: openstack-ha prohibits multiple openstack-clusters in the same broadcast domain

### ISSUE THREAD

**Issue by breu** [rcbops/chef-cookbooks#379]
pr 29 19:09:09 matrix-all-1-571-api2 Keepalived_vrrp: VRRP_Instance(VI_10_127_54_19) ignoring received advertisment...
Apr 29 19:09:09 matrix-all-1-571-api2 Keepalived_vrrp: ip address associated with VRID not present in received packet : 10.127.54.13
Apr 29 19:09:09 matrix-all-1-571-api2 Keepalived_vrrp: one or more VIP associated with VRID mismatch actual MASTER advert
Apr 29 19:09:09 matrix-all-1-571-api2 Keepalived_vrrp: bogus VRRP packet received on eth0 !!!
Apr 29 19:09:09 matrix-all-1-571-api2 Keepalived_vrrp: VRRP_Instance(VI_10_127_54_13) ignoring received advertisment...
Apr 29 19:09:10 matrix-all-1-571-api2 Keepalived_vrrp: ip address associated with VRID not present in received packet : 10.127.54.19
Apr 29 19:09:10 matrix-all-1-571-api2 Keepalived_vrrp: one or more VIP associated with VRID mismatch actual MASTER advert
Apr 29 19:09:10 matrix-all-1-571-api2 Keepalived_vrrp: bogus VRRP packet received on eth0 !!!
Apr 29 19:09:10 matrix-all-1-571-api2 Keepalived_vrrp: VRRP_Instance(VI_10_127_54_19) ignoring received advertisment...
Apr 29 19:09:10 matrix-all-1-571-api2 Keepalived_vrrp: ip address associated with VRID not present in received packet : 10.127.54.13
Apr 29 19:09:10 matrix-all-1-571-api2 Keepalived_vrrp: one or more VIP associated with VRID mismatch actual MASTER advert
Apr 29 19:09:10 matrix-all-1-571-api2 Keepalived_vrrp: bogus VRRP packet received on eth0 !!!
Apr 29 19:09:10 matrix-all-1-571-api2 Keepalived_vrrp: VRRP_Instance(VI_10_127_54_13) ignoring received advertisment...
Apr 29 19:09:11 matrix-all-1-571-api2 Keepalived_vrrp: ip address associated with VRID not present in received packet : 10.127.54.19
Apr 29 19:09:11 matrix-all-1-571-api2 Keepalived_vrrp: one or more VIP associated with VRID mismatch actual MASTER advert

This commit broke this: rcbops-cookbooks/openstack-ha/commit/253ec347d9a59c3f5fe8ddafd2c128ff25097038

**Comment by mancdaz** [comment]
commits that broke this have been reverted:

https://github.com/rcbops-cookbooks/openstack-ha/commit/f0437e4657fb325e7ffdf90deed6eac1db88d6a8
https://github.com/rcbops-cookbooks/rabbitmq-openstack/commit/5e8fd87a70154cfcf103c3ba2a48965dff6a70b8
https://github.com/rcbops-cookbooks/mysql-openstack/commit/577c78353dd3094240c2cb073bcaaafafabe2e04
