### ISSUE TITLE
[DE120]: nova/api-os-compute uses the keystone VIP before openstack-ha is laid down

### ISSUE THREAD

**Issue by breu** [rcbops/chef-cookbooks#380]
00:43:53.583 [2013-04-29T21:17:27+00:00] INFO: Processing keystone_tenant[Register Service Tenant] action create (nova::api-os-compute line 76)
00:43:53.583 [0m
00:43:53.583 ================================================================================[0m
00:43:53.583 [31mError executing action `create` on resource 'keystone_tenant[Register Service Tenant]'[0m
00:43:53.583 ================================================================================[0m
00:43:53.583 
00:43:53.583 [0m
00:43:53.583 Errno::EHOSTUNREACH[0m
00:43:53.583 -------------------[0m
00:43:53.583 No route to host - connect(2)[0m
00:43:53.583 
00:43:53.583 [0m
00:43:53.583 Cookbook Trace:[0m
00:43:53.583 ---------------[0m
00:43:53.583 /var/cache/chef/cookbooks/keystone/providers/tenant.rb:106:in `_find_value'
00:43:53.583 /var/cache/chef/cookbooks/keystone/providers/tenant.rb:49:in`block in class_from_file'[0m
00:43:53.583 
00:43:53.583 [0m
00:43:53.583 Resource Declaration:[0m
00:43:53.583 ---------------------[0m
00:43:53.583 # In /var/cache/chef/cookbooks/nova/recipes/api-os-compute.rb
00:43:53.583 
00:43:53.583  76: keystone_tenant "Register Service Tenant" do
00:43:53.583  77:   auth_host ks_admin_endpoint["host"]
00:43:53.583  78:   auth_port ks_admin_endpoint["port"]
00:43:53.583  79:   auth_protocol ks_admin_endpoint["scheme"]
00:43:53.583  80:   api_ver ks_admin_endpoint["path"]
00:43:53.583  81:   auth_token keystone["admin_token"]
00:43:53.583  82:   tenant_name node["nova"]["service_tenant_name"]
00:43:53.583  83:   tenant_description "Service Tenant"
00:43:53.583  84:   tenant_enabled "1" # Not required as this is the default
00:43:53.583  85:   action :create
00:43:53.583  86: end
00:43:53.583  87: 
00:43:53.583 [0m
00:43:53.583 
00:43:53.583 [0m
00:43:53.583 Compiled Resource:[0m
00:43:53.583 ------------------[0m
00:43:53.583 # Declared in /var/cache/chef/cookbooks/nova/recipes/api-os-compute.rb:76:in `from_file'
00:43:53.583 
00:43:53.583 keystone_tenant("Register Service Tenant") do
00:43:53.583   action [:create]
00:43:53.583   retries 0
00:43:53.583   retry_delay 2
00:43:53.583   cookbook_name "nova"
00:43:53.583   recipe_name "api-os-compute"
00:43:53.583   auth_host "10.127.54.36"
00:43:53.583   auth_port "35357"
00:43:53.583   auth_protocol "http"
00:43:53.583   api_ver "/v2.0"
00:43:53.583   auth_token "eXzpQ_XkF_sa_QsMvzQy"
00:43:53.583   tenant_name "service"
00:43:53.583   tenant_description "Service Tenant"
00:43:53.583   tenant_enabled "1"
00:43:53.583 end
00:43:53.583 [0m
00:43:53.583 
00:43:53.583 [0m

**Comment by mancdaz** [comment]
Fixed in https://github.com/rcbops/jenkins-chef-nova-dingus/commit/c49dfe827f5447172b6b5a21eae0a6cce3d7e773
