### ISSUE TITLE
[DE123]: Horizon Apache config listening on wrong IP

### ISSUE THREAD

**Issue by tomellis** [rcbops/chef-cookbooks#383]
Caveat: I'm deploying RPC into Rackspace Open Cloud for demos of Opencenter and the automation around it, I think this issue would have been noticed already if it occurred on bare metal.

When deploying onto Open Cloud, after Opencenter configures the controller, Apache's /etc/apache2/ports.conf and /etc/apache2/sites-available/openstack-dashboard config files explicitly listen on the SeviceNet private network IP (which resides on eth1) instead of the PublicNet (eth0) IP address. This means that the Horizon interface is not accessible.

From what I can see (bare with me I'm a chef n00b)... the listen_on address used in the templates is getting the address from the get_bind_endpoint function (cookbooks/osops-utils/libraries/ip_location.rb).
1. Why do we explicitly listen on an address? I've seen that the opscode horizon cookbook listens on all addresses
2. It's odd that the get_bind_endpoint function returns the ServiceNet address, perhaps an underlying issue?

Cheers.

**Comment by andymcc** [comment]
Hey Tom, 
Typically you wouldn't aim to set this up on the cloud, but it is a decent test case. The "main" issue is that on the public cloud test installation your instances are assigned random public facing IP addresses so you can't really specify a public range reliably - but if you could it would work as expected. I'd already been looking at changing this for that purpose, as it won't really impact any other solutions, so apache should listen on all IPs once the change is made.

There is one thing worth noting, once a VIP is specified for HA this will cause it to stop listening on ALL IP's again and begin listening on only the VIP IP.

I'll keep you posted once thats adjusted.

**Comment by galstrom21** [comment]
@tomellis: the get_bind_endpoint function figures out which ip to use via the "osops_networks" declaration in the environment.

**Comment by andymcc** [comment]
Fixed https://github.com/rcbops-cookbooks/horizon/pull/94

**Comment by tomellis** [comment]
OK thanks all, that works for me.
