### ISSUE TITLE
[DE124]: Need /etc/nova/policy.json added to nova cookbook

### ISSUE THREAD

**Issue by rpawlik** [rcbops/chef-cookbooks#389]
We have customers that occasionally need changes to this file. Can we please add this to the nova cookbook? Let me know if there's anything I can help with.

**Comment by galstrom21** [comment]
@rpawlik: Can you provide a few use cases.. any examples of what generally gets modified?

**Comment by rpawlik** [comment]
The most recent example is changing:

"compute_extension:hypervisors": [["rule:admin_or_owner"]],

To:

"compute_extension:hypervisors": [],

In other words, the customer wanted to use nova to list hosts with an unprivileged user.

**Comment by rpawlik** [comment]
I can look through the policy file and maybe come up with several that we think customer might want to change. I know at least one other customer has requested a change, but it was a while back (I didn't actually work the ticket, just overheard) so I can't remember what exactly they needed changed.

**Comment by git-harry** [comment]
https://github.com/rcbops-cookbooks/nova/pull/269

This has been added.
