### ISSUE TITLE
[DE128]: [nova-network]: nova-network/providers/networks.rb does not cater for nova.network.manager.VlanManager

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#392]
nova-network/providers/networks.rb does not run a "nova-manage network create" command that includes the vlan option, which results in errors like this:

May 10 18:00:50 localhost (nova): 2013-05-10 18:00:50,920 CRITICAL 'vlan_start'
Traceback (most recent call last):
  File "/usr/bin/nova-manage", line 1404, in <module>
    main()
  File "/usr/bin/nova-manage", line 1391, in main
    fn(_fn_args, *_fn_kwargs)
  File "/usr/bin/nova-manage", line 480, in create
    net_manager.create_networks(context.get_admin_context(), **kwargs)
  File "/usr/lib/python2.7/dist-packages/nova/network/manager.py", line 2112, in create_networks
    if kwargs['num_networks'] + kwargs['vlan_start'] > 4094:
KeyError: 'vlan_start'

Essentially due to the missing vlan option, the calculation of whether the number of networks + starting vlan is more than the possible number of vlans fails.

**Comment by andymcc** [comment]
I basically have this fixed, I need to rebase and PR - but it affects multiple repo's so we'll have to do some magic.

**Comment by andymcc** [comment]
https://github.com/rcbops-cookbooks/nova-network/pull/59 try that out! It should work fine, you will need to specify the appropriate network manager, and also NB the way to define networks has changed slightly.

"networks": {
    "public": {
        "label": "public",
        "bridge_dev": "eth2",
        "dns2": "8.8.8.8",
        "ipv4_cidr": "192.168.100.0/24",
        "bridge": "br100",
        "vlan_id": 112,
        "dns1": "8.8.4.4"
       },
       "private": {
          "label": "private",
          "ipv4_cidr": "192.168.200.0/24",
          "bridge": "br200",
          "bridge_dev": "eth1",
          "vlan_id": 113
        }
     }

Let me know if you run into any issues!
