### ISSUE TITLE
[DE130]: [nova]: vncproxy does not implement ha properly

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#394]
The vncproxy recipe, which is referenced in both default ha roles (ha-controller1, ha-controller2), does not implement ha properly as it does not implement the required memcached or put the memcached option into nova.conf

See this thread for more details: http://lists.openstack.org/pipermail/openstack-operators/2013-May/002949.html

**Comment by mattt416** [comment]
Hi @odyssey4me,

I have verified that this is an issue.  I'm working on some stuff in grizzly branch right now to handle deployment / configuration of memcached for nova -- it's not up yet as the change is a little larger in that we also have to rework the swift cookbook with respect to memcached installation.

I should have some stuff gated by early next week.  If everything looks good, we can backport to folsom also.

Thanks!

-Matt

**Comment by odyssey4me** [comment]
Sounds excellent! Keep me posted. :+1:

**Comment by mattt416** [comment]
Hi @odyssey4me,

The following PRs have been merged:

https://github.com/rcbops-cookbooks/nova/pull/283
https://github.com/rcbops/chef-cookbooks/pull/441
https://github.com/rcbops-cookbooks/swift/pull/97

I'm just waiting for the following to go through:

https://github.com/rcbops/chef-cookbooks/pull/442

That should more or less clear up this issue.  

Give us a shout if you see any further problems.

Thanks!

-Matt
