### ISSUE TITLE
[DE131]: [osops-utils] get_access_endpoint should provide facility to return DNS entries for endpoints

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#395]
It would be ideal if the function get_access_endpoint could provide a facility to return DNS entries for endpoints. This would allow the registration of the endpoints to be DNS entries instead of internal IP Addresses.

This would be optional, of course, based on whether appropriate attributes have been populated in the Chef environment.

As an optional extra enhancement, the osops-utils/autoetchosts recipe could then ensure that all internal hosts have the endpoint names with the internal server ip addresses put into the /etc/hosts file.

**Comment by odyssey4me** [comment]
I see that this may be possible already, but might have a bug as recorded in https://github.com/rcbops/chef-cookbooks/issues/470

**Comment by mancdaz** [comment]
Both 'host' and 'uri' can be passed as an attribute for a service, and these values will override and potential search results.

If 'host' is passed, the IP address will not be looked up for the relevant network, and the endpoint uri will be constructed from the scheme, port, path from the attributes, and the passed in host.

If 'uri' is passed, the entire value is used as the endpoint uri and no search results or other attributes will override this.
