### ISSUE TITLE
[DE133]: [horizon] CSS style sheets not rendering dash properly

### ISSUE THREAD

**Issue by pmesserli** [rcbops/chef-cookbooks#398]
After doing a new Girzzly deploy, it appears that some of the CSS is not rendering on the dashboard properly.  Upon logging in, the top portion of the dashboard is greyed out.  A number of the files for the CSS style sheets are owned by root instead of www-data, however after modifying these permissions it did not appear to resolve the styling.

**Comment by galstrom21** [comment]
This is due to: https://github.com/rcbops-cookbooks/horizon/blob/grizzly/recipes/server.rb#L262
