### ISSUE TITLE
Horizon Grizzly RHEL6.4 CSS not rendering 

### ISSUE THREAD

**Issue by jonjozwiak** [rcbops/chef-cookbooks#403]
When running the horizon cookbook on a RHEL 6.4 server the dashboard web site shows up without any CSS formatting.  I did some testing and learned that this is due to compression.  If you modify /etc/openstack-dashboard/local_settings and enable compression then the CSS renders without problems.  As you see below it looks like this was previously disabled.   

# oh noes... disabled compressed CSS on EPEL based systems until node
# tools are packaged properly...
COMPRESS_ENABLED = False

In the template local_settings.py.erb this is hardcoded.  Could this be modified to allow passing as an attribute so it can be True for newer Red Hat systems?

**Comment by jonjozwiak** [comment]
One thing to add to this.  I found that I was still having some inconsistency (worked in IE but not in Chrome... IE sometimes had problems rendering the login page).  I ended up also add the following line to the /etc/httpd/conf.d/openstack-dashboard: 
   Alias /static /usr/share/openstack-dashboard/static

I'm not sure if this should replace the Alias /media or not, but just adding it worked for me.

**Comment by git-harry** [comment]
@jonjozwiak COMPRESS_ENABLED did not appear to fix anything with my tests. I have made some changes and the dashboard appears to be displaying correctly for me now. I will close this but if you are still seeing problems please update the issue with further information.
