### ISSUE TITLE
[DE145]: Enhancement: Reverse proxy novnc to improve accessibility

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#411]
NoVNC is traditionally made available on port 6080 is many standard configurations. This is presented through a very basic web server (which isn't very robust or secure) and many corporate firewalls don't traditionally have port 6080 accessible.

It'd be far better if it could be made available via port 80 or 443, reverse proxied behind a more robust web server. This would improve its security and accessibility.

Unfortunately Apache2 doesn't allow the reverse proxying of websockets.
http://serverfault.com/questions/290121/configuring-apache2-to-proxy-websocket

That said, someone seems to have written some stuff that could be implemented - perhaps with some modification:
https://github.com/kanaka/websockify/issues/19

nginx could also be used instead of Apache:
https://github.com/kanaka/noVNC/issues/181

**Comment by mancdaz** [comment]
@odyssey4me 

Thanks for the feedback.  We will add this to our product backlog and work on it as appropriate.

**Comment by ram4git** [comment]
why is this closed?

**Comment by odyssey4me** [comment]
I can verify that niginx works. It even enables the use of alternative listening ports for NoVNC. ie the back-end port can still be 6080 while the front-end port can be 80. I have yet to test whether SSL can be off-loaded to the reverse proxy and everything can still work successfully.

Example config:

```
upstream vnc_proxy { server 10.1.0.5:6080; }
server {
  listen 88;
  servername myvncserver;
  location / {
    proxy_pass http://10.1.0.5:6080;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
```

Apache 2.4 now includes mod_proxy_wstunnel: http://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html
I'm busy doing a backport for Precise and will test whether it works and provides the same level of functionality.

**Comment by odyssey4me** [comment]
Using apache2 from [my backport ppa](https://launchpad.net/~jesse-pretorius/+archive/backports), I can confirm that it works. It also enables the use of alternative listening ports for NoVNC.

Example config:

```
root@proxy2:/etc/apache2# a2enmod proxy
root@proxy2:/etc/apache2# a2enmod proxy_http
root@proxy2:/etc/apache2# a2enmod proxy_wstunnel
root@proxy2:/etc/apache2# cat sites-available/novnc.conf
Listen 88

<VirtualHost *:88>
  <Proxy *>
    Require all granted
  </Proxy>

  ProxyRequests Off
  ProxyPass /vnc_auto.html http://10.1.0.5:6080/vnc_auto.html
  ProxyPassReverse /vnc_auto.html http://10.1.0.5:6080/vnc_auto.html
  ProxyPass /favicon.ico http://10.1.0.5:6080/favicon.ico
  ProxyPassReverse /favicon.ico http://10.1.0.5:6080/favicon.ico
  ProxyPass /include/ http://10.1.0.5:6080/include/
  ProxyPassReverse /include/ http://10.1.0.5:6080/include/
  ProxyPass / ws://10.1.0.5:6080/
  ProxyPassReverse / ws://10.1.0.5:6080/

  ErrorLog ${APACHE_LOG_DIR}/error_log-novnc
  CustomLog ${APACHE_LOG_DIR}/access_log-novnc common
  LogLevel debug

</VirtualHost>
```

**Comment by gbenguria** [comment]
@odyssey4me 

Thanks a lot, you save my day (actually my night) ;-)
