### ISSUE TITLE
[DE153]: Add NOVA_ENDPOINT_TYPE to ~/openrc

### ISSUE THREAD

**Issue by retreved** [rcbops/chef-cookbooks#424]
When a different publicURL is specified from internalURL, local nova CLI commands fail as nova client defaults to the publicURL and that address is not routable.  ~/openrc should have a default line that forces internalURL to be used.

export NOVA_ENDPOINT_TYPE=internalURL

**Comment by jcannava** [comment]
This has been corrected in https://github.com/rcbops-cookbooks/nova/pull/280. However, there is a slight implementation difference than using NOVA_ENDPOINT_TYPE. We are now passing the internal-api endpoint to the openrc instead of public, this also avoids having to add another bash env variable.
