### ISSUE TITLE
[DE155]: Add publicURL to chef environment

### ISSUE THREAD

**Issue by retreved** [rcbops/chef-cookbooks#425]
The chef environment settings should allow for specifying a publicURL that is different from the internalURL.  This would return internal and public URLS in the service catalog and allow access from a publicly accessible address to the OpenStack environment.

**Comment by jcannava** [comment]
This has been adjusted in https://github.com/rcbops-cookbooks/keystone/pull/113. We now set the publicURL to the public network (in environment) and the internalURL to the internal network (in environment). The admin api remains on the nova network (in environment).
