### ISSUE TITLE
[DE157]: Network size over 255 causes issues

### ISSUE THREAD

**Issue by rpawlik** [rcbops/chef-cookbooks#427]
If using nova-network, you're not able to add a network that's over a /24. If you use a /23, it creates a /24 then bombs out on the next chef-client run. The fixed_size attribute needs to be added back in. Please see this commit:

https://github.com/rcbops-cookbooks/nova-network/commit/bd1b1e97724d7708f02de44ab9007aa939a389aa

**Comment by rpawlik** [comment]
Any update on this?

**Comment by jcannava** [comment]
Working through fix here:
https://github.com/rcbops-cookbooks/nova-network/pull/23

**Comment by breu** [comment]
The fix has been merged.
