### ISSUE TITLE
[DE172]: Keystone LDAP add-user role issue

### ISSUE THREAD

**Issue by john5223** [rcbops/chef-cookbooks#433]
member_role_id needs to be set in the keystone.conf for adding users to work
# member_role_id = 9fe2ff9ee4384b1894a90878d3e92bab

Currently commented out.

**Comment by jcannava** [comment]
Can you clone this repo: https://github.com/jcannava/keystone/tree/DEMEMBERID, upload it as the keystone cookbook, and see if it corrects the issue?
