### ISSUE TITLE
[DE173]: Keystone LDAP:  add-user with an email fails

### ISSUE THREAD

**Issue by john5223** [rcbops/chef-cookbooks#434]
root@qa-precise-pool716:/etc/keystone# keystone user-create --name demo2 --tenant-id e7046748d64449a791ff3cc2667f713d --pass demo2 --email a@a.com

Unable to communicate with identity service: {"error": {"message": "An unexpected error prevented the server from fulfilling your request. {'info': \"attribute 'email' not allowed\", 'desc': 'Object class violation'}", "code": 500, "title": "Internal Server Error"}}. (HTTP 500)

**Comment by jcannava** [comment]
Can you try setting keystone["ldap"]["user_mail_attribute"] to mail and see if it works?

**Comment by john5223** [comment]
This works!
