### ISSUE TITLE
[DE181]: Keystone pki_setup is running as keystone user and doesnt have permissions on keystone.log

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#446]
[2013-06-14T10:29:07-06:00] INFO: Processing execute[keystone-manage pki_setup] action run (keystone::keystone-common line 50)
[0m
================================================================================[0m
[31mError executing action `run` on resource 'execute[keystone-manage pki_setup]'[0m
================================================================================[0m

[0m
Mixlib::ShellOut::ShellCommandFailed[0m
------------------------------------[0m
Expected process to exit with [0], but received '1'
---- Begin output of keystone-manage pki_setup ----
STDOUT: 
STDERR: Traceback (most recent call last):
  File "/usr/bin/keystone-manage", line 28, in <module>
    cli.main(argv=sys.argv, config_files=config_files)
  File "/usr/lib/python2.6/site-packages/keystone/cli.py", line 174, in main
    config.setup_logging(CONF)
  File "/usr/lib/python2.6/site-packages/keystone/common/config.py", line 119, in setup_logging
    handler = logging.WatchedFileHandler(logfile)
  File "/usr/lib64/python2.6/logging/handlers.py", line 377, in **init**
    logging.FileHandler.**init**(self, filename, mode, encoding, delay)
  File "/usr/lib64/python2.6/logging/**init**.py", line 827, in **init**
    StreamHandler.**init**(self, self._open())
  File "/usr/lib64/python2.6/logging/__init__.py", line 846, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/var/log/keystone/keystone.log'
---- End output of keystone-manage pki_setup ----
Ran keystone-manage pki_setup returned 1[0m

[0m
Resource Declaration:[0m
---------------------[0m
# In /var/chef/cache/cookbooks/keystone/recipes/keystone-common.rb

 50: execute "keystone-manage pki_setup" do
 51:   user "keystone"
 52:   group "keystone"
 53:   command "keystone-manage pki_setup"
 54:   action :nothing
 55: end
 56: 
[0m

[0m
Compiled Resource:[0m
------------------[0m
# Declared in /var/chef/cache/cookbooks/keystone/recipes/keystone-common.rb:50:in `from_file'

execute("keystone-manage pki_setup") do
  action [:nothing]
  retries 0
  retry_delay 2
  command "keystone-manage pki_setup"
  backup 5
  group "keystone"
  returns 0
  user "keystone"
  cookbook_name "keystone"
  recipe_name "keystone-common"
end
[0m

[0m

**Comment by breu** [comment]
https://github.com/rcbops-cookbooks/nova/pull/287
https://github.com/rcbops-cookbooks/keystone/pull/114

**Comment by breu** [comment]
all changes merged
