### ISSUE TITLE
[DE184]: [nova-network] quantum rpc notifiers out of date

### ISSUE THREAD

**Issue by mancdaz** [rcbops/chef-cookbooks#448]
list notifier dropped:
https://github.com/openstack/quantum/commit/8789704221d23b4a713727cad79939f69d2ab02a

rabbit_notifier deprecated:
https://github.com/openstack/quantum/blob/master/quantum/openstack/common/notifier/rabbit_notifier.py

**Comment by jcannava** [comment]
Fixed in https://github.com/rcbops-cookbooks/nova-network/pull/32
