### ISSUE TITLE
[DE185]: Quantum tries to create same bridge on second chef run (single-network-node)

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#449]
http://build.monkeypuppetlabs.com:8080/view/QE%20Jobs/job/build-openstack-cluster-with-remote-chef/250/console

[2013-06-17T09:48:40-05:00] INFO: Processing execute[create provider bridges] action run (nova-network::quantum-ovs-plugin line 87)
[0m
================================================================================[0m
[31mError executing action `run` on resource 'execute[create provider bridges]'[0m
================================================================================[0m

[0m
Mixlib::ShellOut::ShellCommandFailed[0m
------------------------------------[0m
Expected process to exit with [0], but received '1'
---- Begin output of ovs-vsctl add-br br-eth1 ----
STDOUT: 
STDERR: ovs-vsctl: cannot create a bridge named br-eth1 because a bridge named br-eth1 already exists
---- End output of ovs-vsctl add-br br-eth1 ----
Ran ovs-vsctl add-br br-eth1 returned 1[0m

[0m
Resource Declaration:[0m
---------------------[0m
# In /var/chef/cache/cookbooks/nova-network/recipes/quantum-ovs-plugin.rb

 87: execute "create provider bridges" do
 88:     node["quantum"]["ovs"]["provider_networks"].each do |k,v|
 89:         command "ovs-vsctl add-br #{v['bridge']}"
 90:         action :run
 91:     end
 92:     not_if { node["quantum"]["ovs"]["provider_networks"].empty? }
 93: end
[0m

[0m
Compiled Resource:[0m
------------------[0m
# Declared in /var/chef/cache/cookbooks/nova-network/recipes/quantum-ovs-plugin.rb:87:in `from_file'

execute("create provider bridges") do
  action [:run]
  retries 0
  retry_delay 2
  command "ovs-vsctl add-br br-eth1"
  backup 5
  returns 0
  cookbook_name "nova-network"
  recipe_name "quantum-ovs-plugin"
  not_if { #code block }
end
[0m

[0m
[2013-06-17T09:48:40-05:00] INFO: Running queued delayed notifications before re-raising exception

**Comment by jcannava** [comment]
https://github.com/rcbops-cookbooks/nova-network/pull/33

**Comment by jcannava** [comment]
and https://github.com/rcbops-cookbooks/nova-network/pull/34
