### ISSUE TITLE
[DE186]: [osops-utils] check_package_version blows up node['nova'] does not exist

### ISSUE THREAD

**Issue by rpedde** [rcbops/chef-cookbooks#450]
this may be the case if (for example) installing just keystone.
## NoMethodError

undefined method `[]' for nil:NilClass
## Cookbook Trace:

/var/chef/cache/cookbooks/osops-utils/libraries/patch.rb:24:in `check_package_version'
/var/chef/cache/cookbooks/keystone/recipes/keystoneclient-patch.rb:30:in`block (2 levels) in from_file'

**Comment by claco** [comment]
Fixed in osops-utils/grizzly
