### ISSUE TITLE
[DE187]: VIPs for private services come up on public interface

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/chef-cookbooks#451]
Maybe I'm "doing it wrong", but whenever I try to bring up an HA pair using a separate public  network, the two VIPs for MySQL and RabbitMQ are brought up on the public interface instead of the private interface.

eth0 - nova / management network
eth1 - vm network
eth2 - public network

Relevant bits from environment:

```
"vips": {
  "cinder-api": "172.16.0.50",
  "glance-api": "172.16.0.50",
  "glance-registry": "172.16.0.50",
  "horizon-dash": "172.16.0.50",
  "horizon-dash_ssl": "172.16.0.50",
  "keystone-admin-api": "172.16.0.50",
  "keystone-internal-api": "172.16.0.50",
  "keystone-service-api": "172.16.0.50",
  "nova-api": "172.16.0.50",
  "nova-ec2-public": "172.16.0.50",
  "nova-novnc-proxy": "172.16.0.50",
  "nova-xvpvnc-proxy": "172.16.0.50",
  "mysql-db": "192.168.2.51",
  "rabbitmq-queue": "192.168.2.52"
}

"osops_networks": {
  "nova": "192.168.2.0/24",
  "management": "192.168.2.0/24",
  "public": "172.16.0.0/24"
}
```

Controller01 Network Configuration

```
root@controller01:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:36:b3:30 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.1/24 brd 192.168.2.255 scope global eth0
    inet6 fe80::a00:27ff:fe36:b330/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:8a:98:fd brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe8a:98fd/64 scope link 
       valid_lft forever preferred_lft forever
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:a5:d4:7c brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/24 brd 172.16.0.255 scope global eth2
    inet 172.16.0.50/32 scope global eth2
    inet 192.168.2.51/32 scope global eth2
    inet 192.168.2.52/32 scope global eth2
    inet6 fe80::a00:27ff:fea5:d47c/64 scope link 
       valid_lft forever preferred_lft forever
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:d1:0b:d9 brd ff:ff:ff:ff:ff:ff
    inet 10.0.5.15/24 brd 10.0.5.255 scope global eth3
    inet6 fe80::a00:27ff:fed1:bd9/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by mancdaz** [comment]
I am able to reproduce this.  Looks like it's a keepalived scoping problem.

**Comment by mancdaz** [comment]
Issue is here:

https://github.com/rcbops-cookbooks/mysql-openstack/blob/grizzly/attributes/default.rb#L4

and here:

https://github.com/rcbops-cookbooks/rabbitmq-openstack/blob/grizzly/attributes/default.rb#L4

fix coming...

**Comment by mancdaz** [comment]
With the above patches, I now see the following (as it should be):

Environment:

<pre>
    "vips": {
      "mysql-db": "172.16.0.10",
      "rabbitmq-queue": "172.16.0.20",
      "glance-registry": "192.168.3.245",
      "keystone-service-api": "192.168.3.245",
      "nova-novnc-proxy": "192.168.3.245",
      "nova-xvpvnc-proxy": "192.168.3.245",
      "nova-api": "192.168.3.245",
      "keystone-admin-api": "192.168.3.245",
      "glance-api": "192.168.3.245",
      "nova-ec2-public": "192.168.3.245",
      "cinder-api": "192.168.3.245",
      "horizon-dash": "192.168.3.245",
      "swift-proxy": "192.168.3.210",
      "horizon-dash_ssl": "192.168.3.245"
    }
   "osops_networks": {
      "nova": "172.16.0.0/24",
      "public": "192.168.3.0/24",
      "management": "172.16.0.0/24",
    },
</pre>

controller:

<pre>
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether bc:76:4e:08:60:ae brd ff:ff:ff:ff:ff:ff
    inet 5.79.24.33/24 brd 5.79.24.255 scope global eth0
    inet6 2a00:1a48:7803:107:94f4:6b56:ff08:60ae/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::be76:4eff:fe08:60ae/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether bc:76:4e:08:55:14 brd ff:ff:ff:ff:ff:ff
    inet 10.177.201.29/18 brd 10.177.255.255 scope global eth1
    inet6 fe80::be76:4eff:fe08:5514/64 scope link
       valid_lft forever preferred_lft forever
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether bc:76:4e:08:04:4c brd ff:ff:ff:ff:ff:ff
    inet 192.168.3.44/24 brd 192.168.3.255 scope global eth2
    <a style="color:#F10F0F"><b>inet 192.168.3.245/32 scope global eth2</b></a>
    inet6 fe80::be76:4eff:fe08:44c/64 scope link
       valid_lft forever preferred_lft forever
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether bc:76:4e:08:1d:bd brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/24 brd 172.16.0.255 scope global eth3
    <a style="color:#F10F0F"><b>inet 172.16.0.10/32 scope global eth3</b>
    <b>inet 172.16.0.20/32 scope global eth3</b></a>
    inet6 fe80::be76:4eff:fe08:1dbd/64 scope link
       valid_lft forever preferred_lft forever
</pre>
