### ISSUE TITLE
[DE188]: ovs_quantum_plugin.ini is missing config network_vlan_ranges 

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#453]
When building a controller, single-network-node, single-compute cluster, you cannot add quantum networks without adding the following to /etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini on the controller node

[OVS]
network_vlan_ranges = ph-eth1:1:1000

**Comment by jcannava** [comment]
https://github.com/rcbops-cookbooks/nova-network/pull/35
