### ISSUE TITLE
[DE189]: single-network-node role doesnt get openrc

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#454]
When building a node with the role single-network-node, openrc environment file doesnt get laid down in /root, this isnt a breaking bug but it would be nice to have it defaulted there

root@qa-precise-pool987:~# ls -al /root
total 24
drwx------  3 root root 4096 Jun 18 16:10 .
drwxr-xr-x 23 root root 4096 Jun 18 12:33 ..
-rw-------  1 root root 2895 Jun 18 15:05 .bash_history
-rw-r--r--  1 root root 3106 Apr 19  2012 .bashrc
drwx------  2 root root 4096 Jun 18 10:34 .cache
-rw-r--r--  1 root root  140 Apr 19  2012 .profile

**Comment by pedrojimenez** [comment]
The **single-network-node** role is not found at the moment in the repo.

**Comment by mancdaz** [comment]
@pedrojimenez 

Please ensure you have checked out the grizzly branch and have uploaded all the roles to your chef-server:

https://github.com/rcbops/chef-cookbooks/blob/grizzly/roles/single-network-node.rb

**Comment by pedrojimenez** [comment]
@mancdaz you were right ... :S

I am very ashamed !!!

**Comment by mancdaz** [comment]
@jacobwagner currently the openrc file is laid down by the nova::nova-common recipe.  I think it would be appropriate to move this functionality to a separate recipe in our utility cookbook, osops-utils.  This recipe could then be included by any other recipe/role that wanted to lay the file down.

**Comment by mancdaz** [comment]
the following patch adds a recipe to the osops-utils cookbook that can be included from anywhere, or added to a node's runlist:

https://github.com/rcbops-cookbooks/osops-utils/pull/117

from within a cookbook:

```
include_recipe "osops-utils::openrc"
```

to add to a runlist:

```
knife node run_list add <nodename> "recipe[osops-utils::openrc]"
```

**Comment by cjoelrun** [comment]
I get an error when running this on a single-network-node. https://gist.github.com/cjoelrun/6083970

**Comment by Apsu** [comment]
I don't see why you would want an openrc on a single-network-node box that doesn't have the other quantum roles. single-network-node doesn't actually provide any clients, so openrc seems pretty pointless.

Can you elaborate on your use-case?

**Comment by jacobwagner** [comment]
I think this is an old issue that I should have revisted and closed when the functionality of how the neutron recipes worked changed. This was an issue with the first revision of the neutron cookbooks were being tested. This card got lost in the madness that was v4 release testing.
