### ISSUE TITLE
[DE191] Keystone API inaccessible when using HA controller and separate public / private networks.

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/chef-cookbooks#455]
Might be related to issue #451...

I have an HA pair using separate public and private networks, and the Keystone API ends up being inaccessible to the public. Couple things stand out to me:
1. The VIP for private access to the Keystone API (192.168.2.53) is on the wrong interface. It should be eth0.
2. The VIP for public access to the Keystone API (172.16.0.50) is forwarding to an IP address Keystone is not configured to listen on.
## VIPS and OSOPS Networks:

```
"vips": {
  "mysql-db": "192.168.2.51",
  "rabbitmq-queue": "192.168.2.52",
  "keystone-admin-api": "192.168.2.53",
  "cinder-api": "172.16.0.50",
  "glance-api": "172.16.0.50",
  "glance-registry": "172.16.0.50",
  "horizon-dash": "172.16.0.50",
  "horizon-dash_ssl": "172.16.0.50",
  "keystone-internal-api": "172.16.0.50",
  "keystone-service-api": "172.16.0.50",
  "nova-api": "172.16.0.50",
  "nova-ec2-public": "172.16.0.50",
  "nova-novnc-proxy": "172.16.0.50",
  "nova-xvpvnc-proxy": "172.16.0.50"
}

"osops_networks": {
  "nova": "192.168.2.0/24",
  "management": "192.168.2.0/24",
  "public": "172.16.0.0/24"
}
```
## Controller01 Network Configuration:

**eth0** - nova / management network
**eth2** - public network

```
root@controller01:~# ip addr show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:a3:7a:7a brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.1/24 brd 192.168.2.255 scope global eth0
    inet 192.168.2.51/32 scope global eth0
    inet 192.168.2.52/32 scope global eth0
    inet6 fe80::a00:27ff:fea3:7a7a/64 scope link 
       valid_lft forever preferred_lft forever

root@controller01:~# ip addr show eth2
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:99:0c:a1 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/24 brd 172.16.0.255 scope global eth2
    inet 172.16.0.50/32 scope global eth2
    inet6 fe80::a00:27ff:fe99:ca1/64 scope link 
       valid_lft forever preferred_lft forever
```
## KeepAliveD Configuration:

**vrrp_VI_192_168_2_51.conf:**

```
vrrp_instance VI_192_168_2_51 {
  interface eth0
  virtual_router_id 10
  state BACKUP
  priority 100
  virtual_ipaddress {
      192.168.2.51
  }
  track_script {
    mysql
  }

}
```

**vrrp_VI_192_168_2_52.conf:**

```
vrrp_instance VI_192_168_2_52 {
  interface eth0
  virtual_router_id 11
  state BACKUP
  priority 100
  virtual_ipaddress {
      192.168.2.52
  }
  track_script {
    rabbitmq
  }

  notify_backup "/usr/sbin/service rabbitmq-server restart"
  notify_fault "/usr/sbin/service rabbitmq-server restart"
}
```

**vrrp_VI_192_168_2_53.conf:**

```
vrrp_instance VI_192_168_2_53 {
  interface eth2
  virtual_router_id 12
  state BACKUP
  priority 100
  virtual_ipaddress {
      192.168.2.53
  }
  track_script {
    haproxy
  }

  notify_fault "/usr/sbin/service haproxy restart"
}
```

**vrrp_VI_172_16_0_50.conf:**

```
vrrp_instance VI_172_16_0_50 {
  interface eth2
  virtual_router_id 12
  state BACKUP
  priority 100
  virtual_ipaddress {
      172.16.0.50
  }
  track_script {
    haproxy
  }

  notify_fault "/usr/sbin/service haproxy restart"
}
```
## HAProxy Configuration:

**vs_keystone-admin-api.cfg**

```
listen keystone-admin-api 192.168.2.53:35357
    mode http
    balance roundrobin
    option forwardfor
    option httpchk
    option httplog
    server keystone-admin-api-1 192.168.2.1:35357 check
```

**vs_keystone-service-api.cfg**

```
listen keystone-service-api 172.16.0.50:5000
    mode http
    balance roundrobin
    option forwardfor
    option httpchk
    option httplog
    server keystone-service-api-1 172.16.0.1:5000 check
```

**Comment by byronmccollum** [comment]
Of note, this is the state after just the first `chef-client` run on controller01. During the second run, it errors out trying to talk to Keystone to update the various endpoints in the service catalog.

I can confirm, manually correcting the two issues above allows both public and private access to Keystone.

**Comment by breu** [comment]
@mancdaz This may be unrelated to the work that you did this morning but maybe not.  Can you take a look?

**Comment by byronmccollum** [comment]
Other unknown side effects...

Should the generated openrc point to the public load balanced auth endpoint (172.16.0.50:5000), or should there be another HAProxy config to load balance private access too (192.168.2.53:5000).

**Comment by mancdaz** [comment]
> The VIP for private access to the Keystone API (192.168.2.53) is on the wrong interface. It should be eth0.

Change/override the attribute here to get that service on the desired network:
https://github.com/rcbops-cookbooks/openstack-ha/blob/grizzly/attributes/default.rb#L10

> The VIP for public access to the Keystone API (172.16.0.50) is forwarding to an IP address Keystone is not configured to listen on.

Where is keystone listening?  You might need to alter the relevant networks here:

https://github.com/rcbops-cookbooks/keystone/blob/grizzly/attributes/default.rb#L131-L144

**Comment by byronmccollum** [comment]
Thanks! I'll muck around with that and get back to you...

**Comment by mancdaz** [comment]
@byronmccollum did you manage to get things working?

**Comment by mancdaz** [comment]
@byronmccollum I'm going to close this off for now on the assumption that setting those attributes worked for you.

If not, please reopen

**Comment by byronmccollum** [comment]
No, I wasn't able to get it working. And based on the discussion in #463, it sounds like what I'm trying to do just isn't supported by the openstack-ha cookbook.

**Comment by byronmccollum** [comment]
Setting the following seems to make this all work:

```
"keystone": {
  "services": {
    "service-api": {
      "network": "nova"
    }
  }
```

I'm wondering if that should be the default (instead of public), or else the VIPs point to an IP Keystone isn't listening on. I'm going to verify that making this the default doesn't interfere with non-HA setups.

**Comment by byronmccollum** [comment]
Yup, things seem to be working as expected, both HA and non-HA.
