### ISSUE TITLE
[DE170]: [nova] & [nova-network]: nova-api-metadata, nova-compute, nova-network do not restart after nova.conf change

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#456]
When the nova.conf changes on a compute node, the services that use it (nova-api-metadata, nova-compute, nova-network) do not restart automatically in the chef run.

**Comment by jcannava** [comment]
@odyssey4me this should have been corrected in:
 https://github.com/rcbops-cookbooks/nova/commit/3caa4c4a676e9e798b810f80af4ed18d288f855c
 https://github.com/rcbops-cookbooks/nova-network/commit/583dba6ee4182561bf97164abb90421ba2c0ac93

I will go ahead and close, but please feel free to reopen if you continue to see the issue.
