### ISSUE TITLE
[DE204]: Down mysql does not cause failover in Ubuntu

### ISSUE THREAD

**Issue by kstev** [rcbops/chef-cookbooks#468]
Relevant line set in "mysql-openstack/recipes/server.rb"

"/usr/sbin/service mysql status" returns a 0 exit status whether mysqld is running or not so this keepalived script (/etc/keepalived/conf.d/script_mysql.conf) doesn't seem to do anything at least in Ubuntu.

**Comment by hughsaunders** [comment]
Hi @kstev, I have merged a small patch to change the keepalived healthcheck for mysqld to killall -0. Failover is succesfull if the mysqld stops. It will not be effective if the daemon hangs. See: https://github.com/rcbops-cookbooks/mysql-openstack/pull/44
