### ISSUE TITLE
[DE205]: knife cookbook upload -a -o fails to upload cookbooks on first run, succeeds on second

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#469]
http://tickets.opscode.com/browse/CHEF-4330

Putting this here so we can track it

upstream bug

**Comment by jacobwagner** [comment]
Upgrade path bug

When upgrading chef cookbooks from 3.x to 4.0 this may happen, we are seeing it happen when we both update the cookbooks in place (i.e. dont create a new directory) and when we create a new directory and upload using the -a,--all flag

more testing underway

**Comment by DavidWittman** [comment]
@jacobwagner Thanks for opening this bug w/ Opscode. I've been running into the same issues.

**Comment by jacobwagner** [comment]
@DavidWittman I found that you can either delete the cookbooks via knife (not the best, but works) or simply run the upload command twice to get past the issue

**Comment by zfeldstein** [comment]
Info for this upstream bug is in release notes, closing this issue.
