### ISSUE TITLE
[DE206]: [osops-utils]: get_bind_endpoint does not work as documented

### ISSUE THREAD

**Issue by DavidWittman** [rcbops/chef-cookbooks#470]
RCB::get_bind_endpoint does not allow for overriding service URIs at the attribute level [as documented in ip_location.rb](https://github.com/rcbops-cookbooks/osops-utils/blob/grizzly/libraries/ip_location.rb#L28-L44):

>  # Get the bind information necessary for a service.
>  # ex: IPManagement.get_bind_endpoint("keystone","admin")
>  # { "host" => "10.1.0.2",
>  # "port" => 35357,
>  # "scheme" => "http",
>  # "path" => "/v2.0",
>  # "uri" => "http://10.1.0.2:35357/v2.0"
>  # "network" => "management"
>  #
>  # To define this resource, there must be a service entries like...
>  # node["keystone"]["services"]["admin"] =
>  # { "network" => "management", "port" => 35357 }
>  #
>  # IP address is derived from required network, unless overridden
>  # Protocol defaults to "http", path defaults to "/". If a URI
>  # is specified, it overrides all other settings, otherwise it is
>  # composed from the individual components
### What am I doing?

Setting attributes to override service endpoint URIs. e.g. 

``` ruby
node['nova']['services']['novnc-proxy']['uri'] = "http://dashboard.howopenstack.org:6080/vnc_auto.html"
```
### What do I expect to happen?

The endpoint to use the URI which I specified.
### What happens instead?

get_bind_endpoint ends up looking for a locally bound network anyway, ignoring the URI set in the environment.
### Why?

There is logic in [get_config_endpoint](https://github.com/rcbops-cookbooks/osops-utils/blob/grizzly/libraries/ip_location.rb#L118-L122) which checks for the node[server]['services'][service] attribute:

``` ruby
if svc.keys.include?("uri")
  uri = URI(svc["uri"])
  ["path", "scheme", "port", "host"].each do |x|
    retval.merge!(x => uri.send(x))
  end
```

But the information retrieved here ends up getting nuked later on in [get_bind_endpoint](https://github.com/rcbops-cookbooks/osops-utils/blob/grizzly/libraries/ip_location.rb#L141-L148):

``` ruby
if not retval.empty?
  # we'll get the network from the osops network
  retval["host"] =
    Chef::Recipe::IPManagement.get_ip_for_net(retval["network"], nodeish)
  retval["uri"] =
    "#{retval['scheme']}://#{retval['host']}:#{retval['port']}"
  retval["uri"] += retval["path"]
  retval
```

**Comment by hughsaunders** [comment]
Hi, I've patched get_bind_endpoint in PR https://github.com/rcbops-cookbooks/osops-utils/pull/106, however gating issues are currently preventing this from going in.

**Comment by hughsaunders** [comment]
Hi @DavidWittman, the above PR has now been merged. Please re-open this issue if the above does not solve your problem. 

Thanks.

**Comment by hughsaunders** [comment]
Hmm, that patch I submitted only prevents the host from being overridden, not the whole URI. Will add logic for that as well.

**Comment by hughsaunders** [comment]
Added https://github.com/rcbops-cookbooks/osops-utils/commit/c5131c71f241051682215721bd5dec06785860c7 to protect uri, very similar to previous patch for host.

**Comment by kstev** [comment]
Hello,

I believe this still does not work correctly.

For example, if I set the following override attribute so that I may be able to view the console of an instance while accessing the the dashboard from a different network:
node['nova']['services']['novnc-proxy']['uri'] = "novncproxy_base_url=http://160.240.200.160:6080/vnc_auto.html"

...chef makes the following change to /etc/nova/nova.conf:
-novncproxy_host=10.240.0.176
+novncproxy_host=160.240.200.160

I would expect this change to occur instead:
-novncproxy_base_url=http://10.240.0.5:6080/vnc_auto.html
+novncproxy_base_url=http://160.240.200.160:6080/vnc_auto.html

Please let me know if I need to open a new issue for this...
