### ISSUE TITLE
[DE207]: MISSING ROLE: keystone-setup

### ISSUE THREAD

**Issue by pedrojimenez** [rcbops/chef-cookbooks#471]
When applying the role: **single-controller** i have found 2 calls to an unexisting role:

```
keystone-setup
```

https://github.com/rcbops-cookbooks/keystone/blob/grizzly/recipes/keystone-common.rb#L73

https://github.com/rcbops-cookbooks/keystone/blob/grizzly/recipes/keystone-api.rb#L26

I have created it manually and replaced it in **single-controller.rb**

```
name "single-controller"
description "Nova Controller (non-HA)"
run_list(
[ ... ]
  #"role[keystone]",
  "role[keystone-setup]",
[ ... ]
```

The keystone-setup role is a single call to the previous keystone.

```
name "keystone-setup"
description "Keystone server SeTUp"
run_list(
    "role[keystone]"
    )
```

**Comment by hughsaunders** [comment]
Hi, 
Thanks for the feedback, however the roles keystone and keystone-setup should both exist. The keystone role was recently split into keystone-setup and keystone-api:

role[keystone] --> [keystone-setup + keystone-api]
role[keystone-setup] --> recipe[keystone::setup]
role[keystone-api] --> recipe[keystone::api]

Please try removing the roles from your chef server then uploading the latest set of roles. This should solve the issue, if not please re-open this issue (or if not possible, open a new issue). 

Thanks again for the feedback.

**Comment by pedrojimenez** [comment]
Done. It works like a charm.

Regards.
