### ISSUE TITLE
[DE208]: Images Not Replicating Between HA Controllers

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/chef-cookbooks#472]
It seems images are not replicating between HA controllers. Bot the initially loaded images and new ones only land on one controller.

I've manually run the cron job `/var/lib/glance/glance-image-sync.py both`, but it didn't seem to do anything. Manually running the rsync command from `glance-image-sync.py` seems to do the trick. I'm guessing it's a problem getting messages from rabbit.

**Comment by byronmccollum** [comment]
In `glance-api.conf`, should `notifier_strategy = noop` actually be `notifier_strategy = rabbit`?

**Comment by byronmccollum** [comment]
Setting `glance["api"]["notifier_strategy"] = rabbit` fixes this.

**Comment by mattt416** [comment]
Hi @byronmccollum,

That's correct.  In fact, the glance cookbook should set this automatically if it sees two glance-api nodes, however it does appear to take a few chef-client runs on each node for everything to fully converge.  I will work on fixing this over the next few weeks.

Thanks!

-matt
