### ISSUE TITLE
[DE210]: Consider using Galera for HA MySQL

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#474]
[Galera](http://codership.com/content/using-galera-cluster) appears to be a much more reliable multi-master implementation of MySQL than the current implementation used.

Using Galera may pave the way to actually allowing load balanced connections to any of the MySQL instances in the environment - improving scalability. The current cookbooks only point at one of the instances.

**Comment by hughsaunders** [comment]
Hi, 
Thanks for your suggestion, we appreciate the feedback. I have added this as a user story to our development backlog, and it will be considered for future sprints.
