### ISSUE TITLE
[DE211]: cinder-volume node need api-paste.init ?

### ISSUE THREAD

**Issue by jedipunkz** [rcbops/chef-cookbooks#475]
I boostraped 4 nodes by each roles.
- ha-controller1
- ha-controller2
- single-compute
- cinder-volume

When I boostraped these nodes, api-paste.ini on cinder-volume node does not include these lines... These parameters were not setuped.

<pre>
service_host = 10.200.9.68
service_port = 5000
auth_host = 10.200.9.6.68
auth_port = 35357
auth_protocol = http
admin_tenant_name = service
admin_user = cinder
admin_password = 94cwkk8fKntJ7ssd0
</pre>

When I setup these parameter, cinder can create test volume and attach to the instance.

So, Does cinder-volume's recipe need to include this template resoruces ?

```
template "/etc/cinder/api-paste.ini" do
....
```

Thanks.

**Comment by mancdaz** [comment]
Hi @jedipunkz 

Actually, I'm not sure what problem you were having, but cinder api-paste.ini is not actually needed on the cinder-volume node.  I am able to successfully create/delete/attach volumes without it.

In actual fact, we shouldn't even be pulling in the cinder-api package on a cinder-volume standalone node, but at the moment we are (and this is why you see an api-paste.ini file at all).  So this is something we should probably fix.

**Comment by mancdaz** [comment]
fixed in https://github.com/rcbops-cookbooks/cinder/pull/66
