### ISSUE TITLE
[DE212]: [osops-utils] Separate Packages and Repositories

### ISSUE THREAD

**Issue by claco** [rcbops/chef-cookbooks#477]
With this change, I now get all of the wonderful openstacky client packages...on machines I don't need it on:

https://github.com/rcbops-cookbooks/osops-utils/commit/133631c4243d883e5f5f48ea5dc43c42ab914792

For example, a swift storage node. I want the repos, so I was using ::packages, which was fine until it started installing things all willky nillky. We should probably split this out into separate recipes.

**Comment by mancdaz** [comment]
this has now been resolved by backing this change out and fixing in different ways.
