### ISSUE TITLE
[DE214]: [nova] rabbitmq won't start on centos 6.4

### ISSUE THREAD

**Issue by rpedde-rcbops** [rcbops/chef-cookbooks#479]
per customer report, on centos 6.4 qpid is dragged in by default instead of rabbit, and binds to the same port as rabbit, flummoxing things.

I have not repro'd this.

**Comment by andymcc** [comment]
I wasn't able to reproduce this - I used the ha-controller1 role on centos 6.4 and qpid wasn't running, rabbitmq came up normally and services are working/responding.

Can we get more details on this so that we can reproduce it?

**Comment by DavidWittman** [comment]
No issues here either, just tested an all-in-one on CentOS 6.4 last night.

**Comment by breu** [comment]
@DavidWittman did you test with a cloud server or a new baremetal install of CentOS?  I think qpid gets installed when you do a basic install of CentOS from ISO, but I haven't dug into it at all.

**Comment by DavidWittman** [comment]
@rackerjoe It was a Cloud Server. I'll kick a CentOS VM and see if it pulls in qpid.

**Comment by DavidWittman** [comment]
Didn't test a full OpenStack install, but a "Basic" install of CentOS 6.4 from the ISO doesn't install qpid or anything else running on 5672. I searched all of the group packages pulled in for the [different install types](http://wiki.centos.org/FAQ/CentOS6) (Under "What groups are included in each option at install time?") and didn't find anything either.

_shrug_

**Comment by mancdaz** [comment]
cannot reproduce - closing
