### ISSUE TITLE
[DE215]: image_cache_manager_interval

### ISSUE THREAD

**Issue by rpawlik** [rcbops/chef-cookbooks#480]
Guys,

We need the ability to be able to set "image_cache_manager_interval". By default it's set to zero:

```
cfg.IntOpt("image_cache_manager_interval",
           default=0,
```

This means old base disks (backing files) will not be removed and will collect on the host causing potential space issues.

Let me know if you have any further questions.

**Comment by git-harry** [comment]
@rpawlik 

An attribute has now been added to allow this to be configured - https://github.com/rcbops-cookbooks/nova/pull/320
