### ISSUE TITLE
[DE219]: [swift] : possible bug in providers/ring_script.rb:parse_ring_output

### ISSUE THREAD

**Issue by ghost** [rcbops/chef-cookbooks#485]
The read ring has the following format:
id      region  zone    ipaddr    port    dev     weight     partitions balance
Thus, the output constructed by the function is keyed according to [zone][port]
This results devices from the same zone belonging to the same ring to overwrite one another.

am new around here, I hope that the followng makes sense.

**Comment by mancdaz** [comment]
Hi @eranrom 

Please could you provide a bit more detail on this, including logs, what the expected output was, and what the observed output was.  This will help us in pinpointing where the bug may lie.

Thanks!

**Comment by ghost** [comment]
Apologies for the late reply.
I will need to re-deploy my cluster to give accurate output.
In the mean time, I think I can point at the actual problem (might be wrong though)

Consider the following steps which are part of a SWIFT cluster deployment / ongoing management:
(1) The generate_ring.sh script is executed (output below)
(2) At some later point in time chef-client is executed on the management node,e.g. in the case some devices were added to a certain node. This chef-client run parses the existing ring to calculate the difference and update the generate_ring script as necessary. 

Now, the current parsing code looks like this (pasting only the relevant portion of it)
....
   elsif line =~ /^\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+.\d+.\d+.\d+)\s+(\d+)\s+(\S+)\s+([0-9.]+)\s+(\d+)\s+([-0-9.]+)\s*$/
      output[:hosts] ||= {}
      output[:hosts][$3] ||= {}
      output[:hosts][$3][$5] = {}
      output[:hosts][$3][$5][:id] = $1
      output[:hosts][$3][$5][:region] = $2
      output[:hosts][$3][$5][:zone] = $3
      output[:hosts][$3][$5][:ip] = $4
      output[:hosts][$3][$5][:port] = $5
      output[:hosts][$3][$5][:device] = $6
      output[:hosts][$3][$5][:weight] = $7
      output[:hosts][$3][$5][:partitions] = $8
      output[:hosts][$3][$5][:balance] = $9
    elsif line =~ /(\d+) partitions, (\d+.\d+) replicas, (\d+) regions, (\d+) zones, (\d+) devices, (\d+.\d+) balance$/
....
Now, with the hash keys being the zone and port, all devices in a given zone are 'collapsed' to one.
Below is a generate_rings.sh script that I have edited for the purpose of the description, but the format is exactly as being generated (I am showing only the object ring)
One gets a parsed Hash with only one device per zone (also shown below)
fixing the keys to be ip, device gives the desired output. (also shown below)

Two more points
1. As you can see I am using device names instead of UUIDs. I believe that this is of no relevance to the problem.
2. I saw that in the master branch the parse_ring_output code is a bit different and has an additional case for a line format in a ring (my guess it has to do with the region new feature). Still I think that it does not cover the ring line format created in Grizzly.

object ring portion from generate_rings.sh (sorted by zone/device):
swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z1-10.5.0.101:6000/sda1 2861022
swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z1-10.5.0.101:6000/sdc1 2861022
swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z1-10.5.0.101:6000/sdd1 2861022
swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z1-10.5.0.101:6000/sde1 952720

swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z2-10.5.0.102:6000/sda1 2861022
swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z2-10.5.0.102:6000/sdc1 2861022
swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z2-10.5.0.102:6000/sdd1 2861022
swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z2-10.5.0.102:6000/sde1 952720

swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z3-10.5.0.103:6000/sda1 2861022
swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z3-10.5.0.103:6000/sdc1 2861022
swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z3-10.5.0.103:6000/sdd1 2861022
swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z3-10.5.0.103:6000/sde1 952720

swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z7-10.5.0.107:6000/sda1 2861022
swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z7-10.5.0.107:6000/sdd1 2861022
swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z7-10.5.0.107:6000/sdc1 2861022
swift-ring-builder /etc/swift/ring-workspace/rings/object.builder add z7-10.5.0.107:6000/sde1 952720

Here is a print out of the Hash being constructed by the code that parses the existing object ring:
{
  :state=>
    {
      :build_version=>"16", 
      :partitions=>"262144", 
      :replicas=>"3.000000", 
      :regions=>"1", 
      :zones=>"5", 
      :devices=>"16", 
      :balance=>"0.00", 
      :min_part_hours=>"1"
    }, 
    :hosts=>{
      "1"=>{
        "6000"=>{
          :id=>"0", 
          :region=>"1",
          :zone=>"1", 
          :ip=>"10.5.0.101", 
          :port=>"6000", 
          :device=>"sdd1", 
          :weight=>"2861022.00", 
          :partitions=>"58988", :balance=>"-0.00"
        }
      }, 
      "5"=>{
        "6000"=>{
          :id=>"3", 
          :region=>"1", 
          :zone=>"5", 
          :ip=>"10.5.0.101", 
          :port=>"6000", 
          :device=>"sdc1", 
          :weight=>"2861022.00", 
          :partitions=>"58988", 
          :balance=>"-0.00"
        }
      }, 
      "2"=>{
        "6000"=>{
          :id=>"7", 
          :region=>"1", 
          :zone=>"2", 
          :ip=>"10.5.0.102", 
          :port=>"6000", 
          :device=>"sda1", 
          :weight=>"2861022.00", 
          :partitions=>"58989", 
          :balance=>"0.00"
        }
      }, 
      "3"=>{
        "6000"=>{
          :id=>"11", 
          :region=>"1", 
          :zone=>"3", 
          :ip=>"10.5.0.103", 
          :port=>"6000", 
          :device=>"sda1", 
          :weight=>"2861022.00", 
          :partitions=>"58988", 
          :balance=>"-0.00"
        }
      }, 
      "7"=>{
        "6000"=>{
          :id=>"15", 
          :region=>"1", 
          :zone=>"7", 
          :ip=>"10.5.0.107", 
          :port=>"6000", 
          :device=>"sdd1", 
          :weight=>"2861022.00", 
          :partitions=>"58989", 
          :balance=>"0.00"
        }
      }
    }

Here is a print out of the Hash being constructed by the code that parses the existing object ring when using ip, device as keys:
{
  :state=>{
    :build_version=>"16", 
    :partitions=>"262144", 
    :replicas=>"3.000000", 
    :regions=>"1", 
    :zones=>"4", 
    :devices=>"16", 
    :balance=>"0.00", 
    :min_part_hours=>"1"
  }, 
  :hosts=>{
    "10.5.0.101"=>{
      "sdd1"=>{:id=>"0", :region=>"1", :zone=>"1", :ip=>"10.5.0.101", :port=>"6000",        :device=>"sdd1", :weight=>"2861022.00", :partitions=>"58988", :balance=>"-0.00"},
      "sde1"=>{:id=>"1", :region=>"1", :zone=>"5", :ip=>"10.5.0.101", :port=>"6000",        :device=>"sde1", :weight=>"952720.00", :partitions=>"19643", :balance=>"-0.00"}, 
      "sda1"=>{:id=>"2", :region=>"1",:zone=>"5",:ip=>"10.5.0.101",:port=>"6000",
        :device=>"sda1", :weight=>"2861022.00", :partitions=>"58989",:balance=>"0.00"},
      "sdc1"=>{:id=>"3", :region=>"1", :zone=>"5", :ip=>"10.5.0.101", :port=>"6000",                :device=>"sdc1", :weight=>"2861022.00", :partitions=>"58988", :balance=>"0.00"
      }
    }, 
    "10.5.0.102"=>{
      "sdc1"=>{:id=>"4", :region=>"1", :zone=>"2", :ip=>"10.5.0.102", :port=>"6000",                :device=>"sdc1", :weight=>"2861022.00", :partitions=>"58988", :balance=>"-0.00"},
      "sde1"=>{:id=>"5", :region=>"1", :zone=>"2", :ip=>"10.5.0.102", :port=>"6000",                :device=>"sde1", :weight=>"952720.00", :partitions=>"19643", :balance=>"-0.00"},
      "sdd1"=>{:id=>"6", :region=>"1", :zone=>"2", :ip=>"10.5.0.102", :port=>"6000",        :device=>"sdd1", :weight=>"2861022.00", :partitions=>"58988", :balance=>"-0.00"},
      "sda1"=>{:id=>"7", :region=>"1", :zone=>"2", :ip=>"10.5.0.102", :port=>"6000",        :device=>"sda1", :weight=>"2861022.00", :partitions=>"58989", :balance=>"0.00"
      }
    },
    "10.5.0.103"=>{
      "sdd1"=>{:id=>"8", :region=>"1", :zone=>"3", :ip=>"10.5.0.103", :port=>"6000",        :device=>"sdd1", :weight=>"2861022.00", :partitions=>"58988", :balance=>"-0.00"},
      "sdc1"=>{:id=>"9", :region=>"1", :zone=>"3", :ip=>"10.5.0.103", :port=>"6000",        :device=>"sdc1", :weight=>"2861022.00", :partitions=>"58988", :balance=>"-0.00"}, 
      "sde1"=>{:id=>"10", :region=>"1", :zone=>"3", :ip=>"10.5.0.103", :port=>"6000",               :device=>"sde1", :weight=>"952720.00", :partitions=>"19644", :balance=>"0.00"},
      "sda1"=>{:id=>"11", :region=>"1", :zone=>"3", :ip=>"10.5.0.103", :port=>"6000",       :device=>"sda1", :weight=>"2861022.00", :partitions=>"58988", :balance=>"-0.00"
      }
    },
    "10.5.0.107"=>{
      "sde1"=>{:id=>"12", :region=>"1", :zone=>"7", :ip=>"10.5.0.107", :port=>"6000",       :device=>"sde1", :weight=>"952720.00", :partitions=>"19643", :balance=>"-0.00"}, 
      "sda1"=>{:id=>"13", :region=>"1", :zone=>"7", :ip=>"10.5.0.107", :port=>"6000",       :device=>"sda1", :weight=>"2861022.00", :partitions=>"58988", :balance=>"-0.00"},
      "sdc1"=>{:id=>"14", :region=>"1", :zone=>"7", :ip=>"10.5.0.107", :port=>"6000",       :device=>"sdc1", :weight=>"2861022.00", :partitions=>"58988", :balance=>"-0.00"},
      "sdd1"=>{:id=>"15", :region=>"1", :zone=>"7", :ip=>"10.5.0.107", :port=>"6000",       :device=>"sdd1", :weight=>"2861022.00", :partitions=>"58989", :balance=>"0.00"
      }
    }
  }
}

**Comment by jcannava** [comment]
@eranrom apologies for the lack of response here. We are currently re-working a significant amount of the swift cookbooks. As such I am going to close this issue and suggest that you take a look at https://github.com/rcbops-cookbooks/swift-lite and https://github.com/rcbops-cookbooks/swift-private-cloud.
