### ISSUE TITLE
[DE221]: Enable CSS compression in dashboard on RHEL

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/chef-cookbooks#486]
Currently on RHEL, Horizon serves the raw less file without preprocessing to CSS, so you end up with an unskinned dashboard.

This is due to https://github.com/rcbops-cookbooks/horizon/blob/grizzly/templates/default/local_settings.py.erb#L22-24

Needs a dependency on nodejs-less from EPEL for /usr/bin/lessc and the COMPRESS_ENABLED line removed from local_settings.

**Comment by DavidWittman** [comment]
Looks like nodejs-less isn't available in 5.x from EPEL :squirrel:

It might be less troublesome just to convert the configs to flat CSS and get rid of the Node.js dependency altogether.

**Comment by Apsu** [comment]
You're targeting 5.x in any way shape or form? Say it ain't so D:

**Comment by DavidWittman** [comment]
Excellent point. That makes it easy.

**Comment by DavidWittman** [comment]
Fixed by rcbops-cookbooks/horizon#115 (Grizzly) and rcbops-cookbooks/horizon#116 (Folsom).
