### ISSUE TITLE
HA Controllers Require Several More `chef-client` Runs

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/chef-cookbooks#494]
#### This is an issue in the `v4.0.0` branch of the cookbooks, which is the default for RPCS. Please do not close saying it was fixed in a different brach.

---

The documentation instructs the user to run `chef-client` on **controller1**, **controller2**, then again on **controller1**. This will leave the environment partially configured, and several more `chef-client` runs are needed to fully complete the installation, some to be run _after_ the `chef-client` runs on the compute nodes. If this is by design, then the documentation needs to be updated. Either way, the documentation and the actual process are out of sync.

For a cluster consisting of an HA pair of controllers, and two compute nodes, the order of `chef-client` runs should be the following (with a few notes of what gets configured at later stages):
- **controller1**
- **controller2**
- **controller1**
- **controller2**
  - VIPs - Use VIPs for various service endpoints
  - Glance - Add missing `sql_connection` password  in `glance-registry.conf`
  - Glance - Add missing service user password in `glance-registry.conf`
  - Glance - Add missing service user password in `glance-registry-paste.ini`
  - Glance Image Sync - Update `notifier_strategy` in `glance-api.conf`
  - Glance Image Sync - Update `api_nodes` in `glance-image-sync.conf`
- **controller1**
  - Glance Image Sync - Update `notifier_strategy` in `glance-api.conf`
- **compute1**
- **compute2**
- **controller1**
  - Nova - Update authorized keys
- **controller2**
  - Nova - Update authorized keys
- **compute1**
  - Nova - Update authorized keys
- **compute2**
  - Nova - Update authorized keys

---
#### `chef-client` Logs
1.  [controller1](http://3a08087126277193ad07-12903d46605b280d040e55edd2897887.r15.cf1.rackcdn.com/ha-controller-chef-client-logs/01-controller1.txt)
2.  [controller2](http://3a08087126277193ad07-12903d46605b280d040e55edd2897887.r15.cf1.rackcdn.com/ha-controller-chef-client-logs/02-controller2.txt)
3.  [controller1](http://3a08087126277193ad07-12903d46605b280d040e55edd2897887.r15.cf1.rackcdn.com/ha-controller-chef-client-logs/03-controller1.txt)
4.  [controller2](http://3a08087126277193ad07-12903d46605b280d040e55edd2897887.r15.cf1.rackcdn.com/ha-controller-chef-client-logs/04-controller2.txt)
5.  [controller1](http://3a08087126277193ad07-12903d46605b280d040e55edd2897887.r15.cf1.rackcdn.com/ha-controller-chef-client-logs/05-controller1.txt)
6.  [compute1](http://3a08087126277193ad07-12903d46605b280d040e55edd2897887.r15.cf1.rackcdn.com/ha-controller-chef-client-logs/06-compute1.txt)
7.  [compute2](http://3a08087126277193ad07-12903d46605b280d040e55edd2897887.r15.cf1.rackcdn.com/ha-controller-chef-client-logs/07-compute2.txt)
8.  [controller1](http://3a08087126277193ad07-12903d46605b280d040e55edd2897887.r15.cf1.rackcdn.com/ha-controller-chef-client-logs/08-controller1.txt)
9.  [controller2](http://3a08087126277193ad07-12903d46605b280d040e55edd2897887.r15.cf1.rackcdn.com/ha-controller-chef-client-logs/09-controller2.txt)
10. [compute1](http://3a08087126277193ad07-12903d46605b280d040e55edd2897887.r15.cf1.rackcdn.com/ha-controller-chef-client-logs/10-compute1.txt)
11. [compute2](http://3a08087126277193ad07-12903d46605b280d040e55edd2897887.r15.cf1.rackcdn.com/ha-controller-chef-client-logs/11-compute2.txt)

**Comment by mattt416** [comment]
Hello @byronmccollum,

We have eliminated the need for some chef-client runs in our grizzly branch and are currently working out how to backport these fixes to v4.0.0.  I'll leave this issue open until we have something implemented.

With that said, it is likely that we will need to update our documentation so I will review that and get it updated as is necessary.

Lastly, I don't believe the controller1/controller2 chef-client runs to get the authorized_keys files updated are necessary as IIRC it's only the compute nodes that need to be able to log into one-another.  Can you please let me know if that is in fact incorrect?

Regards,
Matt

**Comment by byronmccollum** [comment]
The last couple runs on the controllers might not be needed, but I just wanted to be thorough in documenting.

Thanks

**Comment by mattt416** [comment]
Closing this as v4.1.2 has now been released.
