### ISSUE TITLE
HA Controllers Automatically Registered Images Never Get Synced

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/chef-cookbooks#495]
#### This is an issue in the `v4.0.0` branch of the cookbooks, which is the default for RPCS. Please do not close saying it was fixed in a different brach.

---

Any images that are automatically registered (which is the default for RPCS) will only end up on one of the two controllers. Glance Image Sync doesn't get fully configured until after these images have been uploaded (see #494), and will never be replicated across. Attempts to launch instances using these images will be a crap shoot, depending on which controller the request is forwarded to.

Temporary fix is to override the default:

```
"glance": {
    // Prevent automatically uploading images until glance-image-sync is fully installed
    "image_upload": false
}
```

**Comment by mattt416** [comment]
Hi @byronmccollum,

Thanks for creating this issue.  The glance image sync issue outlined in https://github.com/rcbops/chef-cookbooks/issues/496 should not affect the images in https://github.com/rcbops-cookbooks/glance/blob/grizzly/attributes/default.rb#L72-L76 as any images ending in ".qcow2" or ".img" are not actually stored on the filesystem but are created as glance images pointing to a remote location (see https://github.com/rcbops-cookbooks/glance/blob/grizzly/providers/image.rb#L75, namely the --location flag).

I'm going to go ahead and close this issue -- we will deal w/ the remaining sync issues in https://github.com/rcbops/chef-cookbooks/issues/496.

Regards,
Matt

**Comment by byronmccollum** [comment]
Actually, the `v4.0.0` branch has an AMI as part of its default images to load.

https://github.com/rcbops-cookbooks/glance/blob/v4.0.0/attributes/default.rb#L58

**Comment by mattt416** [comment]
Hi @byronmccollum,

Thanks for pointing this out.  I was not aware we had changed this recently.  :(

I'll re-open this ticket and we'll provide feedback once we have all the necessary changes in grizzly backported to v4.0.0.

Regards,
Matt

**Comment by breu** [comment]
The images that we auto-register are registered with the URL only as a remote image and therefore are now actually stored on the file system.  They will be fetched from the remote location when an instance is first launched.

**Comment by mancdaz** [comment]
@rackerjoe 

in the v4 branch of the glance cookbook an ami is specified (rather than the img we use in the grizzly branch).   In the glance image provider we take different action (ie physical upload) for an ami:

https://github.com/rcbops-cookbooks/glance/blob/v4.0.0/providers/image.rb#L77-L114

**Comment by breu** [comment]
I may have to retract my statement.  Let me test this out.

**Comment by breu** [comment]
Why did we do this?

**Comment by breu** [comment]
Never mind - I see why we did this.

**Comment by mattt416** [comment]
Closing this as v4.1.2 has now been released.
