### ISSUE TITLE
[DE231]: [nova-network][quantum] osops_network hard coded

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#497]
In quantum-common the network used for the ovs_local_ip is hard coded to the osops_network "nova". This should be parameterised like all other references to the osops_networks.

The offending line is:
https://github.com/rcbops-cookbooks/nova-network/blob/grizzly/recipes/quantum-common.rb#L45

This value is then used here:
https://github.com/rcbops-cookbooks/nova-network/blob/grizzly/recipes/quantum-common.rb#L149

Which provides the value for this line in the template:
https://github.com/rcbops-cookbooks/nova-network/blob/grizzly/templates/default/ovs_quantum_plugin.ini.erb#L8

My suggestion is that something like this is added to the default attributes and used:
default["quantum"]["ovs"]["network"]="nova"

**Comment by Apsu** [comment]
I agree, and fixing local_ip is on our plate, but my goal was to fix it in a more flexible way. In particular, I planned on allowing for a custom "tunnel" osops network and possibly tweaking the osops-utils helper functions so we could query for that network and fallback to a parameterized one if it wasn't defined. That way you're able to cleanly separate a (potentially high-bandwidth or necessarily isolated) network from the standard three osops networks, as well as flexibly choose one other than "nova" per your defect.

**Comment by Apsu** [comment]
Actually, there's a simpler way to meet my goals which is solvable by only changing the code as you suggested. Since a custom osops network can be used simply via defining it as an attribute, if local_ip is parameterized, with a default of nova, a stock config will work as it currently does, but a custom network can simply be defined in the environment and the parameter overridden to the custom network name. I will make this go shortly.

**Comment by odyssey4me** [comment]
Yes, the separation is exactly what we plan to do - although I'm still running through everything with a more stock build first to discover any other defects before I start building fixes.

If you get there first then you're awesome. :)

**Comment by odyssey4me** [comment]
I've submitted a pull request for this: https://github.com/rcbops-cookbooks/nova-network/pull/53

**Comment by odyssey4me** [comment]
The PR has been merged.
