### ISSUE TITLE
[DE233]: [nova-network][quantum] when "ha-controller1" role is not used, secondary nodes can't read the db password

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#499]
When there are multiple "nova-network-controller" roles, with the network provider set to quantum then the secondary nodes can't read the db password.

This is due to the role for reading the setting being hard set to the "ha-controller1" role here:
https://github.com/rcbops-cookbooks/nova-network/blob/grizzly/recipes/quantum-server.rb#L29

It would be better if the recipe was setup to read from the first node, or a "quantum-setup" role (like keystone, et al) instead of being hard coded in this way.

We're not using the ha-controller roles as we don't want to implement absolutely everything on two servers. We're spreading the components out a little more. :)

**Comment by Apsu** [comment]
Doh. Guess the first pass at rolling in the quantum-server HA code didn't take into account using the nova-network-controller role without ha-controller roles :) I'll re-think this and decouple it moar better.

**Comment by odyssey4me** [comment]
Once the above pull request is merged, the rest of the fix is in https://github.com/rcbops-cookbooks/nova-network/pull/54

**Comment by jcannava** [comment]
Looks like the subsequent pull requests had some difficulty passing jenkins, but I believe this has been corrected in other commits. If the problem persists please reopen.
