### ISSUE TITLE
[DE235]: Add custom cert to Horizon

### ISSUE THREAD

**Issue by rpawlik** [rcbops/chef-cookbooks#503]
We need the ability to use custom certs for Horizon. It looks like there's a way to specify a custom cert name, but it will generate a self-signed cert when chef runs. We have a customer that needs to use an actual signed cert.

**Comment by odyssey4me** [comment]
This is already possible. In the horizon cookbook there's a files folder with the horizon.key & horizon.pem files - just replace them with your server's key and certificate file and upload the cookbook into Chef. For a signed certificate you'll need to include the whole chain of certificates in the horizon.pem file for it to work.

**Comment by DavidWittman** [comment]
@odyssey4me Are you referring to horizon/files/default/horizon.{key,pem}? Replacing them is certainly possible, but we'd be unnecessarily forking the Horizon cookbook on any deployment which needs to use a custom certificate. An attribute (or data bag item) which accepts a filename or certificate/key string would be a lot more manageable.

**Comment by JCallicoat** [comment]
+1 for new attribute

**Comment by andymcc** [comment]
https://github.com/rcbops-cookbooks/horizon/pull/118
Done! 
Just specify the ["horizon"]["ssl"]["cert_override"] and "key_override" attributes in your environment, as the location for the files you want to use. That'll be pushed to the vhost.
