### ISSUE TITLE
[DE241]: [osops-utils] rabbit sysctls get dropped in ::default

### ISSUE THREAD

**Issue by rpedde** [rcbops/chef-cookbooks#509]
This makes no sense.  The causes strange sysctls on my swift boxes.  these should be dropped by the recipes that require the sysctls, not as a global default.

**Comment by breu** [comment]
@rpedde I will be removing this shortly from all roles.

**Comment by mancdaz** [comment]
fixed in https://github.com/rcbops-cookbooks/osops-utils/pull/126
