### ISSUE TITLE
[DE246]: [openstack-monitoring] monit not monitoring quantum services

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#512]
When selecting Quantum as the network provider, monit is still set to monitor 'nova-network'. It should be monitoring:
1. quantum-openvswitch-agent
2. quantum-metadata-agent
3. quantum-openvswitch-agent
4. quantum-dhcp-agent
5. quantum-l3-agent
6. quantum-server

**Comment by git-harry** [comment]
Forgot to close this, should be fixed by above referenced pull request.
