### ISSUE TITLE
[DE248]: [nova-network][quantum] 'create external bridge' hard codes the bridge name

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#514]
In https://github.com/rcbops-cookbooks/nova-network/blob/grizzly/recipes/quantum-l3-agent.rb#L52 the bridge name is hard-coded to 'br-ex'.

**Comment by odyssey4me** [comment]
Pull request: https://github.com/rcbops-cookbooks/nova-network/pull/61

**Comment by odyssey4me** [comment]
Another pull request: https://github.com/rcbops-cookbooks/nova-network/pull/68

**Comment by hughsaunders** [comment]
Closed in 68, apologies I missed your PR 61.

**Comment by odyssey4me** [comment]
@hughsaunders No problem! :+1:
