### ISSUE TITLE
[osops-utils] Consider using djbdns/tinydns instead of autoetchosts

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#516]
Consider using djbdns instead of autoetchosts to manage DNS entries in the deployment.

There is already a LWRP: http://docs.opscode.com/lwrp_djbdns.html
And the corresponding recipe: https://github.com/opscode-cookbooks/djbdns

This would allow the flexibility of setting up CNAME's, etc and configuring upstream DNS servers, dynamic updates, etc.

**Comment by mancdaz** [comment]
Hi @odyssey4me 

Great stuff - thanks for the suggestion!  I've added this as a story to our development backlog for consideration in future sprints.

Cheers
@mancdaz

**Comment by claco** [comment]
Here's another alternative w/ the dbj stuff:  https://github.com/customink-webops/hostsfile

And in fact, this recipe could best be served by just using a proper ruby lib rather than what it is now (a blob).
