### ISSUE TITLE
[DE253]: cinder volumes in guest being scanned by host

### ISSUE THREAD

**Issue by chalupaul** [rcbops/chef-cookbooks#520]
LVM volumes within the guest are scanned and picked up by the host. This is because the filter in /etc/lvm/lvm.conf by default scans and picks up any block device. I changed it to:

filter = [ "a/sd._/", "r/._/" ] 

from: 

filter = [ "a/.*/" ]

There's probably a less intrusive way of solving this problem though other than enforcing that lvm devices will be only /dev/sdX. 

You'll know its broken when you have a guest with lvm lvs on a cinder volume, and a vgscan picks them up. You'll know its fixed when vgscan revomes the entries.

**Comment by mancdaz** [comment]
Hi @chalupaul 

Could you please give some more detailed steps in how to replicate this problem.  Other than a vgscan actually picking up the guest lvs, what are the negative effects?

Thanks
@mancdaz

**Comment by chalupaul** [comment]
to replicate: attach a volume to a guest and lvm it up. vgscan on host. 

Negative effects: In some circumstances on ubuntu where we were doing lots of volume activities at the same time, we found it was causing volume delete would fail.

**Comment by DavidWittman** [comment]
Blah... thanks for tracking this down @chalupaul. We'd seen some cases of this in the past but didn't immediately know what was causing it to happen.

That said, I think this should be the least obtrusive way to handle this issue:

``` ruby
filter = [ "r/#{node['cinder']['storage']['lvm']['volume_group']}/" ]
```

**Comment by DavidWittman** [comment]
https://github.com/rcbops-cookbooks/cinder/pull/73

**Comment by cfarquhar** [comment]
Hypervisors also pick up LVM metadata from cinder volumes attached via iSCSI.  If something happens to the cinder-volume node, it can cause instability on the hypervisor.
