### ISSUE TITLE
[openstack-monitoring] Collectd plugins create a ridiculous number of tokens 

### ISSUE THREAD

**Issue by DavidWittman** [rcbops/chef-cookbooks#521]
The [collectd plugins](https://github.com/rcbops-cookbooks/openstack-monitoring/tree/grizzly/files/default) for gathering data on OpenStack don't reuse auth tokens between checks, so there is an absurd amount of traffic/cycles/storage wasted on these checks.

There are three separate plugins (Keystone, Nova, Glance) that each run every 10 seconds. If you throw HA into the mix, the number of the tokens doubles. Also, if PKI tokens are used, the size of these tokens in the database can quickly grow out of control without scheduled events to prune the `keystone.token` table.

These checks should either re-use auth tokens, run less frequently, or not run at all.

While we're at it, `/etc/collectd/plugins/python.conf` should not be world readable as it exposes the OpenStack admin credentials to any system user.

**Comment by kaushikb** [comment]
Closing since #544 was closed.
