### ISSUE TITLE
[DE255]: Update example environment for HA

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/chef-cookbooks#525]
Please update the example environment with a working HA config. Something was changed in osops-utils and it's breaking the previously recommended environment that had only an override_attributes.vips block. Output of chef run with cookbooks from v4.1.0 tag:

[2013-08-15T00:18:11+00:00] FATAL: You have not configured a Network for the VIP.  Please set node["vips"]["config"]["10.5.178.121"]["network"]

**Comment by andymcc** [comment]
give that a go j-dizzle. Closing! Let me know if you run into issues.
