### ISSUE TITLE
[osops-utils]:escape hypens in search string in osops_search()

### ISSUE THREAD

**Issue by cbuben** [rcbops/chef-cookbooks#529]
Apologies for lack of pull request, I'd prefer to let the implementation up to the maintainer.

rcbops-cookbooks/osops-utils@70a21ce8822ce75499447f4345463913b9e6d3fc

Caveat: I'm testing with a local chef-zero server, not the real chef server as provisioned in rcbops/support-tools.  That being said, I don't think that's an issue, as I've been burned by this same problem in our in-house cookbooks.

Three nodes in a non-HA setup, built in this order.
- node1: role[single-controller]
- node2: role[single-compute]
- node3: role[single-compute]

chef-client converges node1 and node2 just fine.  When converging node3:

```
[2013-08-19T13:13:02-04:00] ERROR: Found more than 1 nova/api but vips.nova-api is not defined.

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/nova/recipes/compute.rb
================================================================================


RuntimeError
------------
Found more than 1 nova/api but vips.nova-api is not defined.


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:48:in `rcb_exit_error'
  /var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:384:in `get_lb_endpoint'
  /var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:204:in `get_access_endpoint'
  /var/chef/cache/cookbooks/nova/recipes/nova-common.rb:60:in `from_file'
  /var/chef/cache/cookbooks/nova/recipes/compute.rb:20:in `from_file'
```

node1 is definitely supposed to be running nova-api, but the recipes somehow think that node2 is also running nova-api.  But this is a non-HA setup, so no vips defined, therefore puke.

After digging down into the search string being used:

```
[root@node3 ~]# grep 'Osops_sesarch Query' run2-fail.txt  | grep nova-api-os-compute
[2013-08-19T13:30:41-04:00] DEBUG: block in osops_search(): Osops_sesarch Query: roles:nova-api-os-compute AND chef_environment:grizzly
[2013-08-19T13:30:41-04:00] DEBUG: block in osops_search(): Osops_sesarch Query: recipes:nova-api-os-compute AND chef_environment:grizzly
```

So lets run the searches with knife to see what we get:

```
[root@node1 ~]# knife search node 'roles:nova-api-os-compute AND chef_environment:grizzly' -a roles
3 items found

node1:
  roles:
    single-controller
    base
    rsyslog-server
    mysql-master
    rabbitmq-server
    keystone
    keystone-setup
    keystone-api
    glance-setup
    glance-registry
    glance-api
    nova-setup
    nova-network-controller
    nova-scheduler
    nova-conductor
    nova-api-ec2
    nova-api-os-compute
    cinder-setup
    cinder-api
    cinder-scheduler
    nova-cert
    nova-vncproxy
    horizon-server
    openstack-logging
    single-network-node
    rsyslog-client

node2:
  roles:
    single-compute
    base
    rsyslog-client
    nova-network-compute
    openstack-logging
```

node2 doesn't have the role, but is being matched because the search string doesn't escape hypens (special char in solr).

This example makes it pretty clear too:

```
[root@node1 ~]# knife search node -q 'roles:nova-frobozz-compute AND chef_environment:grizzly' -a name
3 items found

node1:
  name: node1

node2:
  name: node2
```

This demonstrates that escaping produces the expected result.

```
[root@node1 osops-utils]# knife search node 'roles:nova\-api\-os\-compute AND chef_environment:grizzly' -a name
1 items found

node1:
  name: node1
```

The following diff produces the expected results.  With this applied, chef-client can successfully converge node3 and things are good.

``` diff
diff --git a/libraries/ip_location.rb b/libraries/ip_location.rb
index 8b4955f..3a3ffa8 100644
--- a/libraries/ip_location.rb
+++ b/libraries/ip_location.rb
@@ -316,8 +316,9 @@ module RCB
         break if one_or_all == :one # skip expensive searches if unnecessary
       end

-      search_string.gsub!(/::/, "\\:\\:")
-      query = "#{query_type}s:#{search_string} AND chef_environment:#{current_node.chef_environment}"
+      # escape colons and hyphens
+      escaped_search_string = search_string.gsub(/::/, "\\:\\:").gsub(/-/, "\\-")
+      query = "#{query_type}s:#{escaped_search_string} AND chef_environment:#{current_node.chef_environment}"
       debug("Osops_sesarch Query: #{query}")
       result, _, _ = Chef::Search::Query.new.search(:node, query)
       results[query_type].push(*result)
```

**Comment by claco** [comment]
@cbuben Thanks for digging into this. Ideally, we're missing a lot more than this:

http://docs.opscode.com/essentials_search.html#Search-QuerySyntax

```
A special character can be used to fine-tune a search query and to increase the accuracy of the search results.
The following characters can be included within the search query syntax, but each occurrence of a special character must be escaped with a backslash

+  -  &&  | |  !  ( )  { }  [ ]  ^  "  ~  *  ?  :  \
```

**Comment by claco** [comment]
@cbuben What knife/chef version to you have?

When I add your patch, Chef server fails with with a Bad Request error:

```
http://build.monkeypuppetlabs.com:8080/job/gate-nova-matrix/BUILD_TYPE=mini-ha-neutron,INSTANCE_IMAGE=jenkins-precise-v2,label=nova/709/consoleFull
```

I wouldn't expect that as we're doing the same exact escaping as for ::

On a local chef 11, if I try:

```
knife search node 'roles:foo\bar' 
ERROR: knife search failed: invalid search query: 'roles:foo\-bar'
```

But this works:

```
knife search node 'roles:foo\\bar'
```

Which seems to imply that the escaping needs to be doubled, or not at all for -

**Comment by cbuben** [comment]
Thanks, Christopher!  I forgot to mention this -- but in my implementation, I copied the search string because the same string instance is being used for both the recipe and role search, and therefore being mutated twice by the hyphen gsub!, resulting in a bad escape in the recipe search.  The colon one doesn't have this problem because the escaped value no longer matches the regex, where the hyphen one still does.

Here's debug output:

```
[2013-08-19T17:38:09-04:00] DEBUG: block in osops_search(): Osops_sesarch Query: roles:nova\-api\-os\-compute AND chef_environment:grizzly
[2013-08-19T17:38:09-04:00] DEBUG: block in osops_search(): Osops_sesarch Query: recipes:nova\\-api\\-os\\-compute AND chef_environment:grizzly
```

**Comment by claco** [comment]
@cbuben so.... the patch is wrong based on that output then right?

Should be:

```
escaped_search_string = search_string.gsub(/::/, '\:\:').gsub(/-/, '\\-')
```

No reason the interpolate the substitution param just to confuse us more. And the hyphen sub needs two?

**Comment by cbuben** [comment]
This was with chef-zero 1.5.  I will repro with Chef Server 11.

I'm wondering if Chef 11 server does some local fixup or this isn't a tested case with chef-pedant (used to very chef-server compliance, which both chef 11 and chef-zero pass)

IME you always want:

```
knife search node 'roles:foo\-bar'
```

**Comment by cbuben** [comment]
> @cbuben so.... the patch is wrong based on that output then right?

@claco Apologies, I'm context switching too fast here.

Yes, I think your patch is incorrect.  I fetched 30cb98832316d88bb0b0e528c4ffe3e9500a6a79 and this produced the debug output I pasted above.  I initially made the same change you did, then realized the double mutation problem, but neglected to mention that in my initial issue.

> No reason the interpolate the substitution param just to confuse us more. And the hyphen sub needs two?

I'm not sure I understand.  The exact code in my patch works for me:

``` ruby
escaped_search_string = search_string.gsub(/::/, "\\:\\:").gsub(/-/, "\\-")
```

Just to be explicit in my thinking: every character we need to escape needs to be escaped by a single backslash.  But at the ruby level, in the second parameter to gsub, we need to escape the backslash as well, that's why there are two.

```
creeper:~ cbuben$ ruby -e 'puts "roles:foo\\-bar"'
roles:foo\-bar
```

Are we talking about the same thing?

**Comment by claco** [comment]
@cbuben Hit me up on freenode irc:  my nick is claco

My point was. Let's take ruby interpolation out of the code, out of the params we pass to gsub() for the sake of removing one level of confusion:

```
1.9.3p392 :001 > "foo\\-bar"
 => "foo\\-bar"
1.9.3p392 :002 > 'foo\-bar'
 => "foo\\-bar"
1.9.3p392 :004 > "foo-bar".gsub(/-/, "\\-")
 => "foo\\-bar"
1.9.3p392 :005 > "foo-bar".gsub(/-/, '\-')
 => "foo\\-bar"
```

So, these two lines are the same:

```
escaped_search_string = search_string.gsub(/::/, "\\:\\:").gsub(/-/, "\\-")
escaped_search_string = search_string.gsub(/::/, '\:\:').gsub(/-/, '\-')
```

Which is the same as:

```
knife search node 'role:my\-role'
```

which fails in my Chef 11. This works:

```
knife search node 'role:my\\-role'
```

and also

```
escaped_search_string = search_string.gsub(/::/, '\:\:').gsub(/-/, '\\-')
```

This makes me suspect that either:

  a) - does not need escaping, and that this is really a solr indexing problem
  b) - does need escaping...twice, differently than : does for reason I do not know
  c) this is a Chef version or Chef Zero issue

**Comment by claco** [comment]
@cbuben Given a fresh chef server and a few nodes with test-role-one, test-role-two, etc, and nothing on them to do with these recipes:

```
knife search node 'roles:test-role-one'
```

is the only proper way. No amount of escaping those - has any effect other than knife/bad request errors, or no results.

So, this is either chef zero returning results it shouldn't, over/under escaping something it shouldn't for search, or possibly the expanded run list (roles: vs role: in search) actually has the role in it.

What if you try role: instead of roles: in your knife search commands?

**Comment by cbuben** [comment]
@claco My first priority is to build a cluster with the exact config prescribed in rcbops/support-tools, as I would like to stop wasting your time ASAP.

I have already reproduced your results exactly with Chef 11 with isolated testing -- that is to say, escaped hypens break search.  Looks like http://docs.opscode.com/essentials_search.html needs to be updated for Chef 11.

I'll build the cluster, ensure the initial issue does not recur, and if so this issue is invalid and should be closed.

After we dispose of this issue I'll investigate search scenarios across Chef Server 10, Chef 11 and chef-zero to ensure there are no further implications.

Thanks again for your help, and sorry for the wild goose chase.

**Comment by cbuben** [comment]
@claco Confirmed this issue occurs only with chef-zero.  Cluster builds fine with real Chef 11.0.4 server.  Closing.  Thanks again for your help.

**Comment by claco** [comment]
@cbuben FYI:  https://github.com/jkeiser/chef-zero/commit/98c2f7148ccaad1af3f237094f9f664368c2a024
