### ISSUE TITLE
[DE258]: tags/v4.1.0 Deploy on Centos 6.3 - Horizon Issue

### ISSUE THREAD

**Issue by john5223** [rcbops/chef-cookbooks#530]
This only happens on Centos. 

Horizon has the message: 

Something went wrong!
An unexpected error has occurred. Try refreshing the page. If that doesn't help, contact your local administrator.

/var/log/httpd/error.log:

[Mon Aug 19 18:18:39 2013] [error] DeprecationWarning: The ADMIN_MEDIA_PREFIX setting has been removed; use STATIC_URL instead.DeprecationWarning: The SECRET_KEY setting must not be empty.DeprecationWarning: Translations in the project directory aren't supported anymore. Use the LOCALE_PATHS setting instead.DeprecationWarning: The syntax for the url template tag is changing. Load the `url` tag from the `future` tag library to start using the new behavior.

This seems to be four different errors for django. 

DeprecationWarning: The ADMIN_MEDIA_PREFIX setting has been removed; use STATIC_URL

instead.DeprecationWarning: The SECRET_KEY setting must not be empty.

DeprecationWarning: Translations in the project directory aren't supported anymore. Use the LOCALE_PATHS setting 

instead.DeprecationWarning: The syntax for the url template tag is changing. Load the `url` tag from the `future` tag library to start using the new behavior.

They say they are DeprecationWarnings (warnings), but it is under an error status in the log, and horizon is down. 

P.S. This apparently doesn't happen if you use centos in cloud servers.  (????)

**Comment by breu** [comment]
I was able to duplicate this with vanilla OpenStack CSS for horizon

I would like to verify something here:

Can you set the following variables in /etc/openstack-dashboard/local_settings and restart apache?
DEBUG = True
TEMPLATE_DEBUG = True

restart apache and visit the site again.  You should see something similar in the error log

OfflineGenerationError: You have offline compression enabled but key "f44e465a54ed0ffb185a58b3576749f0" is missing from offline manifest. You may need to run "python manage.py compress".

Run this command and see if it fixes it:

python /usr/share/openstack-dashboard/manage.py compress

I think the deprecation notices are really notices and there is a problem with how the CSS is getting laid down.

**Comment by breu** [comment]
I take that back - it was with the custom CSS... but the above question still stands :)

**Comment by john5223** [comment]
That does fix the issue. 

Changed local_settings and had to run manage.py compress, and then horizon came back up.
