### ISSUE TITLE
[DE261]: [cinder] Add RBD as a storage provider option

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#536]
Consider adding RBD as a storage provider option, even if the cookbooks don't support the setup of the ceph cluster. This allows the user of the cookbooks to setup a cluster and make use of it.

**Comment by willkelly** [comment]
We'll probably look into this in the near future

**Comment by odyssey4me** [comment]
Pull request submitted for basic implementation: https://github.com/rcbops-cookbooks/cinder/pull/74

**Comment by odyssey4me** [comment]
FYI - I've also been doing a bit of work on improving the ceph setup automation for the purpose of using it in our Openstack deployment. See the work here: https://github.com/ceph/ceph-cookbooks/pull/61

**Comment by mancdaz** [comment]
rebased pull request submitted in https://github.com/rcbops-cookbooks/cinder/pull/77

**Comment by zfeldstein** [comment]
Fixed in:

https://github.com/rcbops-cookbooks/cinder/commit/c18d60cd6cc9cbe7f11741410cb75dbf96fb4380
