### ISSUE TITLE
[DE265]: [nova-network][quantum] quantum-metadata-agent missing from quantum-network-manager role

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#540]
I think that the metadata-agent recipe may be missing from the quantum-network-manager role. I don't see any other role that has the metadata agent.

**Comment by git-harry** [comment]
@odyssey4me 

Thanks for the feedback.

@Apsu 

Was this left out from the quantum-network-manager role intentionally or does it need adding in to this/another role?

**Comment by Apsu** [comment]
@odyssey4me @git-harry The quantum-network-manager role isn't actually the role we use anymore, neither in our docs or deployments. The correct role is single-network-node.

@odyssey4me We definitely have and use the metadata-agent. I've had to solve for several combinations of subnet features, topologies and metadata access together, which we can talk about if you end up trying to use metadata on a network with a gateway.

**Comment by jcannava** [comment]
Closing as it appears resolved, but reopen if this is incorrect.
