### ISSUE TITLE
[horizon] implement password_autocomplete attribute

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#541]
For security in some deployments the requirement is to disable browser login form autocompletion. This should be enabled/disabled via an attribute and implemented into local_settings.py

``` python
# Turn off browser autocompletion for the login form if so desired.
# HORIZON_CONFIG["password_autocomplete"] = "off"
```

**Comment by zfeldstein** [comment]
addressed in:
https://github.com/rcbops-cookbooks/horizon/compare/56fbb97c813c...cb3e1f695568
