### ISSUE TITLE
[DE267]: [horizon] implement help_url attribute

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#542]
The HORIZON_CONFIG help_url should be customisable for a deployment to allow pointing at a service desk URL or knowledgebase of some kind.

``` python
'help_url': "http://docs.openstack.org",
```

**Comment by zfeldstein** [comment]
Thanks for this.. I'll put a patch in for this shortly.

**Comment by zfeldstein** [comment]
Addressed in:

https://github.com/rcbops-cookbooks/horizon/commit/56fbb97c813c1bc6b64446a635d1d82e6048d3f5
