### ISSUE TITLE
[DE268]: [horizon] implement secure cookies if service via SSL

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#543]
The following should be enabled in local_settings.py if Horizon is being served via SSL:

``` python
#CSRF_COOKIE_SECURE = True
#SESSION_COOKIE_SECURE = True
```

**Comment by git-harry** [comment]
@odyssey4me 

Thanks for the feedback, this has been added in.

https://github.com/rcbops-cookbooks/horizon/pull/121
