### ISSUE TITLE
[DE274]: [glance] cookbook assumes swift deployment in places

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#553]
For example:

https://github.com/rcbops-cookbooks/glance/blob/master/recipes/glance-common.rb#L117

should read something along the line of

``` ruby
if glance["api"]["swift_store_auth_address"].nil? && glance["api"]["default_store"]=="swift"
```

**Comment by jcannava** [comment]
Should be fixed with above merge.
