### ISSUE TITLE
[DE275]: [keystone] https scheme is all-or-nothing

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#554]
Setting the service scheme to https for keystone is currently an all-or-nothing action, but the cookbook allows you to define it differently... resulting in a broken deployment.

Ideally the keystone service should be setup in such a way that the admin/internal/public api's can each be designated to use the SSL scheme individually. But an acceptable alternative would be to have the admin URI be independant, but the service/internal URI's must be the same.

**Comment by zfeldstein** [comment]
Thanks for this, I'll work on resolving this, as well as https://github.com/rcbops/chef-cookbooks/issues/565  as they are related.

**Comment by zfeldstein** [comment]
Addressed in: 

https://github.com/rcbops-cookbooks/keystone/commit/fd4f61ba25b8a615233e85445884c543dab08a44
