### ISSUE TITLE
[DE278]: Duplicate entries in collectd mysql plugin

### ISSUE THREAD

**Issue by rpawlik** [rcbops/chef-cookbooks#557]
/etc/collectd/plugins/mysql.conf:

```
# This file autogenerated by Chef
# Do not edit, changes will be overwritten
LoadPlugin "mysql"

<Plugin "mysql">
  <Database "">
    Password "<SANITIZED>"
    User "root"
    Port 3306
    Host "<SANITIZED>"
  </Database>
  <Database "">
    Host "<SANITIZED>"
    User "root"
    Password "<SANITIZED>"
    Port 3306
  </Database>
</Plugin>
```

Code:

root@controller01:/opt/rpcs/chef-cookbooks/cookbooks# sed -n '236,270p' /opt/rpcs/chef-cookbooks/cookbooks/monitoring/providers/metric_collectd.rb

``` ruby
def mysql_metric(new_resource)
  options = {}

  [ "host", "user", "password", "port"].each do |attr|
    if new_resource.send(attr)
      options[attr.capitalize] = new_resource.send(attr)
    end
  end

  options.merge({"MasterStats" => false })

  node["monitoring"]["dbs"] ||= {}
  node.set["monitoring"]["dbs"][new_resource.db] = options

  collectd_plugin "mysql" do
    template "collectd-plugin-mysql.conf.erb"
    cookbook "monitoring"
    options(:databases => node["monitoring"]["dbs"])
    Chef::Log.info(node["monitoring"]["dbs"])
  end

  Chef::Log.error(new_resource)

  new_resource.alarms.each_pair do |alarm, thresholds|
    collectd_threshold "mysql-#{alarm}" do
      options("host_#{new_resource.host}" => {
                "plugin_mysql" => { "type_mysql_threads" => {
                    :data_source => "connected"
                  }.merge(thresholds.inject({}) { |hsh,(k,v)| hsh.merge(k=>v.to_f) })
                }})
    end
  end
end
```

Result of Chef::Log.info(node["monitoring"]["dbs"]):

> [2013-09-04T00:25:09+00:00] INFO: #<Chef::Node::Attribute @normal={...}, @current_normal={""=>{"Password"=>"<SANITIZED>", "User"=>"root", "Port"=>3306, "Host"=>"<SANITIZED>"}, nil=>{"Host"=>"<SANITIZED>", "User"=>"root", "Password"=>"<SANITIZED>", "Port"=>3306}}, @default={...}, @current_default=nil, @override={...}, @current_override=nil, @automatic={...}, @current_automatic=nil, @current_nesting_level=["monitoring", "dbs"], @auto_vivifiy_on_read=false, @set_unless_value_present=false, @set_type=nil, @has_been_read=false>

For whatever reason, it using an empty string ("") and "nil" hence the duplicate entries. This seems to happen in newer cookbook versions as well.

**Comment by zfeldstein** [comment]
Thanks for reporting this. I was able to reproduce this and will be digging on the best way to resolve this.

**Comment by zfeldstein** [comment]
addressed in:

https://github.com/rcbops-cookbooks/monitoring/commit/91607df7bf3b19f57b7dabebb0bd07610c6ece7b
