### ISSUE TITLE
[DE279]: [horizon] OPENSTACK_KEYSTONE_DEFAULT_ROLE is set to non-existent role

### ISSUE THREAD

**Issue by willkelly** [rcbops/chef-cookbooks#558]
OPENSTACK_KEYSTONE_DEFAULT_ROLE is being set to Member in our local_settings.py.  This role does not exist (it is now _member_)

https://github.com/rcbops-cookbooks/horizon/blob/master/templates/default/local_settings.py.erb#L127

**Comment by zfeldstein** [comment]
Fixed in:

https://github.com/rcbops-cookbooks/horizon/commit/af86c4bc1df2ad9db0619dd8ebff0cfe54ae77a1
