### ISSUE TITLE
[DE281]: [nova] Syntax error in nova.conf.erb partial template

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/chef-cookbooks#561]
Half-open quote at `disk_cachemodes="`

https://github.com/rcbops-cookbooks/nova/blob/master/templates/default/partials/compute-options.partial.erb#L10

**Comment by zfeldstein** [comment]
https://github.com/rcbops-cookbooks/nova/commit/a28f96da7afd98966ae07df83d15e5a9227bcb90
