### ISSUE TITLE
[DE285]: [cinder] cinder-api and cinder-scheduler restarts on every chef run even if it doesn't need to

### ISSUE THREAD

**Issue by brc** [rcbops/chef-cookbooks#566]
Services are restarted every time chef runs

**Comment by IRTermite** [comment]
Isn't that normal for config file management?  Every time Chef runs, it's restarting all services and cleaning up any configuration alterations...  Or am I missing something with this issue?  Looking for a conditional service(s) restart action?

**Comment by breu** [comment]
It is not normal to restart the services if the config files haven't changed which is the case here.

**Comment by brc** [comment]
^ yes @IRTermite only want to bounce service if the config changes, not every single time `chef-client` runs.

**Comment by brc** [comment]
Fixed in https://github.com/rcbops-cookbooks/cinder/pull/78
