### ISSUE TITLE
[DE286]: [nova] unnecessary restart of nova services due to unsorted memcached_servers list

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#567]
The memcache server list is returned unsorted, resulting in a nova.conf change almost every chef-client run... this results in unneccessary restarts of the nova services as the list of memcached servers changes.

On one run it may return something like:
memcached_servers=10.71.0.32:11211,10.71.0.28:11211,10.71.0.33:11211,10.71.0.29:11211

Whereas on another run it'll return something like:
memcached_servers=10.71.0.28:11211,10.71.0.29:11211,10.71.0.32:11211,10.71.0.33:11211

It'd be best of the conf entry would be a sorted list so that the entry doesn't change, therefore not resulting in a service restart.

**Comment by breu** [comment]
I agree that this change needs to be made and that we should make every attempt at resolving this as soon as possible.

**Comment by breu** [comment]
I am going to ask @invsblduck or @jrcloud to take a look at this one.

**Comment by brc** [comment]
gating now.

**Comment by claco** [comment]
Only half joking here. We should probably grep all of the templates in a full chef-cookbooks checkout for .each and make sure they're all sorted.

**Comment by breu** [comment]
Sounds like @claco just volunteered.

**Comment by odyssey4me** [comment]
@claco very possibly a good idea... so what were you doing for the weekend? ;)

**Comment by brc** [comment]
Fixed in https://github.com/rcbops-cookbooks/nova/pull/341
