### ISSUE TITLE
[DE287]: force_config_drive being set even though we default to 'false'

### ISSUE THREAD

**Issue by mattt416** [rcbops/chef-cookbooks#569]
If the attribute is `false`, we need to exclude writing the `force_config_drive` option to nova.conf.

**Comment by DavidWittman** [comment]
:+1:  This is the worst option ever.

**Comment by DavidWittman** [comment]
rcbops-cookbooks/nova#342

**Comment by DavidWittman** [comment]
Merged in rcbops-cookbooks/nova#342
