### ISSUE TITLE
[DE288]: [rabbitmq-openstack] which rabbitmq cookbook to use?

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#570]
The rabbitmq cookbook referenced in the .gitmodules is the rcbops version, but the rcbops version is too low and deprecated. Is there a bug there?

**Comment by breu** [comment]
Until COOK-2676 gets resolved upstream we are using our own fork of the rabbitmq cookbook to get past certain issues around rabbitmq clustering.

https://github.com/opscode-cookbooks/rabbitmq/pull/77

**Comment by odyssey4me** [comment]
Ah, so I see now that the repo is following the COOK-2676 branch of https://github.com/rcbops-cookbooks/rabbitmq instead of the master branch. Great, now I know where to point it!
