### ISSUE TITLE
[openstack-ha] adding dns host uri override breaks everything

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#574]
@mancdaz we've discussed this use-case a few times and thought we'd come to a conclusion with some of the code changes you made, but the desired result is not being achieved.

The desired end-goal is to have the public endpoints (only) be DNS names, not IP addresses.

Consider the following partial environment file:

``` json
    "vips": {
      "keystone-service-api": "192.168.4.111",
      "keystone-admin-api": "192.168.4.111",
      "keystone-internal-api": "192.168.4.111",
      "config": {
        "192.168.4.111": {
          "vrid": 12,
          "network": "public"
        }
      }
    },
    "keystone": {
      "services": {
        "service-api": {
          "uri": "http://api.lab.local:5000/v2.0"
        }
      }
    },
```

api.lab.local is an A record which referse to 192.168.4.111

This environment results in a change in /etc/haproxy/haproxy.d/vs_keystone-service-api.cfg something like the following:

```
        --- /etc/haproxy/haproxy.d/vs_keystone-service-api.cfg  2013-09-17 15:26:23.077384544 +0200
        +++ /tmp/chef-rendered-template20130920-7877-1wnuhcz    2013-09-20 13:27:08.585547711 +0200
        @@ -4,5 +4,5 @@
             option forwardfor
             option httpchk
             option httplog
        -    server keystone-service-api-1 192.168.4.62:5000 check
        -    server keystone-service-api-2 192.168.4.65:5000 check
        +    server keystone-service-api-1 api.lab.local:5000 check
```

This change to the haproxy config completely breaks access to keystone as the haproxy config for the keystone public api points to itself rather than the two back-end servers.

As I see it there are two methods to sort this out:
1. The endpoint referencing in several places needs to be changed to make sure that it returns the IP address in all cases _except_ for (only) the public keystone endpoint creation.
2. We simply introduce an optional attribute, something like "name" or "hostname" for each service. If it's present then it is only used for the keystone endpoint registration process. eg: ["keystone"]["services"]["service-api"]["name"] = "api.lab.local"

To me option two is simple, clean and much easier than refactoring the haproxy, monit, SSL endpoint and whoknowswhatelse code.

**Comment by odyssey4me** [comment]
Those three pull requests achieve the desired goal so this issue can be closed now.

**Comment by jcannava** [comment]
closing based on earlier comment from @odyssey4me
