### ISSUE TITLE
[mysql-openstack]: VIPs don't move when mysql service is stopped manually

### ISSUE THREAD

**Issue by ragsns** [rcbops/chef-cookbooks#575]
Here's my environment.

{
  "name": "rpcs",
  "description": "Environment for Rackspace Private Cloud (Grizzly)",
  "cookbook_versions": {
  },
  "json_class": "Chef::Environment",
  "chef_type": "environment",
  "default_attributes": {
  },
  "override_attributes": {
    "nova": {
      "libvirt": {
        "virt_type": "qemu"
      },
      "networks": [
        {
          "label": "public",
          "bridge_dev": "eth0",
          "dns1": "8.8.8.8",
          "dns2": "8.8.4.4",
          "num_networks": "1",
          "ipv4_cidr": "10.0.100.0/24",
          "network_size": "255",
          "bridge": "br100"
        }
      ]
    },
    "mysql": {
      "allow_remote_root": true,
      "root_network_acl": "%"
    },
    "vips": {
            "cinder-api": "192.168.210.197",
            "glance-api": "192.168.210.197",
            "glance-registry": "192.168.210.197",
            "horizon-dash": "192.168.210.197",
            "horizon-dash_ssl": "192.168.210.197",
            "keystone-admin-api": "192.168.210.197",
            "keystone-service-api": "192.168.210.197",
            "keystone-internal-api": "192.168.210.197",
            "nova-api": "192.168.210.197",
            "nova-ec2-public": "192.168.210.197",
            "nova-novnc-proxy": "192.168.210.197",
            "nova-xvpvnc-proxy": "192.168.210.197",
            "mysql-db": "192.168.210.198",
            "rabbitmq-queue": "192.168.210.199",
            "config": {
               "192.168.210.197": {
                   "vrid": 11,
                   "network": "management"
               },
               "192.168.210.198": {
                   "vrid": 12,
                   "network": "management"
               },
               "192.168.210.199": {
                   "vrid": 13,
                   "network": "management"
               }
            }
        },
    "osops_networks": {
      "nova": "192.168.210.0/24",
      "public": "192.168.210.0/24",
      "management": "192.168.210.0/24"
    }
  }
}

It looks like 192.168.210.198 transfers over to ha-controller2 properly when I shutdown ha-controller1. However, when I manually stop and start mysql it seems like the VIP does not transfer over.

root@controllerhaone:~# service mysql stop
mysql stop/waiting
root@controllerhaone:~# ps aux | grep -i mysql
root     57647  0.0  0.0  13584   928 pts/5    S+   07:47   0:00 grep --color=auto -i mysql
root@controllerhaone:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:61:ff:95 brd ff:ff:ff:ff:ff:ff
    inet 192.168.210.103/24 brd 192.168.210.255 scope global eth0
    inet 192.168.210.199/32 scope global eth0
    inet 192.168.210.198/32 scope global eth0
    inet 192.168.210.197/32 scope global eth0
    inet6 fe80::20c:29ff:fe61:ff95/64 scope link 
       valid_lft forever preferred_lft forever

I might have manually stopped earlier before verifying.

**Comment by odyssey4me** [comment]
You'll need to shut down monit, then keepalived. It's keepalived that maintains the virtual ip and monit watches the services and restarts them if they go down.

**Comment by mancdaz** [comment]
Actually, keeplived has a script for each VIP that tracks the service that should be using this VIP.  It should notice when that service goes away, and migrate the VIP.  For mysql:

https://github.com/rcbops-cookbooks/mysql-openstack/blob/master/recipes/server.rb#L254-L258

**Comment by Apsu** [comment]
This is a fundamentally broken way to check for mysqld aliveness. There are several issues here:

A) `killall $name` has subtly incorrect semantics for several valid scenarios for how mysqld may be started. If you check the manpage carefully, when you _don't_ pass a regex for process name, it attempts to match a process executing a file matching the $name passed. This may not, in fact, be the file executed, as it may be wrapped via a monitor, or be a different name, or part of a longer commandline, or other subtly broken situations.
B) This is the wrong way to begin with. For rabbit/haproxy we're making use of `service $name status`, and we can do the same with mysql.

**Comment by jcannava** [comment]
I am going to proceed with closing this issue as we have re-done a significant amount of the HA setup over the past month and it now resides in the master branch. Also see fix above for status checking.
