### ISSUE TITLE
[DE293]: [keystone] endpoint recreate does not check region

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#576]
The endpoint recreation process only checks the URL's and not the regions. It should ideally check the regions too.

**Comment by zfeldstein** [comment]
Thanks for this, I'll dig on the best way to fix, as the URL check happens in the find_value method in the helpers library, which is used by other keystone lwrps.

**Comment by claco** [comment]
I believe this should be fixed with the changes in https://github.com/rcbops/chef-cookbooks/issues/653
