### ISSUE TITLE
[DE294]: [keystone] https scheme assumes that horizon is installed on the same server

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#577]
I see that this issue will be for all other https scheme additions too, not just keystone.

If you have a node which is acting as a keystone service-api endpoint, but does not have horizon installed on it, then you'll find that you get the following error:

```
[2013-09-25T15:04:29+02:00] DEBUG: Chef::Exceptions::ResourceNotFound: resource cookbook_file[/etc/ssl/certs/keystone.pem] is configured to notify resource execute[restore-selinux-context] with action run, but execute[restore-selinux-context] cannot be found in the resource collection. cookbook_file[/etc/ssl/certs/keystone.pem] is defined in /var/chef/cache/cookbooks/keystone/recipes/keystone-ssl.rb:43:in `from_file'
[2013-09-25T15:04:29+02:00] DEBUG: Server doesn't support resource history, skipping resource report.
[2013-09-25T15:04:29+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

This is because the placement of cookbook_files in the recipes all do this:

```
notifies :run, "execute[restore-selinux-context]", :immediately
```

The execute resource restore-selinux-context is only defined in the horizon cookbook, so it can't be found.

Considering this recipe include list:

```
include_recipe "apache2"
include_recipe "apache2::mod_wsgi"
include_recipe "apache2::mod_rewrite"
include_recipe "osops-utils::mod_ssl"
include_recipe "osops-utils::ssl_packages"
```

I would think that perhaps this execute resource should be defined either in the apache cookbook or in the osops-utils cookbook?

**Comment by zfeldstein** [comment]
Merged:

https://github.com/rcbops-cookbooks/osops-utils/commit/fbdef200453dff2068e4c323c41f55fd1cf556dd

**Comment by zfeldstein** [comment]
Actually going to go the route @claco mentioned in your pull request i.e.:

http://docs.opscode.com/config_rb_client.html
enable_selinux_file_permission_fixup

Going rip all references to the restore-selinux-context execute resource and use the chef client config.

**Comment by zfeldstein** [comment]
https://github.com/rcbops-cookbooks/ceilometer/pull/12

**Comment by zfeldstein** [comment]
https://github.com/rcbops-cookbooks/glance/pull/173

**Comment by zfeldstein** [comment]
https://github.com/rcbops-cookbooks/cinder/pull/79

**Comment by zfeldstein** [comment]
https://github.com/rcbops-cookbooks/graphite/pull/38

**Comment by zfeldstein** [comment]
https://github.com/rcbops-cookbooks/horizon/pull/127

**Comment by zfeldstein** [comment]
https://github.com/rcbops-cookbooks/nova/pull/344

**Comment by zfeldstein** [comment]
https://github.com/rcbops-cookbooks/nova-network/pull/73

**Comment by zfeldstein** [comment]
https://github.com/rcbops-cookbooks/keystone/pull/145

**Comment by zfeldstein** [comment]
removed  execute se-linux restore resource (https://github.com/rcbops-cookbooks/osops-utils/pull/137) Need to rely on chef client.rb config to handle selinux context restores.
