### ISSUE TITLE
[DE295]: [keystone] VirtualHost close tag missing in template

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#578]
https://github.com/rcbops-cookbooks/keystone/blob/master/templates/default/keystone_ssl_vhost.erb#L84 should contain a closing VirtualHost tag.

**Comment by zfeldstein** [comment]
@odyssey4me  sorry about this, I missed the pending pull request, it was merged here:

https://github.com/rcbops-cookbooks/keystone/commit/9a6a7493266748be54825846a74d6bd1a02c7634
