### ISSUE TITLE
[DE296] (I think): [keystone] internal service-api does not listen on port 5000 when the public service-api is set to a different port

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#579]
Considering this as a partial environment file:

``` json
    "keystone": {
      "services": {
        "service-api": {
          "scheme": "https",
          "port": "5443"
        }
      }
    }
```

Keystone's public service-api is therefore set to listen on port 5443 with https. The resulting apache config file ends up missing the Listen directive to ensure that the internal service-api still listens on port 5000.

The solution is to insert the following at https://github.com/rcbops-cookbooks/keystone/blob/master/templates/default/keystone_ssl_vhost.erb#L66

``` ruby
Listen <%= @internal_ip %>:<%= @internal_port %>
```

**Comment by zfeldstein** [comment]
merged:

https://github.com/rcbops-cookbooks/keystone/commit/1048b8eeae61a0f4c0f0bc127e33a2d06eeeb4b9
