### ISSUE TITLE
[DE303]: [horizon] OPENSTACK_SSL_NO_VERIFY=True not respected

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#586]
Ref:
1. https://bugs.launchpad.net/django-openstack-auth/+bug/1231480
2. https://github.com/openstack/django_openstack_auth/commit/8759ad4804271d0f86eed514a8007157f44d4ba4
3. https://github.com/openstack/django_openstack_auth/commit/574e9d5f383fd8551fefcbd604e916d7bff6427c

For Grizzly this has not been resolved as it still uses python-openstack-auth 1.0.7. It'd be ideal to roll this as a patch in the Horizon cookbook.

**Comment by odyssey4me** [comment]
After trying to work with self-signed certificates in an Openstack deployment and hitting bug after bug I've decided to give up on that idea. Catering for it would be a quagmire of technical debt to carry, so don't bother. This issue may as well be closed.

**Comment by jcannava** [comment]
Closing based on @odyssey4me's earlier comment.
