### ISSUE TITLE
Nova end points not recreated after SSL enabled

### ISSUE THREAD

**Issue by zfeldstein** [rcbops/chef-cookbooks#590]
On existing installs, when changing nova endpoints to be SSL enabled the keystone DB is not updated with new URL.

**Comment by odyssey4me** [comment]
Hmm, I didn't find that to be a problem - however the endpoints in my environment were being recreated by openstack-ha.

**Comment by kaushikb** [comment]
@jrcloud  Please could add a link to the pull request ?

**Comment by claco** [comment]
@jrcloud is this still the case? And which endpoints? Just the compute endpoint?

Just wandering if this is just a matter of changing the :create to :recreate in the keystone_endpoint calls.

**Comment by claco** [comment]
Went through the various cookbooks and made sure we're doing :recreate instead of :create to pick up any endpoint changes. Reopen if borkened.

**Comment by claco** [comment]
Reopening for backport to 4.1.5

**Comment by claco** [comment]
v4.1.5 was tested for a specific upgrade and released as is. Closing.
