### ISSUE TITLE
[Keystone] Setting Public Endpoints

### ISSUE THREAD

**Issue by woodardchristop** [rcbops/chef-cookbooks#592]
Need the ability to set public endpoints that will not get overwritten. Specifically for Rightscale, they require a public IP to make api calls against. 

Example: 
keystone endpoint-list
+----------------------------------+-----------+---------------------------------------------+-----------------------------------------+-----------------------------------------+
|                id                |   region  |                  publicurl                  |               internalurl               |                 adminurl                |
+----------------------------------+-----------+---------------------------------------------+-----------------------------------------+-----------------------------------------+
| 204689cf4ce744f9a71cd708c44b14bf | RegionOne | https://10.240.0.9:8774/v2/%(tenant_id)s | http://10.240.0.9:8774/v2/%(tenant_id)s | http://10.240.0.9:8774/v2/%(tenant_id)s |
| 46c9629ab8a1472fa53b436b024b4df5 | RegionOne |       https://10.240.0.9:5000/v2.0       |       http://10.240.0.9:5000/v2.0       |       http://10.240.0.9:35357/v2.0      |
| 5b926b5e2a524e69865b782d28e920c7 | RegionOne |        https://10.240.0.9:9292/v1        |        http://10.240.0.9:9292/v1        |        http://10.240.0.9:9292/v1        |
| 62c84801bc0748559857df79777bd5b1 | RegionOne |  https://10.240.0.9:8773/services/Cloud  |  http://10.240.0.9:8773/services/Cloud  |  http://10.240.0.9:8773/services/Admin  |
| 8eb3f4e9c2dd4ed9a73d9082f6772efa | RegionOne |   http://10.240.0.9:8776/v1/%(tenant_id)s   | http://10.240.0.9:8776/v1/%(tenant_id)s | http://10.240.0.9:8776/v1/%(tenant_id)s |
+----------------------------------+-----------+---------------------------------------------+-----------------------------------------+-----------------------------------------+

Desired:

keystone endpoint-list
+----------------------------------+-----------+---------------------------------------------+-----------------------------------------+-----------------------------------------+
|                id                |   region  |                  publicurl                  |               internalurl               |                 adminurl                |
+----------------------------------+-----------+---------------------------------------------+-----------------------------------------+-----------------------------------------+
| 204689cf4ce744f9a71cd708c44b14bf | RegionOne | https://67.192.178.58:8774/v2/%(tenant_id)s | http://10.240.0.9:8774/v2/%(tenant_id)s | http://10.240.0.9:8774/v2/%(tenant_id)s |
| 46c9629ab8a1472fa53b436b024b4df5 | RegionOne |       https://67.192.178.58:5000/v2.0       |       http://10.240.0.9:5000/v2.0       |       http://10.240.0.9:35357/v2.0      |
| 5b926b5e2a524e69865b782d28e920c7 | RegionOne |        https://67.192.178.58:9292/v1        |        http://10.240.0.9:9292/v1        |        http://10.240.0.9:9292/v1        |
| 62c84801bc0748559857df79777bd5b1 | RegionOne |  https://67.192.178.58:8773/services/Cloud  |  http://10.240.0.9:8773/services/Cloud  |  http://10.240.0.9:8773/services/Admin  |
| 8eb3f4e9c2dd4ed9a73d9082f6772efa | RegionOne |   http://10.240.0.9:8776/v1/%(tenant_id)s   | http://10.240.0.9:8776/v1/%(tenant_id)s | http://10.240.0.9:8776/v1/%(tenant_id)s |
+----------------------------------+-----------+---------------------------------------------+-----------------------------------------+-----------------------------------------+

**Comment by cloudnull** [comment]
resolved in 4.1.x
