### ISSUE TITLE
[keystone] region not set appropriately in recipes/setup.rb

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#593]
Due to https://github.com/rcbops-cookbooks/keystone/commit/029329fb78e4443b6cd475a3872d2de9dfd94b82 which was an appropriate removal, keystone's setup recipe does not implement the common region attribute ["nova"]["compute"]["region"] when setting up or updating an endpoint.

Ideally this region should be included as part of the endpoint create/update.

Not having this done correctly may also cause an issue when a solution to https://github.com/rcbops/chef-cookbooks/issues/576 is found.

**Comment by claco** [comment]
Should be closed in the referenced issue.
