### ISSUE TITLE
[horizon] secure cookies implemented under incorrect circumstances

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#594]
https://github.com/rcbops-cookbooks/horizon/commit/1dee8b574f776ec1070bb149c26d37531c705b91 introduced the situation where secure cookies are implemented when the keystone endpoint scheme is https. What should actually be happening is that the secure cookies are set when Horizon's serving up the dashboard via https.

**Comment by zfeldstein** [comment]
merged:

https://github.com/rcbops-cookbooks/horizon/pull/129

**Comment by odyssey4me** [comment]
@jrcloud You missed a part ;)

**Comment by zfeldstein** [comment]
Indeed... thanks for that.
