### ISSUE TITLE
[all SSL services] allow optional SSLCertificateChainFile directive

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#595]
Currently all apache services that use SSL have the SSLCertificateFile and SSLCertificateKeyFile directives. Unfortunately without the SSLCertificateChainFile directive SSL verification will fail when there's an intermediate CA.

It would be ideal to have an optional attribute that could be set for keystone, glance, horizon, cinder, quantum, etc to ensure that an intermediate certificate could also be provided and used.

**Comment by zfeldstein** [comment]
@odyssey4me Thanks for these, i've merged the two nova PR's, I've left some feed back on the keystone PR, once that's addressed I will merge it and close this issue. Thanks!

**Comment by odyssey4me** [comment]
Thanks. :) I'm still working through Glance, then Cinder and others. Things
aren't always simple when working with apache/wsgi it seems.

On Friday, 4 October 2013, Zack Feldstein wrote:

> @odyssey4me https://github.com/odyssey4me Thanks for these, i've merged
> the two nova PR's, I've left some feed back on the keystone PR, once that's
> addressed I will merge it and close this issue. Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rcbops/chef-cookbooks/issues/595#issuecomment-25725273
> .

## 

Jesse Pretorius
mobile: +27 83 680 5492
email: jesse.pretorius@gmail.com
skype: jesse.pretorius

**Comment by zfeldstein** [comment]
@odyssey4me keystone PR merged, I"ll leave this open to add this functionality to the other services.
