### ISSUE TITLE
[nova] when using apache2/wsgi, nova debug logging does not work

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#596]
Setting nova.conf's debug=true when using apache2/wsgi has no effect. The debug logging does not show in the apache log or the nova log.

Ideally the nova debug logging should show in the original nova log, leaving the apache log purely for showing the apache access/error logs.

**Comment by odyssey4me** [comment]
OK, I've made some headway here.

Adjust /etc/apache2/wsgi/nova-api-os-compute so that the logging set lines are after the config.parse_args statement, for example:

``` python
from nova.openstack.common import log as logging
from nova import config
from paste import deploy

config_files = ['/etc/nova/api-paste.ini', '/etc/nova/nova.conf']
config.parse_args([], default_config_files=config_files)

LOG = logging.getLogger(__name__)
logging.setup("nova")

conf = config_files[0]
name = "osapi_compute"

options = deploy.appconfig('config:%s' % conf, name=name)

application = deploy.loadapp('config:%s' % conf, name=name)
```

This sends all the logging from nova to the apache vhost log file, which is ok. The trouble is that it only does that when 'SSLEngine off' in the vhost config. When 'SSLEngine on' in the vhost config the log is dead silent.

**Comment by odyssey4me** [comment]
Silly me. The log is silent because there are no queries on the service, so the wsgi hasn't bothered to load.

Setting the vhost LogLevel directive to 'error' and actually doing a query against the service makes it work.

I'll submit a PR for the wsgi config file change shortly.

**Comment by zfeldstein** [comment]
Merged:

https://github.com/rcbops-cookbooks/nova/commit/7570c908baba746f7c7046739a1fb32ff0a853a7
