### ISSUE TITLE
Setting "max_age" in nova.conf

### ISSUE THREAD

**Issue by rpawlik** [rcbops/chef-cookbooks#601]
Guys,

We need to be able to set the following option in nova.conf:

max_age=0   (IntOpt)number of seconds between subsequent usage refreshes

It goes under the policy section. This is needed to work around quota usage issues we're seeing.

**Comment by zfeldstein** [comment]
https://github.com/rcbops-cookbooks/nova/pull/352

**Comment by zfeldstein** [comment]
Merged: 
https://github.com/rcbops-cookbooks/nova/pull/352
