### ISSUE TITLE
[Monit] Process matching is almost entirely broken

### ISSUE THREAD

**Issue by Apsu** [rcbops/chef-cookbooks#603]
Monit's process monitoring capability can use either a PID file or match process commandlines via regex. In our openstack-monitoring recipes, we're passing only the simple process name (often the same as the service name, which it defaults to if the process name isn't specified). This results in monit incorrectly matching any process which has that name in its commandline, and this is actually very common in helpers and children of the actual service we care about.

I propose a modification/addition to service hashes where the 'process' value has the following patterns:
- For nova processes:
  These are dumb and have tons of subprocs with the same exact cmdline. Need to work on figuring out a solution here.
- For most other python processes:
  `"^.*python.+/path/to/process-name.*$"`
- For most other processes:
  `"^.*/path/to/process-name.*$"`

**Comment by brc** [comment]
Less broken now.
