### ISSUE TITLE
[nova-network] refactor quantum/neutron into its own cookbook

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#611]
I think that it would be pertinant to refactor quantum-neutron into its own cookbook rather than keep it mixed up with nova-network. This would simplify the recipes dramatically and prepare for a future that no longer has nova-network.

It may also be useful to actually have openvswitch in its own cookbook so that it could be used by nova-network, quantum/neutron and can be included in the early stages of a host build for the purposes of setting up [utility networks](https://github.com/rcbops/chef-cookbooks/issues/492#issuecomment-24377365) (eg: api network, san network, etc).

**Comment by jcannava** [comment]
@odyssey4me We agree and have this worked planned for later this year. We are treating it as a feature/enhancement so I am going to close this issue.
