### ISSUE TITLE
Issue with keystone on ha-controllers

### ISSUE THREAD

**Issue by jvervlied** [rcbops/chef-cookbooks#612]
It seems there is an issue with the HA controllers and keystone in a HA setup.

My servers are configured with eth0 public on a 10.0.0.0/22 network  and eth1 being a private 172.16.0.0/24 network.

Here is my environment.

```
{
  "name": "smartp",
  "description": "Smart Platform Openstack envrionment",
  "cookbook_versions": {
  },
  "json_class": "Chef::Environment",
  "chef_type": "environment",
  "default_attributes": {
  },
  "override_attributes": {
    "developer_mode": false,
    "monitoring" : {
      "metric_provider" : "collectd",
      "procmon_provider" : "monit"
    },
    "glance": {
      "image_upload": true,
      "images": ["cirros", "precise"]
    },
    "nova": {
      "ratelimit" : {
        "api" : { "enabled" : true },
        "volume" : { "enabled" : true }
      },
      "libvirt": { "virt_type": "qemu" },
  "network": {
    "provider": "quantum"
  },
      "networks": {
        "public": {
          "label": "public",
          "ipv4_cidr": "10.0.0.0/22",
          "bridge": "br100",
          "bridge_dev": "eth0",
          "dns1": "10.0.1.10",
          "dns2": "8.8.4.4"
        },
        "private": {
          "label": "private",
          "ipv4_cidr": "172.16.101.0/24",
          "bridge": "br101",
          "bridge_dev": "eth1",
          "dns1": "8.8.8.8",
          "dns2": "8.8.4.4"
        }
      }
    },
    "mysql": {
      "allow_remote_root": true,
      "root_network_acl": "%"
    },
    "osops_networks": {
      "nova": "172.16.0.0/24",
      "public": "10.0.0.0/22",
      "management": "172.16.0.0/24"
    },
    "quantum": {
      "ovs" : {
        "network_type": "gre"
      }
    },
    "vips": {
            "rabbitmq-queue": "172.16.0.11",
            "horizon-dash": "10.0.2.55",
            "horizon-dash_ssl": "10.0.2.55",
            "keystone-service-api": "10.0.2.55",
            "keystone-admin-api": "172.16.0.12",
            "keystone-internal-api": "172.16.0.12",
            "nova-xvpvnc-proxy": "172.16.0.12",
            "nova-api": "10.0.2.55",
            "nova-ec2-public": "10.0.2.55",
            "nova-novnc-proxy": "10.0.2.55",
            "cinder-api": "172.16.0.12",
            "glance-api": "10.0.2.55",
            "glance-registry": "10.0.2.55",
            "swift-proxy": "172.16.0.12",
            "quantum-api": "10.0.2.55",
            "mysql-db": "172.16.0.13",
            "config": {
                "172.16.0.11": {
                    "vrid": 1,
                    "network": "management"
                },
                "10.0.2.55": {
                    "vrid": 2,
                    "network": "public"
                },
                "172.16.0.12": {
                    "vrid": 3,
                    "network": "management"
                },
                "172.16.0.13": {
                    "vrid": 4,
                    "network": "management"
                }
            }
    }
  }
}
```

The issue I am running into is that the HA proxy config for vs_keystone_service_api is listening on the proper VIP. It has the backend on the wrong interface. it is telling the service to look for keystone on the 10.0.0.0/22 interface, but keystone is listening on the 172.16.0.0/24 interface

Here is the HA proxy config, note the service check lines

```
root@controller1:/etc# cat /etc/haproxy/haproxy.d/vs_keystone-service-api.cfg 
listen keystone-service-api 10.0.2.55:5000
    mode http
    balance roundrobin
    option forwardfor
    option httpchk
    option httplog
    server keystone-service-api-1 10.0.1.106:5000 check 
    server keystone-service-api-2 10.0.1.111:5000 check 
```

Here is the keystone.conf file showing it is listening on another IP, this is the same on the other controller node

```
root@controller1:/etc/keystone# head -20 keystone.conf 
# This file autogenerated by Chef
# Do not edit, changes will be overwritten
[DEFAULT]
# A "shared secret" between keystone and other openstack services
admin_token = vWCwUK0urOjlo5QQGw1G

# The IP address of the network interface to listen on
bind_host = 172.16.0.1

# The port number which the public service listens on
public_port = 5000

# The port number which the public admin listens on
admin_port = 35357
```

It seems that this will work properly in a non-HA scenario because in keystone-common.rb it sets the bind_host to 0.0.0.0, but otherwise it pulls it from ks_admin_bind["host"]

This is binding keystone to the internal interface only, therefore they ha-proxy config cannot talk to keystone and it's now broken. I'm not sure if this should be fixed in the keystone or the haproxy configs.

**Comment by willkelly** [comment]
We've had quite a few fixes along these lines lately.

Could you retest against master and let us know if you are still running into issues?

**Comment by willkelly** [comment]
Just a word of warning!  Master is now running havana packages and should not be used in production yet.  Upgrades are probably still a little broken (waiting on upstream package fixes to make the process more smooth).  If this is a production cluster, we will be pulling a lot of these changes into the 4.1 branch shortly, which will continue to run grizzly packages.

**Comment by jcannava** [comment]
Please let us know if this problems persists, 4.1.3 will be release shortly if you would like to test on grizzly.

**Comment by treliss** [comment]
This issue is still present in v4.2.2 (Havana).

The keystone.conf sets the bind_host to the private IP, but the public_endpoint lists the public IP and I have the haproxy vip set to the public IP.

In Havana I believe it should be using the public_bind_host and admin_bind_host options.  The [DEFAULT]/bind_host has been deprecated.  But either way, it doesn't work when using HA and separate management/public networks.
