### ISSUE TITLE
openstack-dashboard config file for httpd on centos is named wrong

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#615]
The cookbooks are laying the apache config in /etc/httpd/conf.d as openstack-dashboard, and the apache config in conf/httpd.conf is expecting a .conf

Include /etc/httpd/mods-enabled/_.load
Include /etc/httpd/mods-enabled/_.conf

Include /etc/httpd/conf.d/*.conf

Either we need to change the include or laydown the config correctly

**Comment by jacobwagner** [comment]
This is for the 4.1.3 tag

**Comment by breu** [comment]
I'll take a look at it.

**Comment by cloudnull** [comment]
Fixed in 4.2.0 and 4.1.3(master)
