### ISSUE TITLE
[nova] disk_cachemodes should be a list, not a string

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#618]
As I understand the documentation at http://docs.openstack.org/grizzly/openstack-compute/admin/content/hypervisor-configuration-basics.html the nova.conf disk_cachemodes option should be a list, not a string.

ie `disk_cachemodes=["file=none", "block=writeback", "network=writethrough"]`

Currently the cookbooks implement it as a string which limits it to only one setting.

I suggest that the attribute is set as an array and that the recipe/template loops through the elements of the array to populate them correctly.

**Comment by brc** [comment]
fixed in https://github.com/rcbops-cookbooks/nova/pull/362
