### ISSUE TITLE
centos ha failover

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#621]
I have already done a lot of troubleshooting with Evan on this issue

When killing keepalived on a controller, the vips succeed in moving to the second controller, but the services dont drop ports correctly causing issues with rabbitmq, mysql, and haproxy.

From what I have seen, there is an issue in iptables not correctly removing rules and the src hints arent working.

**Comment by jacobwagner** [comment]
https://github.com/rcbops/chef-cookbooks/issues/575#issuecomment-26442909

**Comment by Apsu** [comment]
This is terribad. Omgherd! Working on feexing it. The local route src hint approach does not seem to behave exactly right, and I'm not sure precisely why yet. I have lots of details but won't bore anyone until/unless I can't fix it.

**Comment by cloudnull** [comment]
fixed in newer HA deployments.
