### ISSUE TITLE
iptables rules for mysql/rabbitmq are getting duplicated - HighAvailability

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#629]
Iptables rules are not getting purged correctly and are creating multiple of the same rules in the nat chain

https://gist.github.com/jacobwagner/7140123

I was seeing this on the initial 4.1.3 testing and Evan was working on a fix but it doesnt seem to have gotten merged

**Comment by kaushikb** [comment]
Fixed as of 849bc5dbfba6e9ba75811c594456a9a1b8f30f50
