### ISSUE TITLE
[keepalived] update_route.sh relies on iptables being present, but it may not be installed

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#632]
I discovered this during an upgrade last night - while the keepalived update_route.sh script uses iptables, there is no guarantee that iptables is actually installed.

The recipe should ensure that iptables is installed if the update_route.sh script is pushed to the client.

**Comment by brc** [comment]
fixed in https://github.com/rcbops-cookbooks/keepalived/pull/20
