### ISSUE TITLE
RabbitMQ failing to upgrade on controllers for 4.1.2 to 4.1.3

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#634]
For upgrades, rabbit is failing to download and install the new 3.1.5 package

https://gist.github.com/jacobwagner/7160162

**Comment by breu** [comment]
What version of rabbitmq-server is installed on the box before the upgrade?

**Comment by jacobwagner** [comment]
this is a update procedure issue that i will file for docs
