### ISSUE TITLE
[mysql] /etc user:group being set to mysql:mysql on CentOS and RHEL 6.4 deployment

### ISSUE THREAD

**Issue by jameswthorne** [rcbops/chef-cookbooks#636]
On CentOS and RHEL 6.4, **/etc** user:group is being changed to **mysql:mysql** when the **single-controller** or **ha-controller#** roles are used.

I believe this occurs because the cookbooks assume the Enterprise Linux mysql packages will lay down the **/etc/mysql** directory, but they do not. On Ubuntu, the mysql packages _do_ lay down the **/etc/mysql** directory. Consequently, on CentOS and RHEL, the mysql variables in the cookbooks are being set to **/etc** instead of **/etc/mysql**.

I believe the logic for this process begins on **line 100** in **chef-cookbooks/cookbooks/mysql/recipes/server.rb**.

**Comment by claco** [comment]
This is indeed an issue with the upstream cookbook for mysql and a ticket has been opened upstream.

https://tickets.opscode.com/browse/COOK-3881

**Comment by claco** [comment]
Also reported in swift-private-cloud: https://github.com/rcbops-cookbooks/swift-private-cloud/issues/214

**Comment by claco** [comment]
Closing. This is fixed in master as it uses the newer upstream mysql book. Havana/4.2.0rc are locked to an older version. As far as I know, this doesn't cause any immediate issues and will likely be merged in a 4.2.1 release.
