### ISSUE TITLE
RabbitMQ Cluster Restart Order 

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#648]
As stated in the HA testing scenerios issue. When a rabbitmq cluster goes down it must be brought up in the reverse order that it went down or it will fail to start

https://gist.github.com/jacobwagner/ac88fbd2f4847e214ada

Step to recreate this are located here

https://github.com/rcbops/chef-cookbooks/issues/626

**Comment by breu** [comment]
Hi @jacobwagner 

Referencing https://github.com/rcbops/chef-cookbooks/issues/626 again for documentation sake.

Unfortunately, there isn't a way around this.   When you have two nodes (nodeA and nodeB) and shutdown nodeA and then nodeB, nodeB must be the first server to be started.  The reason behind this is that while nodeA was down, nodeB may have received messages that were not sync'd to other nodes.  Therefore, if you were to get nodeA running before nodeB was back online then your queues may be unsynced and have different messages.  The only solution is to restart the rabbitmq nodes in the reverse order they were stopped.

Running with more than two rabbitmq nodes would certainly reduce the chance that this event would occur however it just mitigates the problem slightly and does not resolve it.

Unfortunately this is not solved in rabbitmq 3.x and likely won't be.
