### ISSUE TITLE
Need attribute for notification_driver

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/chef-cookbooks#651]
Already done for quantum in #637, also needed for nova, glance, any others that use the notifications subsystem.

**Comment by cloudnull** [comment]
I have implemented a fix for this in my local banch of the cookbooks but I am not going to PR them at this time into master until after our release, next week.  In the mean time you can checkout the cookbooks from https://github.com/cloudnull

Here are the cookbooks I added the feature to:
- https://github.com/cloudnull/nova-network-cookbook nova-network
- https://github.com/cloudnull/nova-cookbook nova
- https://github.com/cloudnull/heat-cookbook heat
- https://github.com/cloudnull/cinder-cookbook cinder
- https://github.com/cloudnull/ceilometer-cookbook ceilometer
- https://github.com/cloudnull/keystone-cookbook keystone

The branch is "notification_driver".

**Comment by cloudnull** [comment]
closing issue , all commits merged to master
