### ISSUE TITLE
[Horizon] On Centos HA, when accessing the vip for horizon, httpd returns a Internal Server error

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#652]
https://gist.github.com/jacobwagner/006f908aad9a4ecdba80
http://i40.tinypic.com/neeyja.png

This is directly after a fresh build. Log and config in gist

**Comment by willkelly** [comment]
The centos package is updating permissions on /etc/openstack-dashboard, which causes terribles.  Working on a fix.

**Comment by willkelly** [comment]
https://github.com/rcbops-cookbooks/horizon/pull/144
