### ISSUE TITLE
On failover, compute node times out waiting for rpc response, conductor

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#654]
https://gist.github.com/jacobwagner/f7629becbed54bd63a8f

Only seeing this behavior on Centos.

**Comment by jacobwagner** [comment]
If i restart nova conductor on the box with the vips, then restart compute all is well in the world

**Comment by kaushikb** [comment]
fixed as of 849bc5dbfba6e9ba75811c594456a9a1b8f30f50
