### ISSUE TITLE
osops networks

### ISSUE THREAD

**Issue by rpawlik** [rcbops/chef-cookbooks#656]
```
"osops_networks": {
  "nova": "10.240.0.0/24",
  "public": "10.240.0.0/24",
  "management": "10.240.0.0/24"
}
```

Can you all please let me know what each of these attributes do? For example, if I set those to different networks, what services will be impacted? We've had several customers ask this question but their use is not clearly defined.

**Comment by klevenstein** [comment]
There's an update in the next version of the user guide that breaks down which services go with which network.
