### ISSUE TITLE
RabbitMQ Queues left over

### ISSUE THREAD

**Issue by cjoelrun** [rcbops/chef-cookbooks#661]
After an ungraceful failure of rpcdaemon queues will stick around and
continue growing.

```
rpcdaemon-dhcp_4ab4261e-d8ff-4c05-8443-b91809251418     20931
rpcdaemon-dhcp_6215667f-8d5a-4b92-854c-e99d4729e00f     20931
rpcdaemon-dhcp_cb4dccaa-bda9-4e98-8b48-f5909e143044     0
rpcdaemon-l3_9324e1f4-2387-4ebe-97c0-ee8d2140433c       20931
rpcdaemon-l3_b48ee6d8-bee4-4e47-8ac4-da4807cd7e36       20931
rpcdaemon-l3_cb5ee73f-f411-415f-b0e3-8a1a5af2235a       0
```

Despite the queues having no subscribers when the node comes back
online the queues stick arounnd

It's suspected because the queues did not receive a proper termination
signal they don't auto-delete.

**Comment by jacobwagner** [comment]
I am currently seeing this in 4.2.0 tag, it is persisting on the ha-proxy vip per neutron

ESTAB      0      5566        198.101.133.159:46067      198.101.133.159:9696   timer:(persist,16sec,14) users:(("rpcdaemon",3619,9)) ino:217895 sk:ffff8805d589f680

**Comment by rpedde** [comment]
Yeah, it actually _has_ a consumer stuck in a persist state.  Apsu has a fix for this that may or may not make it into 4.1.3/4.2.1.  If not, then the only solution is to wait.  They should eventually time out... not sure how long it zero-window probes before recycling the connection though.  Apsu probably knows.

**Comment by Apsu** [comment]
"Too long", is how long. It's unfortunate and a little terrible, and not eminently tunable either. I expect to have a testable branch for the fix in my fork by tonight or tomorrow. I'll update you when/if.

**Comment by jacobwagner** [comment]
verfied fixed on Precise

```
rpcdaemon-dhcp_5366deaf-46df-4f9d-8df0-9007969b565f 0
rpcdaemon-dhcp_ffb1f5db-81c7-45e5-b79f-1bcba73b4087 0
rpcdaemon-l3_341bab3b-a956-4310-bfab-c8b78de98b6c   0
rpcdaemon-l3_5bf05b5e-c13a-4dd9-8ae2-680c92c7fbae   0
```

**Comment by jacobwagner** [comment]
Verfied fixed on Centos

```
reply_fb7369d3c9d9429990cd162f877b664d  0
rpcdaemon-dhcp_9a1dbc70-dd4e-4de7-80ef-886f33b1db6d 0
rpcdaemon-l3_ace9d192-9230-457f-a4a7-5c7aa26ab81f   0
scheduler   0
```
