### ISSUE TITLE
RedHat Monit restart

### ISSUE THREAD

**Issue by cjoelrun** [rcbops/chef-cookbooks#669]
Chef attempts to restart the monit service using the reload command. 
Reload for monit is not a supported option on redhat. 
You have to use restart.

Found by Jake Briggs in support

**Comment by claco** [comment]
I use a different monit book outside of work. We can probably get the relevant brainbits from  here:  https://github.com/claco/chef-monit/blob/master/recipes/default.rb#L34

**Comment by claco** [comment]
Curious to see if this is an issue in 4.1.3 as well?
