### ISSUE TITLE
rpcdaemon isnt starting on ubuntu for fresh installs

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#672]
https://gist.github.com/jacobwagner/0d9a3ede8a3a3d5d0c1b

To recreate: install ha with quantum on precise, check for any process with rpcdaemon, also check the log, it will look like the above gist

This causes routers and networks to not be properly scheduled for creation on either controller

**Comment by cjoelrun** [comment]
Problem exists on centos as well
Monit not configured to monitor rpcdaemon:
    # This file autogenerated by Chef
    # Do not edit, changes will be overwritten
    check process rpcdaemon matching "^((/usr/bin/)?python\d? )?(/usr/bin/)?rpcdaemon\b"
      start program = "/sbin/service  start"
      stop program = "/sbin/service  stop"
      if 5 restarts within 5 cycles then timeout

**Comment by cjoelrun** [comment]
On Centos: Rpcdaemon started on one of the nodes and crashed on the other. Scheduled subnets, but never scheduled router. Crashed RPCDaemon never restarted because of monit issue above.

**Comment by brc** [comment]
This bug was due to missing attributes in the `nova-network` cookbook (where rpcdaemon is located) for the recipe in `openstack-monitoring`.  It was fixed in `master`.  Will's merge above should fix it!

**Comment by jacobwagner** [comment]
This has been fixed, verified by QE
