### ISSUE TITLE
Keepalived reload does not run notify.sh, causing keepalived to not properly load configs

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#677]
When running an upgrade from 4.1.2 to 4.1.3, the vips are not proplery getting config'd due to the cookbooks using kepalived reload, which doesnt use notify.sh which in turn doesnt properly load the vrrp conf files causing failures to bring the vips up inside the net namespaces.

https://gist.github.com/jacobwagner/4696b47822e2b9cfa81f

This is causing multi failures on the chef-client run

**Comment by breu** [comment]
All three of these pull requests should resolve this issue.

**Comment by breu** [comment]
@willkelly backport these when they gate

**Comment by jacobwagner** [comment]
They didnt, reopening!

**Comment by jacobwagner** [comment]
Update: So it seems like keepalived is not the problem (at least all the problem) but the fact that ha-proxy is changing the keystone-api bind to the loopback ip, then attempts to update the keystone endpoints, but the conf has changed.

https://gist.github.com/jacobwagner/094ace0ddbab9d9bca7d

Also it looks like keepalived is restarting 50 million times, which just seems bad

It seems like when the chef-client run fails and runs ha-proxy restart, then the next chef-client runs successfully.

**Comment by jacobwagner** [comment]
This also only seems to be the case for when haproxy updates the vs_keystone-admin-api.cfg. all other configs seems to go through with no issues

**Comment by breu** [comment]
Oops

**Comment by cloudnull** [comment]
QE to review. @jacobwagner @cjoelrun @xeregin

**Comment by claco** [comment]
Closing. Covered by new QE workflow.

**Comment by xeregin** [comment]
Performed HA burn ins successfully. Verified that this should not be an issue.

**Comment by cjoelrun** [comment]
```
! VRRP Configuration file for keepalived
! This file autogenerated by Chef
! Do not edit, changes will be overwritten

vrrp_instance VI_10_127_101_67 {
  interface mgmt
  virtual_router_id 12
  state BACKUP
  priority 100
  track_script {
    haproxy
  }

  notify_master "/etc/keepalived/notify.sh haproxy mgmt 10.127.101.67 169.254.123.1 10.127.101.12"
  notify_backup "/etc/keepalived/notify.sh del mgmt 10.127.101.67 169.254.123.1 10.127.101.12"
  notify_fault "/etc/keepalived/notify.sh del mgmt 10.127.101.67 169.254.123.1 10.127.101.12"
  notify_stop "/etc/keepalived/notify.sh del mgmt 10.127.101.67 169.254.123.1 10.127.101.12"
```
