### ISSUE TITLE
Service not being restart by chef-client

### ISSUE THREAD

**Issue by cjoelrun** [rcbops/chef-cookbooks#679]
After upgrading it was assumed that chef-client would restart all the service.
This is not true. Controller2's services are still down after chef-client run.

Starting the services seems to make things go. Besides that, all the vips moved over nicely.

Services were stopped using monit stop service_name

**Comment by breu** [comment]
We intentionally don't start services that are already down. The reason being that we don't want to restart services that have been intentionally shut off by the user for any number of reasons.  

If you stop them with monit I would suggest starting them with monit after the upgrade.

**Comment by willkelly** [comment]
We'll need to make sure to doc this properly in the upgrade process for HA configs.
