### ISSUE TITLE
Remove previous vips

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#682]
Doing a 4.2.0 to 4.2.1 upgrade failes to remove the vip for haproxy from the lo interface

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet 198.101.133.156/32 scope global lo
    inet 169.254.123.1/30 scope global lo
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever

**Comment by jacobwagner** [comment]
I have a feeling that this cannot be fixed, should we just doc it and close?

**Comment by klevenstein** [comment]
This thing is doc'd under Known Issues in the Release Notes, along with a workaround.

**Comment by jacobwagner** [comment]
Since this wont be fixed this release closing
