### ISSUE TITLE
openvswitch kernel panic thunder from down under

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#689]
https://gist.github.com/jacobwagner/0acfdd64900457ec8dc5

root@qa-precise-pool836:~# apt-cache policy openvswitch-datapath-dkms
openvswitch-datapath-dkms:
  Installed: (none)
  Candidate: 1.10.2-0ubuntu2~cloud0
  Version table:
     1.10.2-0ubuntu2~cloud0 0
        500 http://ubuntu-cloud.archive.canonical.com/ubuntu/ precise-updates/havana/main amd64 Packages
     1.4.0-1ubuntu1.5 0
        500 http://archive.ubuntu.com/ubuntu/ precise-updates/universe amd64 Packages
     1.4.0-1ubuntu1 0
        500 http://archive.ubuntu.com/ubuntu/ precise/universe amd64 Packages

**Comment by brc** [comment]
For anyone troubleshooting this, the DKMS package currently installed is named `openvswitch-datapath-lts-raring-dkms`:

```
duck@infra1:~$ apt-cache policy openvswitch-datapath-lts-raring-dkms
openvswitch-datapath-lts-raring-dkms:
  Installed: 1.9.0-0ubuntu1~ubuntu12.04.1
  Candidate: 1.9.0-0ubuntu1~ubuntu12.04.1
  Version table:
 *** 1.9.0-0ubuntu1~ubuntu12.04.1 0
        500 http://mirror.rackspace.com/ubuntu/ precise-updates/main amd64 Packages
        100 /var/lib/dpkg/status
```

Notice the output in the post above is: 

```
Installed: (none)
```

(for the wrong package name)

Brett

**Comment by jacobwagner** [comment]
Just saw this happen in 4.1.3. Kernel panic'd when i scheduled a instance. Router and subnets scheduled fine, but when I scheduled an instance the box with the router and dhcp agents crashed. I am not seeing this on centos.

The build has been left alive and will be

http://build.monkeypuppetlabs.com:8080/job/autotest-precise-ha/184/console

Also as a foot note, this happened on a completely different set of boxes then when I saw it the first time

**Comment by brc** [comment]
fix is gating https://github.com/rcbops-cookbooks/nova-network/pull/96

**Comment by brc** [comment]
Merged.  Handed to QE. <-- lies. PRs soon to 4.2/4.1rcs <-- Imposter.

**Comment by jacobwagner** [comment]
Verified Fixed by QE
