### ISSUE TITLE
[openstack-monitoring] Ceilometer not being monitored

### ISSUE THREAD

**Issue by claco** [rcbops/chef-cookbooks#693]
Ceilometer is completely missing from monit monitoring sayeth @rackerjoe

**Comment by cloudnull** [comment]
fixed with commits https://github.com/rcbops-cookbooks/ceilometer/commit/f4da027403fdd6371b1423899dab9f1a60db5169 and https://github.com/rcbops-cookbooks/openstack-ha/commit/382c02a1788a2beadfcaf8241349afedc87bf573
