### ISSUE TITLE
failed to install rpcdaemon on upgrade from 4.1.2 to 4.1.3

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#697]
https://gist.github.com/jacobwagner/214f2959743131e0e95f

**Comment by claco** [comment]
Related most likely:  https://github.com/rcbops-cookbooks/nova-network/commit/0534821c7841b35feb355782d177060d1123228d

**Comment by jacobwagner** [comment]
fails the first run on chef-client (when it gets that far on an upgrade), succeeds second time.

seeing on both controllers

**Comment by jacobwagner** [comment]
Verified fixed by QE
