### ISSUE TITLE
[nova-network] Possible L3 Agent Regression

### ISSUE THREAD

**Issue by claco** [rcbops/chef-cookbooks#699]
When merging v4.1.3rc for release into grizzly, the following diff is present. It appears that this commit was merged form master but lost in the creation of v4.1.3rc

Reverting this code from the v4.1.3rc -> grizzly merge and marking this as a possible regression from v4.1.2/grizzly.

/cc @odyssey4me

https://github.com/rcbops-cookbooks/nova-network/commit/953d694e32b39e5674b838d01d8944ccb9a318a1

```
diff --git a/recipes/quantum-l3-agent.rb b/recipes/quantum-l3-agent.rb
index 1ce9f5c..b3c5eca 100644
--- a/recipes/quantum-l3-agent.rb
+++ b/recipes/quantum-l3-agent.rb
@@ -52,6 +52,21 @@ execute "create external bridge" do
   not_if "ovs-vsctl show | grep \"Bridge #{node["quantum"]["ovs"]["external_bridge"]}\""
 end

+if node['quantum']['ovs'].has_key?('external_interface') and not node['quantum']['ovs']['external_interface'].empty?
+  Chef::Log.info("External interface set to #{node['quantum']['ovs']['external_interface']}.")
+  if node['network']['interfaces'].has_key?(node['quantum']['ovs']['external_interface'])
+    execute "add external interface to external bridge" do
+      command "ovs-vsctl add-port #{node['quantum']['ovs']['external_bridge']} #{node['quantum']['ovs']['external_interface']}"
+      action :run
+      not_if "ovs-vsctl iface-to-br #{node['quantum']['ovs']['external_interface']}"
+    end
+  else
+    Chef::Log.warn("Interface #{node['quantum']['ovs']['external_interface']} does not exist!")
+  end
+else
+  Chef::Log.warn("No external interface is set.")
+end
+
 ks_admin_endpoint =
   get_access_endpoint("keystone-api", "keystone", "admin-api")
 quantum_info =
```

**Comment by jacobwagner** [comment]
Im not seeing this code in any of the grizzly branches or tags. What issue did this fix that we could regress on?

**Comment by claco** [comment]
Yeah, it went missing from 4.1.2 -> 4.1.3 because of the merging shenanigans when we started havana. We opted to leave it out at the end of the rc rather then reintroduce it since it wasn't tested in the rc. Given all of the testing in 4.1.4, I say it's safe to close this.

**Comment by breu** [comment]
per @Apsu this was removed on purpose.  We made a decision to not have the chef cookbooks put ports into OVS bridges.
