### ISSUE TITLE
OpenStack connections timeouts

### ISSUE THREAD

**Issue by cjoelrun** [rcbops/chef-cookbooks#700]
OpenStack service timeouts cannot be configured. It's possible during failure for an OpenStack client to remain connected to a failed service for a long duration.

Over time the connection should timeout but this length is sometimes more than is desired.

A fix is to restart the service that is holding on to the connection 
ex: service openstack-nova-compute restart
...or
Wait for the connection to close over time

**Comment by breu** [comment]
can you supply more information on this?  looking at you @jacobwagner

**Comment by jacobwagner** [comment]
Closing, Was not seeing this issue in v4.1.4 testing, all connections were properly terminating
