### ISSUE TITLE
[openstack-ha] nova metadata service not load balanced

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#705]
Note: I'm using Grizzly terminology here. I know that Quantum is renamed to Neutron from Havana onwards - no smartass comments. ;)

The Quantum Metadata Proxy relies on access to the Nova Metadata Service which listens on the Nova API node on port 8775. The host in particular is discovered by doing an endpoint search in the metadata agent recipe. The result is the nova api virtual IP, but unfortunately the openstack-ha recipe does not seem to implement a load balancer for the service running on port 8775, so all Quantum Metadata Proxy efforts fail with an error something like the below in /var/log/quantum/metadata-agent.log

```
2013-12-10 10:28:03    ERROR [quantum.agent.metadata.agent] Unexpected error.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/quantum/agent/metadata/agent.py", line 88, in __call__
    return self._proxy_request(instance_id, req)
  File "/usr/lib/python2.7/dist-packages/quantum/agent/metadata/agent.py", line 138, in _proxy_request
    body=req.body)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1444, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1196, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1132, in _conn_request
    conn.connect()
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 798, in connect
    raise socket.error, msg
error: [Errno 111] ECONNREFUSED
```

The service on port 8775 needs to be included in the load balancing!

**Comment by odyssey4me** [comment]
Note that the standard haproxy httpchk causes the nova-api-metadata service to return an HTTP400 result code, causing haproxy to consider the service down. For my temporary workaround I used the following configuration for the haproxy virtual server:

```
listen nova-api-metadata 10.71.0.44:8775
    mode http
    balance roundrobin
    option forwardfor
    option httpchk
    option httplog
    http-check expect rstatus 400
    server nova-api-metadata1 10.71.0.28:8775 check
    server nova-api-metadata2 10.71.0.29:8775 check
```

This tells haproxy to expect the 400 response and consider it to be OK. There may be a way to make the check send a more appropriate request, but this will do for me as a temporary workaround.

**Comment by breu** [comment]
@odyssey4me did you try using config-drive as a workaround as well?

**Comment by odyssey4me** [comment]
@rackerjoe I haven't. While config-drive is awesome and can facilitate a lot of options, it expects that the image being booted is instrumented to use it. We can't guarantee that. Ensuring that the metadata service is active and available is backwards compatible.

**Comment by breu** [comment]
@odyssey4me True however newish cloud-init uses the config drive which is awesome if you can use it.

**Comment by odyssey4me** [comment]
@rackerjoe I've just caught onto the use-case that makes it especially useful for metadata - when you disable DHCP on the instance subnet. In a standard metadata agent config it uses the DHCP server to serve up the metadata, which falls flat when you disable DHCP for the subnet.

I'm game for implementing both the metadata load balancing and the forcing of config-drive with the basic metadata configuration. That way both options are covered.

**Comment by brc** [comment]
I'm going to try and pick up the patch for this one.  I will leave config drive work separately for the backlog.

**Comment by breu** [comment]
config drive is already enabled in the cookbooks and can be specified on the command line when booting a new instance.

```
nova boot <blah blah blah> --config-drive=true <blah blah blah>
```

**Comment by zfeldstein** [comment]
@invsblduck are you working on this, if so what is your ETA?

**Comment by breu** [comment]
@odyssey4me Interesting.  In my testing I can't get a 400 from the metadata service with the following:

```
listen nova-metadata 169.254.123.1:8775
    mode http
    balance roundrobin
    option forwardfor
    option httpchk
    option httplog
    server nova-metadata-1 192.168.0.1:8775 check
    server nova-metadata-2 192.168.0.5:8775 check
```

**Comment by breu** [comment]
We are adding a new vips entry

https://github.com/invsblduck/openstack-ha/blob/ae5aebfd27d8ac67afaf5a7f5c127e6d27c386ad/attributes/default.rb#L84-L93

**Comment by odyssey4me** [comment]
@rackerjoe That is interesting. I'll have to take a closer look at our setup to see why I'm getting 400 result codes. :/

Meanwhile, I see the merges so the issue is closable in my view. Thanks. :)

**Comment by breu** [comment]
@odyssey4me This feature will be in our next release.     Thanks for reporting!

**Comment by odyssey4me** [comment]
@rackerjoe The metadata service via DHCP or the router is horribly unreliable. Two servers with the same configuration produce different results. It's very annoying. Forcing config-drive is definitely looking like a better option.

**Comment by claco** [comment]
Re-open for QE confirmation.

**Comment by jacobwagner** [comment]
closing for new qe workflow

**Comment by jacobwagner** [comment]
need to add nova-metafata-api vip to environment doc

**Comment by klevenstein** [comment]
Adding to the attribute block in the docs:

```
    "nova-api": "<haproxyVIP>",
    "nova-api-metadata": "<haproxyVIP>",
    "nova-ec2-<networkName>": "<haproxyVIP>",
    "nova-novnc-proxy": "<haproxyVIP>",
    "nova-xvpvnc-proxy": "<haproxyVIP>"
```

**Comment by xeregin** [comment]
When tailing `/var/log/nova/nova-api-metadata.log` on both controllers, I observed load balancing behavior.
I also verified the haproxy nova api metadata configs on both controllers.

Controller 1:`/etc/haproxy/haproxy.d/vs_nova-api-metadata.cfg`

```
listen nova-api-metadata 169.254.123.1:8775
    mode http
    balance roundrobin
    option forwardfor
    option httpchk
    option httplog
    server nova-api-metadata-1 10.127.101.24:8775 check
    server nova-api-metadata-2 10.127.101.5:8775 check
```

Controller 2:`/etc/haproxy/haproxy.d/vs_nova-api-metadata.cfg`

```
listen nova-api-metadata 169.254.123.1:8775
    mode http
    balance roundrobin
    option forwardfor
    option httpchk
    option httplog
    server nova-api-metadata-1 10.127.101.24:8775 check
    server nova-api-metadata-2 10.127.101.5:8775 check
```
