### ISSUE TITLE
[ceilometer] bind_host is not set in ceilometer.conf

### ISSUE THREAD

**Issue by Apsu** [rcbops/chef-cookbooks#714]
Ceilometer binds its API service to `0.0.0.0` (wildcard) by default, and when you have the `ceilometer-api` VIP in your environment, an haproxy virtual server is created to listen on the `ceilometer-api` port, but you can't bind any service to listen on $anyip:$port if a service is already listening on *:$port.

This causes haproxy to fail to restart entirely, breaking everything.

**Comment by cloudnull** [comment]
This was fixed in https://github.com/rcbops-cookbooks/ceilometer/pull/24
