### ISSUE TITLE
Monit monitors quantum post upgrade

### ISSUE THREAD

**Issue by cjoelrun** [rcbops/chef-cookbooks#722]
Monit is monitoring quantum post upgrade

These configs still exist in /etc/monit.d:
quantum-dhcp-agent.conf  quantum-l3-agent.conf  quantum-metadata-agent.conf  quantum-server.conf

To fix remove them and restart monit:
service monit restart

**Comment by claco** [comment]
@cjoelrun If you have an instance up an running... can you confirm that the process names are the same, just with neutron- instead of quantum- for these four? Thanks.

**Comment by cjoelrun** [comment]
neutron-dhcp-agent.conf
neutron-l3-agent.conf
neutron-metadata-agent.conf
neutron-server.conf

**Comment by claco** [comment]
Reopen for QE confirmation

**Comment by breu** [comment]
The code contributed to this point gets you almost there.  We need to remove the quantum monit configs first and then rely on the neutron config drops to trigger a restart of monit.  This comment is for you @claco

**Comment by claco** [comment]
Reopen for QE confirmation

**Comment by claco** [comment]
Reopen for QE confirmation.  Oh githubs. You closing issues all the times on pushs of other peoples branches.

**Comment by cjoelrun** [comment]
fixed
