### ISSUE TITLE
Ceilometer broken in HA

### ISSUE THREAD

**Issue by cjoelrun** [rcbops/chef-cookbooks#726]
Ceilometer was referencing the wrong vip:

```
[api]
##### BINDING #####
host=198.101.133.159
port=8777
```

Old haproxy config

```
[root@qa-centos-pool861 haproxy.d]# cat /etc/haproxy/haproxy.d/vs_ceilometer-api.cfg
listen ceilometer-api 169.254.123.1:8777
    mode http
    balance roundrobin
    option forwardfor
    option httpchk
    option httplog
    server ceilometer-api-1 198.101.133.210:8777 check
    server ceilometer-api-2 198.101.133.220:8777 check
```

401 unauthorized

```
Authentication required[root@qa-centos-pool861 haproxy.d]# curl -I http://198.101.133.220:8777
HTTP/1.0 401 Unauthorized
Date: Fri, 13 Dec 2013 23:24:48 GMT
Server: WSGIServer/0.1 Python/2.6.6
WWW-Authenticate: Keystone uri='http://198.101.133.159:35357'
Content-type: text/plain
Content-Length: 0
```

Needs to be:

```
[root@qa-centos-pool861 haproxy.d]# cat /etc/haproxy/haproxy.d/vs_ceilometer-api.cfg 
listen ceilometer-api 169.254.123.1:8777
    mode tcp
    balance source
    server ceilometer-api-1 198.101.133.210:8777 check
    server ceilometer-api-2 198.101.133.220:8777 check
```

**Comment by cloudnull** [comment]
This PR fixes the bind endpoint issues in the Ceilometer API https://github.com/rcbops-cookbooks/ceilometer/pull/26

**Comment by cloudnull** [comment]
Both fixes have been merged. Please retest I believe this should not longer be an issue.

**Comment by breu** [comment]
Have the sub modules been updated?

**Comment by brc** [comment]
openstack-ha and ceilometer pointers are updated in master;
doesn't look like v4.2.1rc is.

**Comment by cloudnull** [comment]
Good looking out @invsblduck,  @rackerjoe master submodules are up-to-date. The changes need to be cherry picked into 4.2.1rc. @claco We're looking at you Mr. release manager man.

**Comment by brc** [comment]
@cloudnull nice try, but per the new Release Mangler Manifesto, Chapter `TL;DR`, Section `Silence is Acceptance`, paragraph three, @claco waives all cherry-picking responsibilities:

```
If this bug needs fixed in grizzly/havana, fix the appropriate v4.x.xrc branches.
Cherry-pick -x from your master branch fix. PR it to that rc branch.
Someone will review and GBM it.
```

;-)

**Comment by cloudnull** [comment]
Code to fix this issue was merged by @claco. This should be resolved. @cjoelrun please confirm when possible.

**Comment by claco** [comment]
@rackerjoe actually. I just did the submodule needfuls.

**Comment by jacobwagner** [comment]
verified fixed on Centos

```
[root@qa-centos-pool879 ~]# cat /etc/haproxy/haproxy.d/vs_ceilometer-api.cfg 
listen ceilometer-api 169.254.123.1:8777
    mode tcp
    balance source
    server ceilometer-api-1 198.101.133.208:8777 check 
    server ceilometer-api-2 198.101.133.248:8777 check 
```

**Comment by jacobwagner** [comment]
verified fixed on Precise

root@qa-precise-pool935:~# cat /etc/haproxy/haproxy.d/vs_ceilometer-api.cfg 
listen ceilometer-api 169.254.123.1:8777
    mode tcp
    balance source
    server ceilometer-api-1 198.101.133.226:8777 check 
    server ceilometer-api-2 198.101.133.240:8777 check
