### ISSUE TITLE
[collectd] Support for Vagrant >= 1.3.0

### ISSUE THREAD

**Issue by darxriggs** [rcbops/chef-cookbooks#748]
- since Vagrant 1.3.0 these options are no longer available in Vagrantfile:
  
  config.ssh.max_tries = 40
  config.ssh.timeout   = 120
- see https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#130-september-5-2013

**Comment by darxriggs** [comment]
See the [vagrant-1.3.0-support](https://github.com/darxriggs/collectd/tree/vagrant-1.3.0-support) branch for the commits.

**Comment by claco** [comment]
FYI. When you submit PRs for issues opened here, please use the 'Fixes rcbops/chef-cookbooks#issuenum' hint in your git commit comment. This will cause github to automatically close the issue# when the PR is merged elsewhere.  Thanks!
