### ISSUE TITLE
[collectd] NoMethodError accessing node["monitoring"]["configs"]

### ISSUE THREAD

**Issue by darxriggs** [rcbops/chef-cookbooks#750]
- NoMethodError: undefined method `[]' for nil:NilClass recipes/default.rb:100
- http://stackoverflow.com/questions/19290710/ruby-syntax-in-chef-recipe

**Comment by darxriggs** [comment]
See the [attributes-fix](https://github.com/darxriggs/collectd/tree/attributes-fix) branch for the commits.

**Comment by claco** [comment]
PR Merged.
