### ISSUE TITLE
[RESOLVED] [horizon] OPENSTACK_KEYSTONE_URL not being configured properly when different osops_networks configured

### ISSUE THREAD

**Issue by jameswthorne** [rcbops/chef-cookbooks#753]
If you set the **management** osops_network to a different subnet than **nova** and **public** like so:

```
"osops_networks": {
    "nova": "192.168.10.0/24",
    "public": "192.168.10.0/24",
    "management": "10.10.10.0/24"
}
```

the following line in **/etc/openstack-dashboard/local_settings.py** on the controller node _is not_ being configured properly (notice the **http** missing) after a **chef-client** run:

```
OPENSTACK_KEYSTONE_URL = "://%s:5000/v2.0" % OPENSTACK_HOST
```

If you set all of the osops_networks to the same subnet like so:

```
"osops_networks": {
    "nova": "192.168.10.0/24",
    "public": "192.168.10.0/24",
    "management": "192.168.10.0/24"
}
```

the following line in **/etc/openstack-dashboard/local_settings.py** on the controller node _is_ being configured properly:

```
OPENSTACK_KEYSTONE_URL = "http://%s:5000/v2.0" % OPENSTACK_HOST
```

The Chef Template for **/etc/openstack-dashboard/local_settings.py** is located at **chef-cookbooks/cookbooks/horizon/templates/default/local_settings.py.erb** but I suspect the logic problem to be located in **chef-cookbooks/cookbooks/horizon/recipes/server.rb** between lines 142 and 156:

```
# If internal and service URI's are on same host and either is set for SSL
# Set the service proto to SSL
if node['horizon']['endpoint_scheme'].nil?
  if ks_internal_endpoint["host"] == ks_service_endpoint["host"]
    if [ks_internal_endpoint["scheme"],ks_service_endpoint["scheme"]].any?{|proto|
        proto == "https"
      }
      endpoint_scheme = "https"
    else
      endpoint_scheme = ks_service_endpoint["scheme"]
    end
  end
else
  endpoint_scheme = node['horizon']['endpoint_scheme']
end
```

The **management** osops_network parameter is responsible for setting up what IP address the internal Keystone API listens on and I think an additional else statement needs to be added to the block of code above to account for cases when the **management** subnet differs from **nova** and **public**.

**Comment by breu** [comment]
@jamesthorne can you post your vips": {} config from the environment as well as the roles assigned to these machines?

**Comment by jameswthorne** [comment]
Hey Joe,

This was not an HA environment. You only need to apply the **single-controller** role to a node with a Chef Environment file that has different subnets for the **management** and **public** osops_networks.

**Comment by jameswthorne** [comment]
I can consistently reproduce the problem with the following Vagrantfile: http://public.thornelabs.net/Vagrantfile-bug

The problem goes away with this Vagrantfile: http://public.thornelabs.net/Vagrantfile-nobug

Those two Vagrantfiles are virtually the same except for the **management** osops_networks parameter using different networks and an additional private network added to the controller node.

**Comment by breu** [comment]
@jamesthorne 

Can you test this patch out and let me know if it resolves the issue?

```
diff --git a/recipes/server.rb b/recipes/server.rb
index 010ec1c..0befddb 100644
--- a/recipes/server.rb
+++ b/recipes/server.rb
@@ -150,6 +150,8 @@ if node['horizon']['endpoint_scheme'].nil?
     else
       endpoint_scheme = ks_service_endpoint["scheme"]
     end
+  else
+    endpoint_scheme = ks_service_endpoint["scheme"]
   end
 else
   endpoint_scheme = node['horizon']['endpoint_scheme']
```

If it does you were correct and we missed one case

**Comment by breu** [comment]
so - the change resolves the error but the "Something went wrong" error still persists.  Investigating.

**Comment by jameswthorne** [comment]
I encountered the same thing you did. Looking into it as well.

**Comment by breu** [comment]
@jamesthorne 

I have a resolution here.  At current MySQL and RabbitMQ bind to the IP address on the management interface but the API services bind to the IP address on the public interface.

When using differing public and management network ranges you need:
1) the patch in https://github.com/rcbops/chef-cookbooks/issues/753#issuecomment-31547824
2) update your environment to set

```
{
  "override_attributes": {
    "horizon": {
      "endpoint_type": "publicURL"
    }
  }
}
```

Can you check this out and let me know if it resolves the issue?

**Comment by jameswthorne** [comment]
That looks to have fixed it. Thanks for your help!

**Comment by breu** [comment]
Thanks for checking.  I'll get the patch applied to our master branch and discuss with the team how we should handle service bindings to interfaces next week.

**Comment by infinitydon** [comment]
Hello Joe...

Please am using the RPC Sandbox (VirtualBox and Vmware), how do i fix this problem also.

Am getting the same error when accessing the Dashboard.

Thanks!

**Comment by breu** [comment]
You will need to patch the horizon cookbook and update your environment by hand to work around this.

**Comment by infinitydon** [comment]
Hi Joe,

Any procedure for this please?

I will appreciate a detailed guide for patching the horizon cookbook (may provide a file that I can use to replace the broken one?).

How do I go about updating my environment by hand... Sorry if am asking too much :)

**Comment by breu** [comment]
@infinitydon It is probably best to ask this question in https://community.rackspace.com/products/f/45/t/3211.  The gist of it is you will have to locate the horizon cookbook on your node, make the change noted above to recipes/server.rb, upload the cookbook, and then edit the environment with knife to add the horizon section.

However, this only affects horizon if you are using different IP ranges for public and management.  Is that the case in your failure? If not, then head over to the communities forum and ask your question.

**Comment by claco** [comment]
Re-open for QE confirmation.

**Comment by jacobwagner** [comment]
closing for new QE workflow

**Comment by claco** [comment]
Reopen for backport to 4.1.5

https://github.com/rcbops-cookbooks/horizon/pull/159

**Comment by claco** [comment]
v4.1.5 was tested for a specific upgrade and released as is. Closing.
