### ISSUE TITLE
Misspelled config file name in ec2api_modwsgi.py 

### ISSUE THREAD

**Issue by galstrom21** [rcbops/chef-cookbooks#754]
User filed this in launchpad: https://bugs.launchpad.net/nova/+bug/1266510

Offending line: https://github.com/rcbops-cookbooks/nova/blob/master/files/default/ec2api_modwsgi.py#L5

**Comment by breu** [comment]
from the launchpad bug:

```
I found a misspelling in file ec2api_modwsgi.py.

config_files = ['/etc/nova/api-paste.ini', '/etc/nova/nova.comf']

should be:

config_files = ['/etc/nova/api-paste.ini', '/etc/nova/nova.conf']
```
