### ISSUE TITLE
Add "sqlalchemy_pool_size" attribute

### ISSUE THREAD

**Issue by rpawlik** [rcbops/chef-cookbooks#755]
We need the ability to set a custom sqlalchemy_pool_size for the Neutron OVS plugin [1]. We've had to change this by hand several times and we have a customer requesting it be added as an attribute [2].

[1]
/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini

[2]
https://rax.io/rpcticket

**Comment by breu** [comment]
@rpawlik We aren't planning on cutting another tag for grizzly.  Did you intend for this change to be made against grizzly or havana?

reference - the default value for this option is 5

**Comment by rpawlik** [comment]
For future releases is fine.

**Comment by cbuben** [comment]
@rackerjoe Possible to get this in v4.1.5rc?  We need this in grizzly.
