### ISSUE TITLE
[openstack-logging] Remote logs are not being rotated on Rsyslog server

### ISSUE THREAD

**Issue by DavidWittman** [rcbops/chef-cookbooks#756]
The logs under `/var/log/rsyslog` are not being rotated by logrotate.

We're just dropping this down in /etc/logrotate.d/:

```
/var/log/rsyslog/*
/var/log/rsyslog/*/*
{
    rotate 3
    daily
    missingok
    notifempty
    compress
    postrotate
        reload rsyslog >/dev/null 2>&1 || true
    endscript
}
```

This seems to be working for us, but there are likely some corner cases which this doesn't cover, and I'm not sure if we need to reload rsyslog after each rotation.

**Comment by breu** [comment]
This seems to work more as expected

```
/var/log/rsyslog/*.log
/var/log/rsyslog/*/*.log
{
    rotate 3
    daily
    missingok
    delaycompress
    notifempty
    compress
    sharedscripts
    postrotate
        reload rsyslog >/dev/null 2>&1 || true
    endscript
}
```

@DavidWittman can you check the environment that you applied the original fix in to make sure that you aren't seeing any oddities in the logs that are rotate?

**Comment by breu** [comment]
Thanks for the report @DavidWittman.  This change will be in 4.2.2 when released.

**Comment by DavidWittman** [comment]
@rackerjoe I'm a little late to the party here, but using `*.log` instead of `*` for the match doesn't catch `/var/log/rsyslog/$HOST/syslog` and a few other logs as well.

Example:

``` bash
$ cat /etc/logrotate.d/rpc-logging.conf 
# logrotate script for rotating log files from OpenStack services.

/var/log/rsyslog/*.log
/var/log/rsyslog/*/*.log
{
  rotate 3
  daily
  missingok
  delaycompress
  notifempty
  compress
  sharedscripts
  postrotate
    reload rsyslog >/dev/null 2>&1 || true
  endscript
}
$ ll /var/log/rsyslog/compute01/
total 528
drwxr-xr-x 2 root adm    4096 Feb  3 16:41 ./
drwxr-xr-x 4 root root   4096 Feb  3 16:41 ../
-rw-r----- 1 root adm  497941 Feb  3 17:02 auth.log
-rw-r----- 1 root adm    4248 Feb  3 16:42 daemon.log
-rw-r----- 1 root adm     335 Feb  3 16:41 debug
-rw-r----- 1 root adm    1211 Feb  3 16:41 kern.log
-rw-r----- 1 root adm    1093 Feb  3 16:41 messages
-rw-r----- 1 root adm    5715 Feb  3 16:42 syslog
$ logrotate -f /etc/logrotate.d/rpc-logging.conf 
$ ll /var/log/rsyslog/compute01/
total 540
drwxr-xr-x 2 root adm    4096 Feb  3 17:03 ./
drwxr-xr-x 4 root root   4096 Feb  3 16:41 ../
-rw-r----- 1 root adm    1528 Feb  3 17:03 auth.log
-rw-r----- 1 root adm  505581 Feb  3 17:03 auth.log.1
-rw-r----- 1 root adm    4248 Feb  3 16:42 daemon.log.1
-rw-r----- 1 root adm     335 Feb  3 16:41 debug
-rw-r----- 1 root adm    1211 Feb  3 16:41 kern.log.1
-rw-r----- 1 root adm    1093 Feb  3 16:41 messages
-rw-r----- 1 root adm    5715 Feb  3 16:42 syslog
```

As you'd expect, syslog is one of the more bloated log files, so we'll need to ensure this is rotated here as well. `*/*` seems to have worked in my testing, but if there's a particular reason why we shouldn't be doing that, we can try some other things.

**Comment by claco** [comment]
I want to say this was partially intentional because the other way was too recursive and was removing things it shouldn't.

**Comment by DavidWittman** [comment]
@claco Oh yeah... It looks like that glob just causes it to rotate the rotated files as well, resulting in `syslog.1.1`, etc.

**Comment by cloudnull** [comment]
fixed. closing

**Comment by claco** [comment]
Reopen for backport to 4.1.5.

"add a logrotate.d conf file to rotate log files" is backported already for 4.1.4
"Include messages, syslog, and debug in logrotate" needs to go into 4.1.5

**Comment by claco** [comment]
v4.1.5 was tested for a specific upgrade and released as is. Closing.
