### ISSUE TITLE
[nova-network] Some OVS packages not updated in v4.1.2 to v4.1.3 upgrade

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/chef-cookbooks#758]
When upgrading from v4.1.2 to v4.1.3 on a Ubuntu host, the openvswitch-switch and openvswitch-common packages are not upgraded by chef-client.

This is because the do_package_upgrades flag only causes packages explicitly listed in the cookbooks to be upgraded, and while they are dependencies on quantum-plugin-openvswitch-agent, which is explicitly listed, there is no version in the dependency.

So the 1.4.0 versions of the packages satisfy the dependency and are not upgraded by apt, and because they are not explicitly listed, they are not upgraded by chef.

Upon reboot or ovs-ctl force-reload-kmod, you have 1.10 openvswitch module with 1.4 userland, and the agents refuse to start with:

> 2014-01-07 21:36:15    ERROR [quantum.plugins.openvswitch.agent.ovs_quantum_agent] Failed to create OVS patch port. Cannot have tunneling enabled on this agent, since this version of OVS does not support tunnels or patch ports. Agent terminated!

Manually running apt-get install openvswitch-switch openvswitch-common resolves the issue.

**Comment by breu** [comment]
code for this is has been merged and will be released in 4.1.4 and 4.2.2

**Comment by klevenstein** [comment]
Suggested release note, please comment:
"Rackspace Private Cloud v4.1.4 contains a fix for an issue with OpenVSwitch (OVS). Previously, upgrades to v4.1.3 would not upgrade the openvswitch-switch and openvswitch-common packages, which would cause the OVS agents to fail to start. The cookbooks have been updated to upgrade these packages correctly. Users who want to upgrade from v4.1.2 should upgrade directly to v4.1.4."

For the 4.2.2 release notes, replace "4.1.4" with "4.2.2".

**Comment by breu** [comment]
@klevenstein That looks good

**Comment by claco** [comment]
Re-open for QE confirmation.

**Comment by jacobwagner** [comment]
closing for new QE workflow
