### ISSUE TITLE
[knowledge center] v4.1.3 release notes missing required step

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/chef-cookbooks#759]
The release notes / upgrade guide[1] are missing a step to reboot the host, or run ovs-ctl force-reload-kmod, to make the new 1.10 openvswitch module active.

[1] http://www.rackspace.com/knowledge_center/article/rackspace-private-cloud-v-413-release-notes#upgrade-4.1.3

**Comment by klevenstein** [comment]
I'll add that in. At what point does the user have to do this—after Step 6, or sometime before?

**Comment by JCallicoat** [comment]
Actually... @Apsu, will there need to be an explicit ovs-ctl force-reload-kmod here, or will that be taken care of by the cookbooks when #758 is fixed?

**Comment by Apsu** [comment]
@JCallicoat The goal was to have it taken care of sanely in the cookbooks, but that would have to be a 4.1.4/4.2.2 bug fix release, so.... that said, for the 4.1.3/4.2.1 release notes/upgrade guide, it would be a manual step.

**Comment by JCallicoat** [comment]
@klevenstein So looks like there should be a reboot after Step 6.

**Comment by klevenstein** [comment]
Okay, I'll update accordingly.

**Comment by breu** [comment]
@klevenstein ok to close this one?

**Comment by klevenstein** [comment]
@jacobwagner was doing further investigations on this and indicated there might be more updating to come, so maybe not.

**Comment by breu** [comment]
ok @klevenstein.  I'll leave it open for now

**Comment by jacobwagner** [comment]
This is in the 4.1.4 release notes, closing
