### ISSUE TITLE
Not able to override novncproxy_base_url

### ISSUE THREAD

**Issue by kstev** [rcbops/chef-cookbooks#762]
Some users require the ability to set the novnc-proxy URL to something else (like a NAT'd IP)

If I set the following override attribute so that I may be able to view the console of an instance while accessing the the dashboard from a different network:
node['nova']['services']['novnc-proxy']['uri'] = "novncproxy_base_url=http://160.240.200.160:6080/vnc_auto.html"

...chef makes the following change to /etc/nova/nova.conf:
-novncproxy_host=10.240.0.176
+novncproxy_host=160.240.200.160

This is the change I was hoping for:
-novncproxy_base_url=http://10.240.0.5:6080/vnc_auto.html
+novncproxy_base_url=http://160.240.200.160:6080/vnc_auto.html

From 'cookbooks/nova/providers/conf.rb':
"novncproxy_base_url" => novncproxy_endpoint["uri"],

This correctly defaults to the IP of the controller(s) but I believe it should be able to be overridden..

Kevin

**Comment by ghost** [comment]
Hi!

I am one of those users!    =)

But, in fact, I need to change it to my FQDN, instead of the NAT'd IP.

Also, a bit off-topic but, I think we need to keep in mind, that, if the
"nova network", under "osops_networks" (Chef Env File), _is different_ from
the "public network", at least the "vncserver_listen = IP" must also listen
on the "public" side, instead on "nova network", otherwise, you'll not be
able to isolate the "nova" network traffic from the "public view", without
breaking the VNC access from the Dashboard. I know that this is a complete
different problem but, I think that it worth saying it here.

Just a note: if cookbooks start using (allowing) the entries be the "FQDN",
here and there, instead only IPs, it will help the transition for IPv6!
 ;-)

Thanks!
Thiago

**Comment by jameswthorne** [comment]
See if adding the following to the Chef Environment file under the **nova** JSON block helps. Change controller1 to another hostname or an IP address.

```
"nova": {
    "services": {
        "xvpvnc-proxy": {
            "host": "controller1"
        },
        "novnc-proxy": {
            "host": "controller1"
        }
    }
}
```

**Comment by ghost** [comment]
It's working!! Thank you!

**Comment by ghost** [comment]
Hey James,

Sorry to bother you guys with this but, I was playing a bit with the
following Chef Env overrides:

---

```
"nova": {
  "services": {
    "xvpvnc-proxy": {
      "host": "controller-1.domain.com"
    },
    "novnc-proxy": {
      "host": "controller-1.domain.com"
    },
    "novnc-server": {
      "host": "192.168.10.10"
    }
  },
```

---

And, at first (without declaring novnc-server too), it was working smoothly
but, after I added "novnc-server" to test, I ended up with the following
error:

---

...
- chef_gem[mysql] action install (up to date)
  [2014-01-14T00:22:46-02:00] ERROR: Can't find network management
  ...

## Full output: http://paste.openstack.org/show/61155/

But, I'm pretty sure I did not touched "osops_networks" (or
`single-controller` network setup), which still remain exactly as before:

---

```
  "osops_networks": {
    "nova": "192.168.10.0/24",
    "public": "192.168.10.0/24",
    "management": "10.10.10.0/24",
    "cinder": "10.30.30.0/24",
    "neutron": "10.20.20.0/24"
  }
```

---

After removing all _vnc_ overrides (i.e., in fact restoring previous
working chef env file by removing ""services":{...}"), the error "Can't
find network management" still persist! Very weird...

Any tips?! Chef-client doesn't run anymore...    :-/

Is there any "Chef cache" files to clean or something?!

Tks!
Thiago

**Comment by ghost** [comment]
Just for the record, I also tried it with:

---

```
    "novnc-server": {
      "host": "0.0.0.0"
    }
```

---

I'll try to reproduce the problem today, since I don't know precisely what
triggered it... Starting again from scratch (including brand new chef
server).

Best,
Thiago

**Comment by ghost** [comment]
Guys,

Please, ignore my latest two e-mails, it was my mistake, already fixed my
Chef Env File.

Sorry about the buzz...     =)

Anyway, I'm doing more tests to see if everything is okay...

Regards,
Thiago
