### ISSUE TITLE
external_network_bridge cannot be nothing ('' or ' ')

### ISSUE THREAD

**Issue by kstev** [rcbops/chef-cookbooks#763]
If I create an external provider network as type vlan with 'external_network_bridge" config option set to the default br-ex (or br-bond0), any router is unable to communicate with that network I believe because Neutron places the router qbxxxx port in that bridge.

If I adjust 'external_network_bridge to nothing:
root@controller1:~# head -n2 /etc/neutron/l3_agent.ini
[DEFAULT]
external_network_bridge =
root@controller1:~#

...the router is attached to br-int and the solution works as expected.

However, if I set the following in the environment:
['neutron']['ovs']['external_bridge'] = ''
# ...chef-client fails:
# Error executing action `run` on resource 'execute[create external bridge]'
## Mixlib::ShellOut::ShellCommandFailed

Expected process to exit with [0], but received '1'
---- Begin output of ovs-vsctl add-br   ----
STDOUT:
STDERR: ovs-vsctl: 'add-br' command requires at least 1 arguments
---- End output of ovs-vsctl add-br   ----
Ran ovs-vsctl add-br   returned 1

Should I simply set external_network_bridge to br-int? This seems counter-intuitive so here I am.

**Comment by busterswt** [comment]
Kevin - I have it set using double quotes and it works OK.

['neutron']['ovs']['external_bridge'] = ""

When the option is set, the router interface is placed in the specified bridge and provider attributes are not honored (ie. segmentation id). When left blank, the interface is placed in the integration bridge and adheres to flow rules based on the attributes.

**Comment by kstev** [comment]
Yes it does appear to work. Sorry about that.
