### ISSUE TITLE
[mysql-openstack] don't change master when replication broken on first master

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/chef-cookbooks#764]
The cookbook is currently checking results from `show slave status` for idempotency when setting up the first master as a slave of the second master; if it doesn't find 'Slave_SQL_Running' then it sets MASTER_LOG_FILE="mysql-binlog.000001", MASTER_LOG_POS=0. The problem is, the block runs even if replication has already been configured, but is broken at the time of the chef-client run on controller1. We should probably be checking 'Master_Log_File' and 'Read_Master_Log_Pos' instead of 'Slave_SQL_Running'.

**Comment by breu** [comment]
This change has gone into master, v4.2.2rc, and is gating against 4.1.4rc as we speak.  This will be in our next release.

**Comment by claco** [comment]
Re-open for QE confirmation.

**Comment by breu** [comment]
@claco did you want me to re-open?
