### ISSUE TITLE
[keepalived] v4.1.3 VIPS on both controllers after controller reboot

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/chef-cookbooks#765]
We've seen keepalived failing VIPs properly when both controllers are up, but if a controller is rebooted it comes back up with the VIPs, and the original controller still has them as well. People marrying dogs, dogs marrying oxen, oxen marrying fish; there's nothing but chaos and insanity down that road.

@Apsu 's theory is that there's a race between services that results in this behavior. I haven't been able to pinpoint the source of the problem. Changing keepalived to start at service level 99 (default: 20) seems to work around the issue and confirm the suspicion that there's a race condition somewhere.

**Comment by cloudnull** [comment]
fixed in newer HA deployments.

**Comment by xeregin** [comment]
I've verified that this has been solved by building a 4.2.2 cluster on public cloud and tested it by bringing down the controller without the vips. After rebooting, I verified that the vips did not replicate on the freshly booted controller.
