### ISSUE TITLE
Add RPC release identifier

### ISSUE THREAD

**Issue by DavidWittman** [rcbops/chef-cookbooks#772]
It's important to know which version of Rackspace Private Cloud you're running. I propose we start including a file (`/etc/rpc-release`?) with the installed version of RPC.

**Comment by breu** [comment]
@DavidWittman could you not look at the version of the cookbooks on the chef server?

**Comment by claco** [comment]
This will be easier in the stackforge stuff. We'll be down to one repo w/wrapper books, one VERSION file and we can just drop a copy on converge.

**Comment by DavidWittman** [comment]
@rackerjoe I could, but that's not always indicative of the running version. And it's easier to just cat out a file.

**Comment by breu** [comment]
I think the problem here could be that you could have a cookbook off-rev that wouldn't indicate the real cookbook versions deployed.  Let me think about this.

**Comment by claco** [comment]
At converge time:  `run_context.cookbook_collection[cookbook_name].metadata.version`

The trick is, which cookbook in 4.x should drop the file?

**Comment by breu** [comment]
Something in base should do it

**Comment by claco** [comment]
I vote osops-utils if we want to do this now.

**Comment by DavidWittman** [comment]
:+1: for osops-utils

**Comment by claco** [comment]
What's the time frame vs. need here? We're technical handed off to QE for 2 weeks of testing, but we suck at feature freeze. This also seems to be an enhancement-not-a-critical-bug.

**Comment by breu** [comment]
I will remember this one claco

**Comment by breu** [comment]
And I meant stash it in osops-utils and include it from the base role.

**Comment by claco** [comment]
No seriously. I'm not against doing it like, right now. Just asking for the sake of asking.

**Comment by breu** [comment]
Pepperidge farms remembers.
