### ISSUE TITLE
Submodule changes.

### ISSUE THREAD

**Issue by sdeaton2** [rcbops/chef-cookbooks#775]
Can the following be added to the .git/config to help with RPC installations, since we normally install these by hand anyway?

```
[submodule "cookbooks/cron"]
        url = https://github.com/opscode-cookbooks/cron.git
[submodule "cookbooks/chef-client"]
        url = https://github.com/opscode-cookbooks/chef-client.git
```

**Comment by sdeaton2** [comment]
The newer chef-client cookbook requires logrotate now...so.... also -

```
[submodule "cookbooks/logrotate"]
        url = https://github.com/opscode-cookbooks/logrotate.git
```

**Comment by claco** [comment]
There will have to be some testing work related to this. The chef-client cookbook has a slightly different way of thinking about config files (client.d) and the support-tools repo is dropping something different. The cookbook is pretty smart about being applied when client config exists though.

**Comment by breu** [comment]
@claco I think @sdeaton2 is just looking for inclusion of these cookbooks into the submodule refs, not that we actually consume them?  @sdeaton2 for this to work we need some way to test these cookbooks as our auto submodule update job may pull in code that breaks something...

**Comment by sdeaton2** [comment]
@rackerjoe - you hit the nail on the head... that's exactly what I am aiming for.  I just installed them on a new deploy I did yesterday, but that doesn't mean that everything is going to work everywhere, or that anything will work going forward.  What would you recommend for a way to setup testing for this?
