### ISSUE TITLE
swift submodule version wrong

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#779]
2014-01-30 16:40:07,299 rcbops.qa INFO: Uploading swift          [4.1.3]

**Comment by breu** [comment]
Is this on a 4.1.x to 4.2.x upgrade?   Swift is no longer included in the 4.2.x cookbooks and has not be updated.  

If it is just a 4.1.4 install then we'll have to take a look but not a showstopper.

**Comment by jacobwagner** [comment]
yeah 4.1.2 to 4.1.4

just put this here so i didnt forget, not release breaking so i didnt label it

**Comment by breu** [comment]
Ok.  Cool.

**Comment by claco** [comment]
I'll get this fixed as soon as I'm done locking my self out of all of my devices in github. :-0
