### ISSUE TITLE
[glance]: glance notifications will not be re-processed into the notifications queue if running single-controller role

### ISSUE THREAD

**Issue by breu** [rcbops/chef-cookbooks#786]
ha-controller[1-2] include the recipe glance::replicator which processes messages from the glance queue and redelivers them to the notifications queue for ceilometer to process.  If you are running with single-controller the messages are never redelivered and ceilometer will not process them.

**Comment by jacobwagner** [comment]
closing per new QE workflow

**Comment by claco** [comment]
Reopen for backport to 4.1.5

**Comment by claco** [comment]
Not applicable to grizzly.
