### ISSUE TITLE
haproxy on ha build

### ISSUE THREAD

**Issue by xeregin** [rcbops/chef-cookbooks#797]
On a fresh precise-ha build, haproxy is not running on the controller2 node when using our public cloud. This obviously causes issues when the controller node goes down.

**Comment by breu** [comment]
I verified this on 4.2.2rc new install in public cloud

**Comment by cloudnull** [comment]
I tested Ubuntu 4.2.2rc and it worked for me. Please provide version of cookbook deployment, if possible the env json and more data.

**Comment by xeregin** [comment]
This was an issue on 4.1.4rc and was fixed in 4.1.5rc.

**Comment by xeregin** [comment]
I tested this in public cloud using a 4.1.5rc as well as a 4.2.2rc build. The issue is no longer present in either one of these versions.
