### ISSUE TITLE
Runtime Error: Can't find network management

### ISSUE THREAD

**Issue by Pensu** [rcbops/chef-cookbooks#805]
Hi all,

I have been trying to install openstack as "allinone" node on a Ubuntu 12.04 machine. I have set up the role and when I tried to run chef-client, I get the following error:

[2014-02-24T07:42:28+00:00] ERROR: Can't find network management
# 
# Recipe Compile Error in /var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb
## RuntimeError

Can't find network management
## Cookbook Trace:

  /var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:52:in `rcb_exit_error'
  /var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:93:in`get_if_ip_for_net'
  /var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:75:in `get_ip_for_net'
  /var/chef/cache/cookbooks/mysql-openstack/recipes/server.rb:33:in`from_file'
## Relevant File Content:

/var/chef/cache/cookbooks/osops-utils/libraries/ip_location.rb:

 45:  
 46:    def rcb_exit_error(msg, options = {})
 47:      log_errors = options.fetch(:log_errors, true)
 48:  
 49:      if log_errors then
 50:        Chef::Log.error(msg)
 51:      end
 52>>     raise msg
 53:    end
 54:  
 55:    def rcb_safe_deref(hash, path, delim = ".")
 56:      current = hash
 57:  
 58:      debug("searching for #{path} in #{hash} with delimiter #{delim}")
 59:      path_ary = path.split(delim)
 60:      path_ary.each do |k|
 61:        if current and current.has_key?(k)

Running handlers:
[2014-02-24T07:42:28+00:00] ERROR: Running exception handlers
Running handlers complete

[2014-02-24T07:42:28+00:00] ERROR: Exception handlers complete
[2014-02-24T07:42:28+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 9 resources updated in 2129.244722608 seconds
[2014-02-24T07:42:30+00:00] ERROR: Can't find network management
[2014-02-24T07:42:30+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

Can you please help me figure out the issue here?

Thanks,
Peeyush Gupta

**Comment by breu** [comment]
Hello @Pensu 

Can you paste the environment that you are using and the IP address configuration on the box?

```
knife environment show <environment name> -Fj
ip a
```

Thanks!

**Comment by Pensu** [comment]
Hi @rackerjoe, I actually figured this out. I had management label missing out of my environment. Adding it did the trick and installation went successful. 

Thanks.

**Comment by datsrtn** [comment]
Hi @Pensu  I am getting same error, can you please tell me how to set management label..? 
shall i paste my environment details..? i am trying it on UBUNTU 12.04 LTS server 
i have two environments, _default,and "ubuntu".
please help in this issue. Thank you in advance.

**Comment by Pensu** [comment]
Hi @datsrtn you environment file should have all these attributes:

osops_networks": {
        "nova": "<novaNetworkCIDR>",
        "public": "<publicNetworkCIDR>",
        "management": "<managementNetworkCIDR>"
    }

Now, try to edit to your environment file and add all the three labels, specifically the last management one. I guess that should do the trick.

**Comment by datsrtn** [comment]
This is my environment 

root@ubuntu:~# knife environment show cookbook
chef_type:           environment
cookbook_versions:
default_attributes:
description:         OpenStack Cookbook environment
json_class:          Chef::Environment
name:                cookbook
override_attributes:
  developer_mode: false
  glance:
    image_upload: true
    images:
      cirros
      precise
  monitoring:
    metric_provider:  collectd
    procmon_provider: monit
  mysql:
    allow_remote_root: true
    root_network_acl:  %
  nova:
    libvirt:
      virt_type: qemu
    networks:
      bridge:       br100
      bridge_dev:   eth1
      dns1:         8.8.8.8
      dns2:         8.8.4.4
      ipv4_cidr:    10.10.100.0/24
      label:        public
      network_size: 255
      num_networks: 1
    ratelimit:
      api:
        enabled: true
      volume:
        enabled: true
  osops_networks:
    management: 172.16.0.0/24
    nova:       172.16.0.0/24
    public:     172.16.0.0/24

**Comment by Pensu** [comment]
Looks like you already have management label, my environment didnt have it, so adding it worked. I am not sure about your error. May be if there is any way to reload the environment or something.

**Comment by datsrtn** [comment]
ok, I will try it , Thanks a lot
