### ISSUE TITLE
Regions are hard coded throughout many cookbooks

### ISSUE THREAD

**Issue by breu** [rcbops/chef-cookbooks#808]
RegionOne is an attribute in the nova cookbook, but hard coded every where else.  This is present in v4.1.5rc and v4.2.2rc

**Comment by brc** [comment]
I had added a `region` attribute to osops-utils (https://github.com/rcbops-cookbooks/osops-utils/commit/f000a67c970af01d414f876af5ebe64f9586d4f2) and updated all the cookbooks to use it... When I switch to `v4.2.2rc` branch on my workstation I see it:

```
[(v4.2.2rc % u=) /git/rcbops/chef-cookbooks/cookbooks]$ gr region |grep -i osops
...
osops-utils/attributes/default.rb:default["osops"]["region"] = "RegionOne"    # default OpenStack region
openstack-ha/recipes/default.rb:        endpoint_region node["osops"]["region"]
cinder/recipes/cinder-setup.rb:  endpoint_region node["osops"]["region"]
exerstack/recipes/default.rb:    "keystone_region_name" => node["osops"]["region"],
glance/recipes/api.rb:  endpoint_region node["osops"]["region"]
nova-network/recipes/neutron-server.rb:  endpoint_region node["osops"]["region"]
nova-network/recipes/neutron-common.rb:    "auth_region" => node["osops"]["region"],
ceilometer/recipes/ceilometer-api.rb:  endpoint_region node["osops"]["region"]
nova/recipes/api-os-compute.rb:  endpoint_region node["osops"]["region"]
nova/recipes/nova-common.rb:    "nova_region" => node["osops"]["region"],
nova/recipes/api-ec2.rb:  endpoint_region node["osops"]["region"]
heat/recipes/heat-api.rb:  endpoint_region node["osops"]["region"]
heat/recipes/heat-api-cfn.rb:  endpoint_region node["osops"]["region"]
keystone/recipes/keystone-api.rb:  endpoint_region node["osops"]["region"]
keystone/README.md:      endpoint_region node["osops"]["region"]
```

Not accurate?

**Comment by brc** [comment]
Looks like it's still hard-coded in some places:

```
[(v4.2.2rc % u=) /git/rcbops/chef-cookbooks/cookbooks]$ gr regionone
kong/recipes/default.rb:  swift_store_region="RegionOne"
kong/recipes/default.rb:    swift_store_region="RegionOne"
kong/recipes/default.rb:    "keystone_region" => 'RegionOne',
kong/attributes/default.rb:default["swift"]["swift_store_region"] = "RegionOne"  # node_attribute
kong/.kitchen.yml:      swift_store_region: RegionOne
osops-utils/attributes/default.rb:default["osops"]["region"] = "RegionOne"    # default OpenStack region
swift/recipes/setup.rb:    endpoint_region "RegionOne"
openstack-ceph/recipes/radosgw.rb:  endpoint_region "RegionOne"
tempest/templates/default/tempest.conf.erb:region = RegionOne
keystone/attributes/default.rb:#          "RegionOne": {
keystone/resources/register.rb:attribute :endpoint_region, :kind_of => String, :default => "RegionOne"
keystone/resources/endpoint.rb:attribute :endpoint_region, :kind_of => String, :default => "RegionOne", :required => true
```

**Comment by breu** [comment]
Missed some

```
(DFW)(rax)[12:10:00] breu@mac:~/W/chef-cookbooks (master)$ grep -R RegionOne *
cookbooks/kong/.kitchen.yml:      swift_store_region: RegionOne
cookbooks/kong/attributes/default.rb:default["swift"]["swift_store_region"] = "RegionOne"  # node_attribute
cookbooks/kong/recipes/default.rb:  swift_store_region="RegionOne"
cookbooks/kong/recipes/default.rb:    swift_store_region="RegionOne"
cookbooks/kong/recipes/default.rb:    "keystone_region" => 'RegionOne',
cookbooks/openstack-ceph/recipes/radosgw.rb:  endpoint_region "RegionOne"
cookbooks/tempest/templates/default/tempest.conf.erb:region = RegionOne
```

**Comment by cloudnull** [comment]
The "tempest" needs to have the needful done as well. 
Additionally all of this needs to be backported into 4.1.5 Master before QE begins testing.

**Comment by brc** [comment]
I'm updating kong right now

**Comment by breu** [comment]
As @cloudnull said we need all of this work backported into 4.1.5rc.  @invsblduck please cherry-pick this work into 4.1.5rc

**Comment by brc** [comment]
## kong

master: https://github.com/rcbops-cookbooks/kong/pull/42
v4.1.5: https://github.com/rcbops-cookbooks/kong/pull/43
v4.2.2: https://github.com/rcbops-cookbooks/kong/pull/44

## tempest

master: https://github.com/rcbops-cookbooks/tempest/pull/9 
v4.1.5: https://github.com/rcbops-cookbooks/tempest/pull/10
v4.2.2: https://github.com/rcbops-cookbooks/tempest/pull/11

I don't think the super repos were updated for -rc branches, looks like i may have to PR those as well?

**Comment by claco** [comment]
Updated chef-cookbooks submodules for both branches.

**Comment by xeregin** [comment]
debian:~/rcbops/v4.1.5rc/chef-cookbooks/cookbooks# grep -ir "regionone" .
./glance/recipes/api.rb:  endpoint_region "RegionOne"
./exerstack/recipes/default.rb:    "keystone_region_name" => "RegionOne",
./cinder/recipes/cinder-setup.rb:  endpoint_region "RegionOne"
./kong/.kitchen.yml:      swift_store_region: RegionOne
./kong/recipes/default.rb:    "keystone_region" => 'RegionOne',
./nova/README.md:\* `nova["compute"]["region"]` - Region name, defaults to RegionOne
./nova/attributes/default.rb:default["nova"]["compute"]["region"] = "RegionOne"
./keystone/README.md:- endpoint_region: Default value is "RegionOne"
./keystone/README.md:      endpoint_region "RegionOne"

debian:~/rcbops/v4.2.2rc/chef-cookbooks/cookbooks# grep -ir "regionone" .
./kong/.kitchen.yml:      swift_store_region: RegionOne
./kong/recipes/default.rb:    "keystone_region" => 'RegionOne',
./keystone/README.md:- endpoint_region: Default value is "RegionOne"
./keystone/attributes/default.rb:#          "RegionOne": {
./keystone/resources/endpoint.rb:attribute :endpoint_region, :kind_of => String, :default => "RegionOne", :required => true
./keystone/resources/register.rb:attribute :endpoint_region, :kind_of => String, :default => "RegionOne"
./osops-utils/attributes/default.rb:default["osops"]["region"] = "RegionOne"    # default OpenStack region
./keystone/attributes/default.rb:#          "RegionOne": {
./keystone/recipes/keystone-api.rb:  endpoint_region "RegionOne"
./keystone/resources/endpoint.rb:attribute :endpoint_region, :kind_of => String, :default => "RegionOne", :required => true
./keystone/resources/register.rb:attribute :endpoint_region, :kind_of => String, :default => "RegionOne"
./ceilometer/recipes/ceilometer-api.rb:  endpoint_region "RegionOne"
./tempest/templates/default/tempest.folsom.conf.erb:aws_region = RegionOne
./swift/recipes/setup.rb:    endpoint_region "RegionOne"
./nova-network/templates/default/quantum.conf.erb:auth_region = RegionOne
./nova-network/recipes/quantum-server.rb:  endpoint_region "RegionOne"

**Comment by brc** [comment]
awesome.  i'll cherry-pick the original commits into `v4.1.5rc`.

**Comment by brc** [comment]
Fixes have been merged; you will still see `"RegionOne"` in a few places - particularly in the `kong` cookbook (used for gating), in the `tempest` cookbook for an old Folsom template , and in the `keystone` cookbook LWRPs (which can't use node attributes, AFAIK). 

https://github.com/rcbops-cookbooks/ceilometer/pull/37
https://github.com/rcbops-cookbooks/cinder/pull/94
https://github.com/rcbops-cookbooks/exerstack/pull/40
https://github.com/rcbops-cookbooks/glance/pull/198
https://github.com/rcbops-cookbooks/keystone/pull/165
https://github.com/rcbops-cookbooks/nova/pull/397
https://github.com/rcbops-cookbooks/nova-network/pull/130
https://github.com/rcbops-cookbooks/osops-utils/pull/168
