### ISSUE TITLE
[horizon]: Need to expose CertificateChainFile for customer SSL certificates

### ISSUE THREAD

**Issue by aaronsegura** [rcbops/chef-cookbooks#841]
Customer wants to install their own SSL with intermediary certificate for horizon.  We need to be able to set SSLCertificateChainFile via overrides.  This option is not currently in the dash-site.erb template file.

**Comment by rpawlik** [comment]
Made PR regarding this:

https://github.com/rcbops-cookbooks/horizon/pull/158

**Comment by aaronsegura** [comment]
After the patch was applied, chef overwrites the node["horizon"]["ssl"]["(cert|key)"] with the same horizon files as templates, overwriting the actual destination cert/key with the "example.controller.com" cert/key from the recipe.

**Comment by aaronsegura** [comment]
Sorry, I should have specified we have overridden the following attributes:

```
"horizon": {
  "ssl": {
    "chain": "<newIntermediaryfile>",
    "cert": "<newCertificateFile>",
    "key": "<newKeyFile>"
  }
},
```

**Comment by aaronsegura** [comment]
After further digging, this appears to be an issue with the cookbooks unrelated to this patch.  Opening a new issue.
