### ISSUE TITLE
configure problems with three node 

### ISSUE THREAD

**Issue by l0l1l2l3l2l1l0l** [rcbops/chef-cookbooks#843]
hello. i`m using chef and knife for building openstack tree node architecture with the instruction here 
( http://www.rackspace.com/knowledge_center/article/installing-openstack-with-rackspace-private-cloud-tools ). 

And i found that there is something strange on osops network for keystone.

On the controller node, there should be only two Network Interface(network hardware card) like eth0 for management network, eth1 for public network, The the architecture of my openstack is like this ( https://github-camo.global.ssl.fastly.net/c5bbff98a5ad9b4d82bcc841cdbd76c07a50b82e/687474703a2f2f692e696d6775722e636f6d2f467273756768652e6a7067 )

but when i`m trying to install keystone with chef-client command on controller node, an error occurs which goes like this "RuntimeError: Network 'nova' is not defined (check environment)"

should i use three nics on every openstack nodes? 

on the architecture above, the NICs that each nodes has is like below
controller - 2 nics (management, public)
network - 3 nics (management, nova(for vm), public)
compute - 2 nics (management, nova(for vm))

**Comment by breu** [comment]
@baryonicdm please attach a copy of your chef environment

**Comment by l0l1l2l3l2l1l0l** [comment]
hmm.. it seems that i should set nova  network on environment even if i don`t use nova network. 

i found how to solve this. i`ll close this. 
but the architecture of your environment can make user a bit confused.
