### ISSUE TITLE
[ceilometer/keystone/horizon] Ceilometer is throwing an tenant access error

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#845]
OS: Precise 12.04.3
release: V4.2.2rc
Looks like we arent installing a package that this got fixed in 

https://bugs.launchpad.net/horizon/+bug/1260528

```
root@qa-precise-pool285:~# dpkg -l | grep horizon
ii  python-django-horizon                1:2013.2.1-0ubuntu1~cloud0                          Django     module providing web based interaction with OpenStack
```

**Comment by rebelagentm** [comment]
Are we going to add this in?

**Comment by brc** [comment]
@jacobwagner is `1:2013.2.1-0ubuntu1~cloud0` the version with the bug, or the version we need?  Attempting to figure that out now.   I see `1:2014.1~b2-0ubuntu1~cloud0` currently available in icehouse repo only (http://ubuntu-cloud.archive.canonical.com/ubuntu/dists/precise-updates/icehouse/main/binary-amd64/Packages)

**Comment by brc** [comment]
ok i also see `1:2013.2.2-0ubuntu1~cloud0` on the mirrors - looking inside the packages for the bugfix now.

**Comment by brc** [comment]
Looks like it's the `openstack-dashboard` package with the bug; version `1:2013.2.2-0ubuntu1~cloud0` fixes it.

**Comment by brc** [comment]
The new package dropped last week, please let us know if the problem went away.  Thanks

**Comment by jacobwagner** [comment]
verified fixed same as following issue
https://github.com/rcbops/chef-cookbooks/issues/854
