### ISSUE TITLE
Ceilometer logrotate

### ISSUE THREAD

**Issue by jruels** [rcbops/chef-cookbooks#869]
Hello,
I noticed we do not have logrotate configured for Ceilometer. 

root@553085-DFW-CONTROL-1:~# ls -1 /etc/logrotate.d/
apache2
apport
apt
aptitude
cinder-api
cinder-scheduler
dpkg
glance-api
glance-registry
holland
keystone
monit
mysql-server
neutron-dhcp-agent
neutron-l3-agent
neutron-metadata-agent
neutron-plugin-openvswitch-agent
neutron-server
nova-api-ec2
nova-api-metadata
nova-api-os-compute
nova-cert
nova-conductor
nova-consoleauth
nova-manage
nova-novncproxy
nova-scheduler
openvswitch-switch
ppp
rabbitmq-server
rsyslog
ufw
unattended-upgrades
upstart

**Comment by jruels** [comment]
I will work on a pull request when I get back to hotel.

**Comment by breu** [comment]
Hey @aslaen - by default I don't believe that we drop any logrotates down except for the centralized syslog server and /var/log/rsyslog/*.  The logrotate config file should actually be owned by the package itself so this may be an upstream packaging issue.  Are you on ubuntu or centos?

**Comment by jruels** [comment]
Ubuntu. I will check the package. 

Thanks man
