### ISSUE TITLE
Cinder doesn't obey device name

### ISSUE THREAD

**Issue by cjoelrun** [rcbops/chef-cookbooks#873]
``` bash
nova  boot --image precise-image --flavor 2 --nic net-id=d128efaf-81bf-4b1d-9715-78da64e904e7 gretestvol --key-name camkey --block-device-mapping vdz=5957d34e-66c9-4bda-9416-ad6cc5da751f
```

or

``` bash
nova volume-attach a2782648-b8a1-4e29-ad13-fcd1249706d0 5957d34e-66c9-4bda-9416-ad6cc5da751f /dev/vdg
```

Nova doesn't respect device name. Puts it in next sequential device name.

```
ubuntu@gretestvol:~$ sudo fdisk -l
sudo: unable to resolve host gretestvol

Disk /dev/vda: 21.5 GB, 21474836480 bytes
4 heads, 32 sectors/track, 327680 cylinders, total 41943040 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00010d09

   Device Boot      Start         End      Blocks   Id  System
/dev/vda1   *        2048    41943039    20970496   83  Linux

Disk /dev/vdb: 10.7 GB, 10737418240 bytes
16 heads, 63 sectors/track, 20805 cylinders, total 20971520 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00000000

Disk /dev/vdb doesn't contain a valid partition table
```

**Comment by breu** [comment]
https://bugs.launchpad.net/nova/+bug/1088430

**Comment by kaushikb** [comment]
Does this need to be documented as a known issue in 4.2.2 ?

**Comment by claco** [comment]
@kaushikb no harm in doing so right? I suspect this has been around for a while unrelated to our cookbooks.

**Comment by klevenstein** [comment]
Suggested release note text:
== Nova ignores block storage device name ==
When attaching a volume, nova ignores the specified block storage device and instead places the volume in the next sequential device. This is related to OpenStack bug (https://bugs.launchpad.net/nova/+bug/1088430).

**Comment by breu** [comment]
Another report for the same thing:

https://bugzilla.redhat.com/show_bug.cgi?id=693372

KVM is working as expected.  OpenStack needs to reflect the fact that device assignments are not a feature of kvm.  They are in xen though.

**Comment by klevenstein** [comment]
I'll link to the Red Hat bug as well.

== Nova ignores block storage device name ==
When attaching a volume, nova ignores the specified block storage device and instead places the volume in the next sequential device. This is related to a known OpenStack bug. More information is available in OpenStack Bug 108830( https://bugs.launchpad.net/nova/+bug/1088430) and RHEL bug 693372 (https://bugzilla.redhat.com/show_bug.cgi?id=693372).

**Comment by klevenstein** [comment]
Added as a known issue in the release notes:
https://one.rackspace.com/download/attachments/79960660/rackspace-private-cloud-releasenotes-v4.2-20140314.pdf?version=1&modificationDate=1394826996592&api=v2
