### ISSUE TITLE
[ceilometer] upgrading from grizzly to havana needs python-swiftclient manual upgrade

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#876]
need to add python-swiftclient to manual upgrade packages docs / KC

if you dont this happens and it isnt fun to fix

https://gist.github.com/jacobwagner/ad384f7cf1bef94db000

**Comment by jacobwagner** [comment]
under Prep for Ubuntu

openstack ceilometer

**Comment by claco** [comment]
https://github.com/rcbops-cookbooks/ceilometer/pull/38

**Comment by claco** [comment]
I'll backport in the morning

**Comment by breu** [comment]
thanks @claco.

**Comment by jacobwagner** [comment]
verified fixed per https://github.com/rcbops/chef-cookbooks/issues/799
