### ISSUE TITLE
[nova-network] Enable l3 send_arp_for_ha

### ISSUE THREAD

**Issue by cjoelrun** [rcbops/chef-cookbooks#877]
"send_arp_for_ha" should be templated
It's a valid attribute and is defaulted correctly, but isn't laid down in

/etc/neutron/l3_agent.ini

```
(monster)chef-cookbooks$ grep send_arp_for_ha -r .
./cookbooks/nova/providers/conf.rb:    network_options["send_arp_for_ha"] = node[net_provider]["network"]["send_arp_for_ha"]
./cookbooks/nova-network/README.md:* `nova["network"]["send_arp_for_ha"]` - Send gratuitous ARPs for HA setup?
./cookbooks/nova-network/attributes/default.rb:default["nova"]["network"]["send_arp_for_ha"] = true
```

**Comment by cjoelrun** [comment]
ex: 

```
# OVS                                                                                                                                                                                
interface_driver = neutron.agent.linux.interface.OVSInterfaceDriver
send_arp_for_ha = 3
```

**Comment by cjoelrun** [comment]
Actually that is not a valid default, should be an integer.
0 for no gratuitous arp
1 or any number for how many arppings to send

**Comment by claco** [comment]
Yeah, and openstack docs say 0 is the default when in l3agent. Used to be =True in nova-network proper.

http://docs.openstack.org/trunk/config-reference/content/section_neutron-l3_agent.ini.conf.html

For grizzly, released in 2013.1, but not documented well:

https://bugs.launchpad.net/neutron/+bug/1042046

**Comment by cjoelrun** [comment]
Recommendation: https://bugs.launchpad.net/openstack-manuals/+bug/1093000

**Comment by claco** [comment]
So, now for the code dive.

Grizzly config file defaults imply 3: https://github.com/openstack/neutron/blob/stable/grizzly/etc/l3_agent.ini#L44
Grizzly code says 3: https://github.com/openstack/neutron/blob/stable/grizzly/quantum/agent/l3_agent.py#L127

Havana config file defaults imply 3: https://github.com/openstack/neutron/blob/stable/havana/etc/l3_agent.ini#L49
Havana code says 0: https://github.com/openstack/neutron/blob/stable/havana/neutron/agent/l3_agent.py#L165 

Master/Icehouse config file defaults imply 0: https://github.com/openstack/neutron/blob/master/etc/l3_agent.ini#L51
Master/Icehouse code says 0: https://github.com/openstack/neutron/blob/master/neutron/agent/l3_agent.py#L171

Definitely needed in havana. Will backport to grizzly just to be clear about intent so the next person doesn't have to code dive.

**Comment by claco** [comment]
This is used in the nova conf provider as True/False if the provider is nova: Will need to ponder how to move forward since nova-network isn't dead in icehouse.

https://github.com/rcbops-cookbooks/nova/blob/master/providers/conf.rb#L98

**Comment by claco** [comment]
After night slumber, I think I will do this:

Change the attribute from true to 3 (the default in Grizzly). Then change network_options in the nova conf provider to turn > 0 into true for nova networks. For quantum/neutron, just drop the value as-is.

Now curiously, havana/icehouse have the default as 0, citing this change:

https://github.com/openstack/neutron/commit/591ee00a67fbbe5f106ba12140b9f9420dee5907

Should we only turn it on in certain cases in our codebase, or enable it all of the time, or follow upstream (3 for grizzly, 0 for havana)?

**Comment by claco** [comment]
Keep it true/false. When true, drop 3 in quantum/havana.

Update: The attributes are namespaced. We can have both true/3 in nova, and a separate attr with 3 in neutron/grizzly.

**Comment by cjoelrun** [comment]
arp works, floating ips are reassignable without large downtime

```
[DEFAULT]
external_network_bridge = br-vmnet

metadata_ip = 10.127.101.67
metadata_port = 8775

send_arp_for_ha = 3
```

**Comment by claco** [comment]
Keeping this open and moving it to 4.1.5

**Comment by jacobwagner** [comment]
V4.1.5 l3_agent.ini file
Will verify fixed after testing

```
root@node98-sat6-lab:~# cat /etc/quantum/l3_agent.ini 
[DEFAULT]
external_network_bridge = br-int

metadata_ip = 10.127.101.67
metadata_port = 8775

send_arp_for_ha = 3

# OVS
interface_driver = quantum.agent.linux.interface.OVSInterfaceDriver
```

**Comment by jacobwagner** [comment]
Is this even an issue for grizzly seeing as how we dont have L3 supported?

**Comment by jacobwagner** [comment]
Verified that this is fixed, but since we didnt support L3 networks in Grizzly we are not testing it.

Closing
