### ISSUE TITLE
[Swift] Invalid user token

### ISSUE THREAD

**Issue by jedipunkz** [rcbops/chef-cookbooks#899]
I deployed Swift + Keystone with rcbops/chef-cookbooks. 

When I run 'swift stat' command, I got this error.

```
# source swift-openrc
# swift stat
Akccount HEAD failed: http://10.200.9.112:8080/v1/AUTH_14f5366cded54f6e96a2026b43e26671 401 Unauthorized
```

on  'role[swift-proxy-server]' node, these error messages are found.

<pre>
Mar 18 13:42:28 swift-proxy proxy-server Authorization failed for token MIIG-wYJKoZIhvcNAQcCoIIG8DCCBuwCAQExCTAHBgUrDgMCGjCCBVUGCSqGSIb3DQEHAaCCBUYEggVCeyJhY2Nlc3MiOiB7InRva2VuIjogeyJpc3N1ZWRfYXQiOiAiMjAxNC0wMy0xOFQwNDo0MjoyOC4yODk2NDUiLCAiZXhwaXJlcyI6ICIyMDE0LTAzLTE5VDA0OjQyOjI4WiIsICJpZCI6ICJwbGFjZWhvbGRlciIsICJ0ZW5hbnQiOiB7ImRlc2NyaXB0aW9uIjogImFkbWluIFRlbmFudCIsICJlbmFibGVkIjogdHJ1ZSwgImlkIjogIjE0ZjUzNjZjZGVkNTRmNmU5NmEyMDI2YjQzZTI2NjcxIiwgIm5hbWUiOiAiYWRtaW4ifX0sICJzZXJ2aWNlQ2F0YWxvZyI6IFt7ImVuZHBvaW50cyI6IFt7ImFkbWluVVJMIjogImh0dHA6Ly8xMC4yMDAuOS4xMTI6ODA4MC92MS9BVVRIXzE0ZjUzNjZjZGVkNTRmNmU5NmEyMDI2YjQzZTI2NjcxIiwgInJlZ2lvbiI6ICJSZWdpb25PbmUiLCAiaW50ZXJuYWxVUkwiOiAiaHR0cDovLzEwLjIwMC45LjExMjo4MDgwL3YxL0FVVEhfMTRmNTM2NmNkZWQ1NGY2ZTk2YTIwMjZiNDNlMjY2NzEiLCAiaWQiOiAiNzZmNWQ2YzliZDI4NDgxNzllYjJmMjIzNzYyZjJhMWUiLCAicHVibGljVVJMIjogImh0dHA6Ly8xMC4yMDAuOS4xMTI6ODA4MC92MS9BVVRIXzE0ZjUzNjZjZGVkNTRmNmU5NmEyMDI2YjQzZTI2NjcxIn1dLCAiZW5kcG9pbnRzX2xpbmtzIjogW10sICJ0eXBlIjogIm9iamVjdC1zdG9yZSIsICJuYW1lIjogInN3aWZ0In0sIHsiZW5kcG9pbnRzIjogW3siYWRtaW5VUkwiOiAiaHR0cDovLzEwLjIwMC45Ljg3OjM1MzU3L3YyLjAiLCAicmVnaW9uIjogIlJlZ2lvbk9uZSIsICJpbnRlcm5hbFVSTCI6ICJodHRwOi8vMTAuMjAwLjkuODc6NTAwMC92Mi4wIiwgImlkIjogIjQwNzkyMzQyYjViZjQ5OGNhNWE0ZTBiOTIxNzI2Zjk5IiwgInB1YmxpY1VSTCI6ICJodHRwOi8vMTAuMjAwLjkuODc6NTAwMC92Mi4wIn1dLCAiZW5kcG9pbnRzX2xpbmtzIjogW10sICJ0eXBlIjogImlkZW50aXR5IiwgIm5hbWUiOiAia2V5c3RvbmUifV0sICJ1c2VyIjogeyJ1c2VybmFtZSI6ICJhZG1pbiIsICJyb2xlc19saW5rcyI6IFtdLCAiaWQiOiAiMzgyMjE4YTc1MDI1NDZlNzg0MTQyMjIxMzRlYTZkNzYiLCAicm9sZXMiOiBbeyJuYW1lIjogImFkbWluIn0sIHsibmFtZSI6ICJLZXlzdG9uZUFkbWluIn0sIHsibmFtZSI6ICJLZXlzdG9uZVNlcnZpY2VBZG1pbiJ9LCB7Im5hbWUiOiAiX21lbWJlcl8ifV0sICJuYW1lIjogImFkbWluIn0sICJtZXRhZGF0YSI6IHsiaXNfYWRtaW4iOiAwLCAicm9sZXMiOiBbIjcxOGUxYmNmM2ExZTRhMTk5NzVhZWViOTViNzU2YjEzIiwgIjgxNThjZDk0M2ZlOTRlZTk5MTk5NmU1ZGM1MzEzYmFiIiwgImQwOWViYjljYTNmOTQ3OTNiZWM0NDBiY2EzZGRhMzNhIiwgIjlmZTJmZjllZTQzODRiMTg5NGE5MDg3OGQzZTkyYmFiIl19fX0xggGBMIIBfQIBATBcMFcxCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVVbnNldDEOMAwGA1UEBwwFVW5zZXQxDjAMBgNVBAoMBVVuc2V0MRgwFgYDVQQDDA93d3cuZXh
Mar 18 13:42:28 swift-proxy proxy-server Invalid user token - deferring reject downstream
</pre>

any idea ?

Thanks.

**Comment by claco** [comment]
@jedipunkz From the looks of the error, it looks like PKI in keystone is enabled, which is the default in our keystone cookbook, and I assume you're using 4.1.x/Grizzly?

So, if you disable PKI in your environment attribute overrides and rerun chef-client, this will change thekeystone config, that should fix your issue.

```
{"keystone": { "pki": {"enabled": false}}}

...
[signing]
token_format = UUID
```

If you want/need to leave PKI enabled, it might be an ssl certificate issue. Try hitting the keystone endpoints with `curl` to see what it has to say about the state of the ssl certificates .

FYI, Between 4.1.x/Grizzly and 4.2.x/Havana, we have deprecated and removed the swift cookbook. It was not being maintained or updated.

The latest swift cookbooks are here:

https://github.com/rcbops-cookbooks/swift-lite
https://github.com/rcbops-cookbooks/swift-private-cloud

The first one is a base cookbook that deploys a minimal set of packages and configs. The second one is now the full opinionated install of swift with logging, mail notifications, etc. They do not make any attempt to do the partitions or rings.

If you happen to like Ansible, here's a repo that automates the setup of swift/chef server, clients, etc.

https://github.com/rcbops/ansible-swift-private-cloud

**Comment by jedipunkz** [comment]
Hi, I resolved this issue by disabling PKI auth_token. Thanks.

and Thank you for your information of newer cookbooks. I will try that soon.

Thanks!
