### ISSUE TITLE
4.2.1 to 4.2.2 upgrade

### ISSUE THREAD

**Issue by cjoelrun** [rcbops/chef-cookbooks#907]
Situation:
Upgrading from 4.2.1 to 4.2.2

Issue:
keepalived gets restarted during the chef-client runs of the controllers.
This could cause connectivity problems if the failover doesn't happen fast enough.

Solution:

Stop keepalived on controller1
run chef-client on controller1
Start keepalived on controller1
Stop keepalived on controller2
run chef-client on controller2
Start keepalived on controller2
... proceed with rest of nodes normally

or

just run chef-client again after failure of controllers

**Comment by klevenstein** [comment]
Changing the procedure in the Upgrade Guide to match this process:

https://one.rackspace.com/download/attachments/81098256/421-422-upgrade.pdf?version=1&modificationDate=1396017850485&api=v2

...and yes, I'm aware that it says "controller2" twice. Fixing it.

**Comment by cjoelrun** [comment]
Yeah looks good aside from the controller2 twice :+1:
