### ISSUE TITLE
[monit] RPC v4.2.1 rabbitmq-server set to /bin/true

### ISSUE THREAD

**Issue by jameswthorne** [rcbops/chef-cookbooks#909]
This is the monit configuration file for the **mysql** service:

```
# This file autogenerated by Chef
# Do not edit, changes will be overwritten
check process mysqld matching "^(/bin/sh )?/usr/bin/mysqld_safe\b"
  start program = "/sbin/service mysqld start"
  stop program = "/sbin/service mysqld stop"
  if 5 restarts within 5 cycles then timeout
```

This is the monit configuration file for the **rabbitmq-server** service:

```
# This file autogenerated by Chef
# Do not edit, changes will be overwritten
check process rabbitmq-server matching "/etc/rabbitmq/rabbitmq"
  start program = "/sbin/service rabbitmq-server /bin/true"
  stop program = "/sbin/service rabbitmq-server /bin/true"
  if 5 restarts within 5 cycles then timeout
```

Why is the rabbitmq-server service command set to **/bin/true** instead of **start** or **stop**?

Running any **stop**, **start**, or **restart** monit commands on that service does nothing and results in an **Execution failed** monit summary message.

**Comment by breu** [comment]
This is already fixed in 4.2.2rc

**Comment by jameswthorne** [comment]
I should have checked. Thanks!

**Comment by claco** [comment]
@rackerjoe @jameswthorne Actually, it's not. It's slated for 4.2.3:  https://github.com/rcbops/chef-cookbooks/issues/860

**Comment by breu** [comment]
Well that is embarrassing.
