### ISSUE TITLE
[keystone] Active Directory user_name_attribute

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/chef-cookbooks#911]
Need to update the docs for AD

```
user_name_attribute: cn
```

needs to be 

```
user_name_attribute: sAMAccountName
```

for Active Directory

**Comment by klevenstein** [comment]
Fixed and created 2 sample code blocks, one for AD and one for LDAP.
https://one.rackspace.com/download/attachments/81098256/rackspace-private-cloud-ad-ldap-20140324.pdf?version=1&modificationDate=1395678123754&api=v2

**Comment by jacobwagner** [comment]
Docs look good, verifying +1
