### ISSUE TITLE
[nova] add support for libvirt_cpu_mode

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/chef-cookbooks#925]
We've discovered that on the hardware we use, the instances are ending up with a core2duo cpu model as a results of the default nova `libvirt_cpu_model=host-model`. This can be observed through `ps -ef | grep kvm` on a compute host.

While this is not really too much of an issue, we found that FreeBSD 9.x would not run on the compute hosts. This was due to the '+xsave' option being in the libvirt fallback option for the CPU. The host-model option resulted in libvirt trying to apply the 'SandyBridge' model, which doesn't work so libvirt falls back to the core2duo option which includes the '+xsave' CPU flag which hits a bug in KVM. That bug was resolved early this year, but I don't think it's hit any of the distro builds yet.

My bug report: https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1285708
Patch in KVM: https://lkml.org/lkml/2014/2/22/58

Anyway, to cut a long (confusing) story short the simple solution for us to overcome this is to set `libvirt_cpu_mode=none` in nova.conf.

**Comment by claco** [comment]
@odyssey4me "us" as in changing the attr in your environment file, or are you advocating we change the default in the cookbooks? Or, just an FYI for us? :-)

**Comment by odyssey4me** [comment]
LoL I see that the more recent cookbook for nova has it. Never mind - I'll adjust it in my environment file. :) The long story was more FYI, just in case someone else finds the same behavior.

**Comment by breu** [comment]
It appears that the cookbooks support setting ["nova"]["libvirt"]["libvirt_cpu_mode"] which will template  nova.conf with libvirt_cpu_model=["nova"]["libvirt"]["libvirt_cpu_model"] if libvirt_cpu_mode is == custom.  Both at the moment default to nil.

However, you should be able to set ["nova"]["libvirt"]["libvirt_cpu_mode"] in the environment to none and accomplish what you are trying to accomplish.

**Comment by breu** [comment]
and my comment is out of date now :)

**Comment by odyssey4me** [comment]
:) Interestingly, when I disabled the cpu model fallback in the libvirt config I got the same error mentioned in the Folsom release notes https://wiki.openstack.org/wiki/ReleaseNotes/Folsom#Known_Issues_2

`unsupported configuration: CPU specification not supported by hypervisor`

**Comment by claco** [comment]
@odyssey4me you're welcome?

**Comment by mancdaz** [comment]
@odyssey4me stop using folsom?

**Comment by breu** [comment]
@mancdaz folsom had the best network model ever and it worked!

**Comment by odyssey4me** [comment]
:) would you believe that I'm having to get an _upgrade_ to folsom done shortly

@claco Send me a poster, signed of course, so I can add it to my shrine. :p

**Comment by claco** [comment]
@odyssey4me be careful what you wish for. :-P

**Comment by odyssey4me** [comment]
Oh, and @claco if you think you have Chef hell now - remember Chef 10.18 (it ships in Ubuntu Precise) with couchdb? I still have two production environments running that... not for long though. :)

**Comment by odyssey4me** [comment]
Oops - it didn't ship with precise... it came from here: http://apt.opscode.com/dists/

**Comment by claco** [comment]
So, closing. :-)
