### ISSUE TITLE
Understanding chef cookbook issue

### ISSUE THREAD

**Issue by lollisoft** [rcbops/chef-cookbooks#982]
Hi,

I try to setup a swift cluster using my forked cookbook https://github.com/lollisoft/swift

After understanding how to provide environment (overriding attributes) using knife, I still get the same error:

==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/swift/recipes/common.rb:
==> default:  63:  # drop a ring puller script so we can dsh ring pulls
==> default:  64:  template "/etc/swift/pull-rings.sh" do
==> default:  65:    source "pull-rings.sh.erb"
==> default:  66:    owner "swift"
==> default:  67:    group "swift"
==> default:  68:    mode "0700"
==> default:  69:    variables({
==> default:  70>>               :builder_ip => git_service["host"],
==> default:  71:                :service_prefix => platform_options["service_pr
efix"]
==> default:  72:              })
==> default:  73:    only_if "/usr/bin/id swift"
==> default:  74:  end
==> default:  75:
==> default:  76:  execute "/etc/swift/pull-rings.sh" do
==> default:  77:    cwd "/etc/swift"
==> default:  78:    only_if "[ -x /etc/swift/pull-rings.sh ]"
==> default:  79:  end

After looking into the code I assume there is a failing git endpoint.

I do not yet have put all my code into git. Do I need to put my chef-repo into git first?

I also do not like to put all stuff at github. Can I add a git server to chef Server?

Or am I completely wrong with my assumptions?

Thanks, Lothar

**Comment by mancdaz** [comment]
Hi @lollisoft,

Apologies, but these chef cookbooks are no longer maintained - as you'll see the last commit was 18 months ago.

We have since developed a completely new Openstack deployment mechanism (including swift) using ansible in place of chef. If you're interested in checking this out, head on over to

https://github.com/openstack/openstack-ansible

Thanks!
